// Code generated by scripts/gen_sdk.py from 旺店通旗舰版 API 文档; DO NOT EDIT.
// 重新生成：python scripts/gen_sdk.py

package wdt

import "context"

// LogisticsService 提供 setting.Logistics.* 接口的封装。
type LogisticsService struct{ client *Client }

// PurchaseProviderService 提供 setting.PurchaseProvider.* 接口的封装。
type PurchaseProviderService struct{ client *Client }

// WarehouseService 提供 setting.Warehouse.* 接口的封装。
type WarehouseService struct{ client *Client }

// ShopService 提供 setting.Shop.* 接口的封装。
type ShopService struct{ client *Client }

// EmployeeService 提供 setting.Employee.* 接口的封装。
type EmployeeService struct{ client *Client }

// VirtualWarehouseService 提供 setting.strategy.VirtualWarehouse.* 接口的封装。
type VirtualWarehouseService struct{ client *Client }

// OperationReasonService 提供 setting.OperationReason.* 接口的封装。
type OperationReasonService struct{ client *Client }

// AddressService 提供 setting.Address.* 接口的封装。
type AddressService struct{ client *Client }

// CompositeService 提供 composite.Composite.* 接口的封装。
type CompositeService struct{ client *Client }

// SystemService 提供 system.Core.* 接口的封装。
type SystemService struct{ client *Client }

type LogisticsQueryLogisticsParams struct {
	// 物流编号：物流编号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 物流名称：物流名称（String，选填）
	LogisticsName string `json:"logistics_name,omitempty"`
	// 是否隐藏已停用：true:隐藏；false:不隐藏（boolean，选填）
	HideDelete bool `json:"hide_delete,omitempty"`
	// 是否需要刷新单量余额：0：否（默认）1：是 (当设置为 1 时，page_size 最大限制为 20)（bool，选填）
	NeedQuantity bool `json:"need_quantity,omitempty"`
}

type PurchaseProviderQueryDetailParams struct {
	// 供应商编号：供应商编号（String，选填）
	ProviderNo string `json:"provider_no,omitempty"`
	// 供应商名称：供应商名称（String，选填）
	ProviderName string `json:"provider_name,omitempty"`
	// 电话：电话（String，选填）
	Telno string `json:"telno,omitempty"`
	// 手机：手机（String，选填）
	Mobile string `json:"mobile,omitempty"`
	// 采购平台供应商账户名：采购平台供应商账户名（String，选填）
	Description string `json:"description,omitempty"`
	// 联系人：联系人（String，选填）
	Contact string `json:"contact,omitempty"`
	// 创建开始时间：创建开始时间（String，选填）
	CreatedBegin string `json:"created_begin,omitempty"`
	// 创建结束时间：创建结束时间（String，选填）
	CreatedEnd string `json:"created_end,omitempty"`
	// 修改开始时间：修改开始时间（String，选填）
	ModifiedBegin string `json:"modified_begin,omitempty"`
	// 修改结束时间：修改结束时间（String，选填）
	ModifiedEnd string `json:"modified_end,omitempty"`
	// 是否停用：1: 停用,0:未停用（Int，选填）
	IsDisabled int `json:"is_disabled,omitempty"`
	// 是否删除：0: 未删除 1:已删除（Int，选填）
	Deleted int `json:"deleted,omitempty"`
}

type PurchaseProviderPushProvider struct {
	// 供应商编号：供应商编号（String，必填）
	ProviderNo string `json:"provider_no"`
	// 供应商名称：供应商名称（String，必填）
	ProviderName string `json:"provider_name"`
	// 联系人：联系人（String，选填）
	Contact string `json:"contact,omitempty"`
	// 固话：固话（String，选填）
	Telno string `json:"telno,omitempty"`
	// 手机：手机（String，选填）
	Mobile string `json:"mobile,omitempty"`
	// 传真：传真（String，选填）
	Fax string `json:"fax,omitempty"`
	// QQ：QQ（String，选填）
	Qq string `json:"qq,omitempty"`
	// 邮编：邮编（String，选填）
	Zip string `json:"zip,omitempty"`
	// 旺旺：旺旺（String，选填）
	Wangwang string `json:"wangwang,omitempty"`
	// 邮箱：邮箱（String，选填）
	Email string `json:"email,omitempty"`
	// 网址：网址（String，选填）
	Website string `json:"website,omitempty"`
	// 地址：地址（String，选填）
	Address string `json:"address,omitempty"`
	// 到货天数：到货天数（Int，选填）
	ArriveCycleDays int `json:"arrive_cycle_days,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 是否停用：是否停用 0:否 1:是 默认为0（Int，选填）
	IsDisabled int `json:"is_disabled,omitempty"`
	// 银行卡号：银行卡号（String，选填）
	AccountBankNo string `json:"account_bank_no,omitempty"`
	// 收款银行：收款银行（String，选填）
	AccountBank string `json:"account_bank,omitempty"`
	// 收款人：收款人（String，选填）
	CollectName string `json:"collect_name,omitempty"`
	// 省份ID：省份ID，点击查看城市代码表（Int，选填）
	Province int `json:"province,omitempty"`
	// 城市ID：城市ID，点击查看城市代码表（Int，选填）
	City int `json:"city,omitempty"`
	// 地区ID：地区ID，点击查看城市代码表（Int，选填）
	District int `json:"district,omitempty"`
	// 供应商分组：供应商分组（String，选填）
	ProviderGroup string `json:"provider_group,omitempty"`
	// 跟进人：跟进人（传值为员工的员工昵称）（String，选填）
	Shortname string `json:"shortname,omitempty"`
}

type WarehouseQueryWarehouseParams struct {
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 仓库名称：仓库名称（String，选填）
	WarehouseName string `json:"warehouse_name,omitempty"`
	// 类型：1:普通（内部）,2:自流转,3:平台,4:京东沧海.6:抖音云仓,124：跨境 125:代发仓,126:分销委外（Int，选填）
	Type int `json:"type,omitempty"`
	// 子类型：0:默认,1:旺店通,2:菜鸟,3:百世WMS,4:巨沃,5:心怡WMS,6:科捷,7:吉客云,8:中通WMS,9:通天晓,10:酷仓宝WMS,11:景天WMS,12:网店管家笛佛WMS,13:九曳WMS,14:万里牛,15:麓客WMS,16:青图WMS(ERP),17:安鲜达WMS,18:顺丰WMS,19苏宁WMS,20:雅澳E,21:EMS,22:递四方,23:中邮WMS,24:云腾WMS,25:天图WMS;26:但丁WMS,27:e仓宝,28:仓卫士,29:山橙WMS,30橙蚁WMS,31:中山邮政WMS,32:赢路WMS,33:无忧WMS,34:筋斗云WMS,35:韵达WMS,36:GEEK（Int，选填）
	SubType int `json:"sub_type,omitempty"`
	// 开始时间：最后修改时间（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：最后修改时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 是否隐藏已停用数据：0:不隐藏; 1:隐藏已删除; 默认隐藏已删除（Int，选填）
	HideDelete int `json:"hide_delete,omitempty"`
}

type ShopQueryShopParams struct {
	// 店铺编号：店铺编号（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
	// 平台id：平台id,点击查看获取平台id（Int，选填）
	PlatformId int `json:"platform_id,omitempty"`
}

type ShopUpdateShopParams struct {
	// 店铺编号：店铺编号（String，必填）
	ShopNo string `json:"shop_no"`
	// 联系人：联系人（String，选填）
	Contact string `json:"contact,omitempty"`
	// 省：代码表参考城市代码表（Int，选填）
	Province int `json:"province,omitempty"`
	// 市：代码表参考城市代码表（Int，选填）
	City int `json:"city,omitempty"`
	// 区：代码表参考城市代码表（Int，选填）
	District int `json:"district,omitempty"`
	// 地址：地址（String，选填）
	Address string `json:"address,omitempty"`
	// 电话：电话（String，选填）
	Telno string `json:"telno,omitempty"`
	// 手机：手机（String，选填）
	Mobile string `json:"mobile,omitempty"`
	// 邮编：邮编（String，选填）
	Zip string `json:"zip,omitempty"`
	// 邮箱：邮箱（String，选填）
	Email string `json:"email,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 网址：网址（String，选填）
	Website string `json:"website,omitempty"`
}

type EmployeeSearchParams struct {
	// 开始时间：开始修改时间（date，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束修改时间（date，必填）
	EndTime string `json:"end_time"`
	// 员工编号：员工编号（String，选填）
	EmployeeNo string `json:"employee_no,omitempty"`
}

type VirtualWarehouseSearchParams struct {
	// 开始时间：修改时间, yyyy-MM-dd HH:mm:ss格式（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：yyyy-MM-dd HH:mm:ss格式（String，必填）
	EndTime string `json:"end_time"`
	// 虚拟仓编号：虚拟仓编号（String，选填）
	VirtualWarehouseNo string `json:"virtual_warehouse_no,omitempty"`
	// 实体仓编号：实体仓编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
}

type VirtualWarehouseQueryParams struct {
	// 虚拟仓编号：虚拟仓编号（String，选填）
	VirtualWarehouseNo string `json:"virtual_warehouse_no,omitempty"`
	// 实体仓编号：实体仓编号（String，选填）
	SysWarehouseNo string `json:"sys_warehouse_no,omitempty"`
}

type VirtualWarehouseStockSearchParams struct {
	// 开始时间：修改时间, yyyy-MM-dd HH:mm:ss格式（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：yyyy-MM-dd HH:mm:ss格式（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 商家编码：英文逗号分割,最多500个;；不填时间条件时必填（String，选填）
	SpecNos string `json:"spec_nos,omitempty"`
	// 虚拟仓编号：虚拟仓编号；不填时间条件时必填（String，选填）
	VirtualWarehouseNo string `json:"virtual_warehouse_no,omitempty"`
	// 实体仓编号：实体仓编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
}

type VirtualWarehouseCreateOrderMap struct {
	// 虚拟仓编号：虚拟仓编号（String，必填）
	VirtualWarehouseNo string `json:"virtual_warehouse_no"`
	// 单据类型：1:锁定分配,2:释放出库,3:虚拟仓间调拨,4:采购入库默认值为1（byte，选填）
	OrderType int `json:"order_type,omitempty"`
	// 目标虚拟仓编号：order_type=3时必传（String，选填）
	ToVirtualWarehouseNo string `json:"to_virtual_warehouse_no,omitempty"`
	// 是否预审核：仅在order_type=3时生效1：预设审核， 0：不审核（Int，选填）
	IsPreCheck int `json:"is_pre_check,omitempty"`
	// 库存不足则不审核：仅在order_type=3时生效，默认01：自动审核时严格检查库存，不足客户端内审核失败"存在库存不足货品，自动审核失败" 0：自动审核时不检查库存是否充足，有多少锁多少，直接审核通过（Int，选填）
	InsufficientStockNotPreCheck int `json:"insufficient_stock_not_pre_check,omitempty"`
	// 审核时间：仅在order_type=3时生效, 格式: yyyy-MM-dd HH:mm, 时间要大于当前服务器时间2分钟以上（String，选填）
	PreTime string `json:"pre_time,omitempty"`
	// 备注：默认为空（String，选填）
	Remark string `json:"remark,omitempty"`
	// 是否审核单据：1：审核， 0：不审核默认0不审核（Int，选填）
	IsCheck int `json:"is_check,omitempty"`
}

type VirtualWarehouseCreateDetail struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 实体仓编号：实体仓编号（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 入库数量：入库数量，默认为1（BigDecimal<19,4>，选填）
	Num any `json:"num,omitempty"`
	// 成本：成本，默认为0（BigDecimal<19,4>，选填）
	Price any `json:"price,omitempty"`
	// 采购在途数量：采购在途数量，默认为0（BigDecimal<19,4>，选填）
	PurchaseNum any `json:"purchase_num,omitempty"`
	// 自定义数量：自定义数量，默认为0（BigDecimal<19,4>，选填）
	FactoryNum any `json:"factory_num,omitempty"`
}

type VirtualWarehouseOrderSearchParams struct {
	// 开始时间：最后修改时间, yyyy-MM-dd HH:mm:ss格式（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：最后修改时间, yyyy-MM-dd HH:mm:ss格式（String，必填）
	EndTime string `json:"end_time"`
	// 虚拟仓编号：虚拟仓编号（String，选填）
	VirtualWarehouseNo string `json:"virtual_warehouse_no,omitempty"`
	// 实体仓编号：实体仓编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 单据类型：单据类型1：锁定入库2：释放出库3：调拨4：采购入库（Int，选填）
	OrderType int `json:"order_type,omitempty"`
}

type VirtualWarehouseStrategyAllocationCreateParams struct {
	// 分配范围：分配范围0：指定单据1：所有单据（Int，必填）
	Range int `json:"range"`
	// 分配模式：分配模式0：货品1：全局2：品牌（Int，必填）
	Mode int `json:"mode"`
	// 规则编码：规则编码（String，必填）
	RuleNo string `json:"rule_no"`
	// 规则名称：规则名称（String，必填）
	RuleName string `json:"rule_name"`
	// 关联单类型：关联单类型0：采购单1：其他入库业务单2：调拨单3：生产成品单（String，选填）
	SrcOrderType string `json:"src_order_type,omitempty"`
	// 关联单号：关联单号（String[]，选填）
	OrderNoList []string `json:"order_no_list,omitempty"`
	// 立刻执行对应策略：默认是（boolean，选填）
	ExecuteStrategy bool `json:"execute_strategy,omitempty"`
	// 旧规则编码：修改时 该字段必传不传或者传入为空的情况下为新建（仅支持修改mode=0的单据）（String，选填）
	OldRuleNo string `json:"old_rule_no,omitempty"`
}

type VirtualWarehouseStrategyAllocationCreateDetail struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 虚拟仓编码：虚拟仓编码（String，必填）
	VirWarehouseNo string `json:"vir_warehouse_no"`
	// 优先级：优先级（Int，选填）
	Priority int `json:"priority,omitempty"`
	// 锁定库存量：锁定库存量（BigDecimal，选填）
	Num float64 `json:"num,omitempty"`
	// 锁定比例：锁定比例（BigDecimal，选填）
	Ratio float64 `json:"ratio,omitempty"`
	// 品牌编码：品牌编码（String[]，选填）
	BrandNoList []string `json:"brand_no_list,omitempty"`
	// 明细主键id：主键id修改时必须传入只修改"优先级、锁定库存量、锁定比例"这三个字段（Integer，选填）
	RecId int `json:"rec_id,omitempty"`
}

type VirtualWarehouseStrategyAllocationQueryParams struct {
	// 仓库编号：虚拟仓仓库编号(暂不支持批量)(如果一个规则有多个使用其中一个搜索会将这个策略搜索出来也会显示这个策略全部的虚拟仓)（String，选填）
	VirtualWarehouseNo string `json:"virtual_warehouse_no,omitempty"`
	// 商家编码：商家编码（前缀）（String，选填）
	SpecNo string `json:"spec_no,omitempty"`
	// 货品编号：货品编号（前缀）（String，选填）
	GoodsNo string `json:"goods_no,omitempty"`
	// 规则编号：规则编号（前缀）（String，选填）
	RuleNo string `json:"rule_no,omitempty"`
	// 规则名称：规则名称（前缀）（String，选填）
	RuleName string `json:"rule_name,omitempty"`
}

type VirtualWarehouseReserveExtractAddOrderInfo struct {
	// 单号：单号（Int，必填）
	OrderNo int `json:"order_no"`
	// 单据类型：单据类型2：调拨单4：盘点单14：采购退货21：其他出库业务单（Int，必填）
	OrderType int `json:"order_type"`
}

type VirtualWarehouseReserveExtractAddDetail struct {
	// 商家编码：平台规格编码，不传默认为空（String，必填）
	SpecNo string `json:"spec_no"`
	// 虚拟仓编码：虚拟仓编码（String，必填）
	VirWarehouseNo string `json:"vir_warehouse_no"`
	// 入库虚拟仓：入库虚拟仓（String，选填）
	ToVirwarehouseNo string `json:"to_virwarehouse_no,omitempty"`
	// 释放优先级：释放优先级（Int，必填）
	Priority int `json:"priority"`
	// 出库数量：出库数量（BigDecimal，选填）
	Num float64 `json:"num,omitempty"`
}

type OperationReasonSearchParams struct {
	// 开始时间：最后修改时间, yyyy-MM-dd HH:mm:ss格式（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：最后修改时间, yyyy-MM-dd HH:mm:ss格式（String，选填）
	EndTime string `json:"end_time,omitempty"`
}

type AddressProvinceSearchParams struct {
	// 开始时间：最后修改时间（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：最后修改时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
}

type AddressCitySearchParams struct {
	// 省id：省id（Int，选填）
	ProvinceId int `json:"province_id,omitempty"`
	// 开始时间：最后修改时间（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：最后修改时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
}

type AddressDistrictSearchParams struct {
	// 市id：市id（Int，选填）
	CityId int `json:"city_id,omitempty"`
	// 开始时间：最后修改时间（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：最后修改时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
}

type CompositeCheckOrderByApiParam struct {
	// 单据类型：1=订单审核 2=退换单审核 3=调拨出入库单审核（int，必填）
	Type int `json:"type"`
	// 单号列表：对应类型的单号列表（List<String>，必填）
	OrderNoList []string `json:"order_no_list"`
}

// QueryLogistics 物流公司查询 - 获取ERP物流公司信息
// 不支持
//
// 结果不含已停用的物流
//
// 对应接口：setting.Logistics.queryLogistics
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.Logistics.queryLogistics
func (s *LogisticsService) QueryLogistics(ctx context.Context, params *LogisticsQueryLogisticsParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "setting.Logistics.queryLogistics", pager, params)
}

// QueryDetail 供应商查询 - 获取ERP供应商档案资料
// 支持
//
// 【权限校验】：供应商权限（旺店通客户端-采购-采购权限管理界面控制权限）
//
// 对应接口：setting.PurchaseProvider.queryDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.PurchaseProvider.queryDetail
func (s *PurchaseProviderService) QueryDetail(ctx context.Context, params *PurchaseProviderQueryDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "setting.PurchaseProvider.queryDetail", pager, params)
}

// Push 供应商信息推送 - 推送供应商档案资料给ERP
// 不支持
//
// 供应商创建和修改为一个接口，如果provider_no已存在为修改，不存在为新增
//
// 对应接口：setting.PurchaseProvider.push
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.PurchaseProvider.push
func (s *PurchaseProviderService) Push(ctx context.Context, provider *PurchaseProviderPushProvider) (*Response, error) {
	return s.client.Call(ctx, "setting.PurchaseProvider.push", provider)
}

// QueryWarehouse 仓库查询 - 获取ERP的仓库档案资料
// 支持
//
// 【权限校验】：仓库权限
//
// 对应接口：setting.Warehouse.queryWarehouse
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.Warehouse.queryWarehouse
func (s *WarehouseService) QueryWarehouse(ctx context.Context, params *WarehouseQueryWarehouseParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "setting.Warehouse.queryWarehouse", pager, params)
}

// QueryShop 店铺查询 - 获取ERP的店铺档案资料
// 不支持
// 店铺编号不传则全量获取
// 【权限校验】：店铺权限
//
// 对应接口：setting.Shop.queryShop
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.Shop.queryShop
func (s *ShopService) QueryShop(ctx context.Context, params *ShopQueryShopParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "setting.Shop.queryShop", pager, params)
}

// UpdateShop 店铺更新 - 更新ERP的店铺档案资料
//
// 对应接口：setting.Shop.updateShop
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.Shop.updateShop
func (s *ShopService) UpdateShop(ctx context.Context, params *ShopUpdateShopParams) (*Response, error) {
	return s.client.Call(ctx, "setting.Shop.updateShop", params)
}

// Search 员工查询 - 获取ERP的员工页面信息
// 支持
//
// 对应接口：setting.Employee.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.Employee.search
func (s *EmployeeService) Search(ctx context.Context, params *EmployeeSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "setting.Employee.search", pager, params)
}

// WarehouseSearch 虚拟仓仓库查询 - 获取ERP虚拟仓仓库信息
// 支持
// 起止时间跨度不超过30天
// 【权限校验】：虚拟仓权限，实体仓权限tips: 多个实体仓对应同一个虚拟仓的情况, 只要有其中一个仓库的权限就可以查到改虚拟仓
//
// 对应接口：setting.strategy.VirtualWarehouse.warehouseSearch
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.strategy.VirtualWarehouse.warehouseSearch
func (s *VirtualWarehouseService) WarehouseSearch(ctx context.Context, params *VirtualWarehouseSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "setting.strategy.VirtualWarehouse.warehouseSearch", pager, params)
}

// Query 虚拟仓信息查询 - 获取ERP虚拟仓、店铺、实体仓关联信息
//
// 对应接口：setting.strategy.VirtualWarehouse.query
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.strategy.VirtualWarehouse.query
func (s *VirtualWarehouseService) Query(ctx context.Context, params *VirtualWarehouseQueryParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "setting.strategy.VirtualWarehouse.query", pager, params)
}

// StockSearch 虚拟仓库存查询 - 获取ERP虚拟仓库存信息
// 支持
// start_time与end_time时间跨度不超过30天
// 权限校验：【仓库和虚拟仓权限】
//
// 对应接口：setting.strategy.VirtualWarehouse.stockSearch
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.strategy.VirtualWarehouse.stockSearch
func (s *VirtualWarehouseService) StockSearch(ctx context.Context, params *VirtualWarehouseStockSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "setting.strategy.VirtualWarehouse.stockSearch", pager, params)
}

// Create 虚拟仓单据创建 - 创建虚拟仓订单给ERP
//
// 权限校验：【虚拟仓权限】
//
// 对应接口：setting.strategy.VirtualWarehouse.create
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.strategy.VirtualWarehouse.create
func (s *VirtualWarehouseService) Create(ctx context.Context, orderMap *VirtualWarehouseCreateOrderMap, detailList []*VirtualWarehouseCreateDetail) (*Response, error) {
	return s.client.Call(ctx, "setting.strategy.VirtualWarehouse.create", orderMap, detailList)
}

// OrderSearch 虚拟仓单据查询 - 获取ERP虚拟仓单据信息
// 支持
// start_time与end_time时间跨度不超过30天
// 权限校验：【虚拟仓权限】tips:有虚拟仓权限的情况下, 只要有明细中某个实体仓的权限就可以查到单据
//
// 对应接口：setting.strategy.VirtualWarehouse.orderSearch
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.strategy.VirtualWarehouse.orderSearch
func (s *VirtualWarehouseService) OrderSearch(ctx context.Context, params *VirtualWarehouseOrderSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "setting.strategy.VirtualWarehouse.orderSearch", pager, params)
}

// StrategyAllocationCreate 虚拟仓库存分配策略创建 - 虚拟仓库存分配, 功能类似于客户端: 设置-策略设置-虚拟仓策略-虚拟仓库存分配
//
// param增加 旧规则编码，非必填项，若传入值为空则新建，有值则视为修改，仅修改“锁定库存”“锁定比例”“分配优先级”若入参和所填单据货品明细不一致，则直接报错
//
// 对应接口：setting.strategy.VirtualWarehouse.strategyAllocationCreate
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.strategy.VirtualWarehouse.strategyAllocationCreate
func (s *VirtualWarehouseService) StrategyAllocationCreate(ctx context.Context, params *VirtualWarehouseStrategyAllocationCreateParams, detail []*VirtualWarehouseStrategyAllocationCreateDetail) (*Response, error) {
	return s.client.Call(ctx, "setting.strategy.VirtualWarehouse.strategyAllocationCreate", params, detail)
}

// StrategyAllocationQuery 虚拟仓库存分配策略查询 - 获取ERP虚拟仓库存分配策略查询页面的数据
//
// 该接口查询只能查询分配模式为货品的情况（mode=0）
//
// 对应接口：setting.strategy.VirtualWarehouse.strategyAllocationQuery
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.strategy.VirtualWarehouse.strategyAllocationQuery
func (s *VirtualWarehouseService) StrategyAllocationQuery(ctx context.Context, params *VirtualWarehouseStrategyAllocationQueryParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "setting.strategy.VirtualWarehouse.strategyAllocationQuery", pager, params)
}

// ReserveExtractAdd 虚拟仓库存释放策略新建 - 虚拟仓库存分配, 功能类似于客户端: 设置-策略设置-虚拟仓策略-虚拟仓库存分配
//
// 对应接口：setting.strategy.VirtualWarehouse.reserveExtractAdd
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.strategy.VirtualWarehouse.reserveExtractAdd
func (s *VirtualWarehouseService) ReserveExtractAdd(ctx context.Context, orderInfo *VirtualWarehouseReserveExtractAddOrderInfo, detail []*VirtualWarehouseReserveExtractAddDetail) (*Response, error) {
	return s.client.Call(ctx, "setting.strategy.VirtualWarehouse.reserveExtractAdd", orderInfo, detail)
}

// Search 退换原因查询 - 查询退换原因
// 支持
// start_time和end_time最大跨度为30天。
//
// 对应接口：setting.OperationReason.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.OperationReason.search
func (s *OperationReasonService) Search(ctx context.Context, params *OperationReasonSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "setting.OperationReason.search", pager, params)
}

// ProvinceSearch 地址查询-省 - 接口描述: 查询省份信息
// 支持
//
// 对应接口：setting.Address.provinceSearch
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.Address.provinceSearch
func (s *AddressService) ProvinceSearch(ctx context.Context, params *AddressProvinceSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "setting.Address.provinceSearch", pager, params)
}

// CitySearch 地址查询-市 - 查询市信息
// 支持
// start_time和end_time最大跨度为30天。
// 查询需要传入省id或者起止时间，省id通过省查询接口获取
//
// 对应接口：setting.Address.citySearch
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.Address.citySearch
func (s *AddressService) CitySearch(ctx context.Context, params *AddressCitySearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "setting.Address.citySearch", pager, params)
}

// DistrictSearch 地址查询-区 - 查询区信息
// 支持
// start_time和end_time最大跨度为30天。
// 查询需要传入市id或者起止时间，市id通过市查询接口获取
//
// 对应接口：setting.Address.districtSearch
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.Address.districtSearch
func (s *AddressService) DistrictSearch(ctx context.Context, params *AddressDistrictSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "setting.Address.districtSearch", pager, params)
}

// CheckOrderByApi 综合审核接口 - 支持多种类型的单据进行审核 销售订单，退换单，调拨出入库单
// 校验 【店铺权限】【仓库权限】
//
// 对应接口：composite.Composite.checkOrderByApi
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=composite.Composite.checkOrderByApi
func (s *CompositeService) CheckOrderByApi(ctx context.Context, param *CompositeCheckOrderByApiParam) (*Response, error) {
	return s.client.Call(ctx, "composite.Composite.checkOrderByApi", param)
}

// Now 获取服务器当前时间 - 用于获取当前服务器时间, 可以同步此时间作为服务器时间
//
// 对应接口：system.Core.now
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=system.Core.now
func (s *SystemService) Now(ctx context.Context) (*Response, error) {
	return s.client.Call(ctx, "system.Core.now")
}
