// Code generated by scripts/gen_sdk.py from 旺店通旗舰版 API 文档; DO NOT EDIT.
// 重新生成：python scripts/gen_sdk.py

package wdt

import "context"

// GoodsService 提供 goods.Goods.* 接口的封装。
type GoodsService struct{ client *Client }

// SuiteService 提供 goods.Suite.* 接口的封装。
type SuiteService struct{ client *Client }

// ApiGoodsService 提供 goods.ApiGoods.* 接口的封装。
type ApiGoodsService struct{ client *Client }

// GoodsClassService 提供 goods.GoodsClass.* 接口的封装。
type GoodsClassService struct{ client *Client }

// GoodsBrandService 提供 goods.GoodsBrand.* 接口的封装。
type GoodsBrandService struct{ client *Client }

// CategoryService 提供 goods.Category.* 接口的封装。
type CategoryService struct{ client *Client }

// BarcodeService 提供 goods.Barcode.* 接口的封装。
type BarcodeService struct{ client *Client }

// BomService 提供 process.Bom.* 接口的封装。
type BomService struct{ client *Client }

// ProcessService 提供 process.Process.* 接口的封装。
type ProcessService struct{ client *Client }

// SettleProcessService 提供 finance.settle.process.* 接口的封装。
type SettleProcessService struct{ client *Client }

type GoodsPushGoodsInfo struct {
	// 货品编号：货品编号（String，必填）
	GoodsNo string `json:"goods_no"`
	// 货品名称：货品名称’（String，必填）
	GoodsName string `json:"goods_name"`
	// 分类名称：分类名称,不传或为空则默认为’无’（String，选填）
	ClassName string `json:"class_name,omitempty"`
	// 品牌名称：品牌名称, 不传或为空则默认为’无’（String，选填）
	BrandName string `json:"brand_name,omitempty"`
	// 基本单位名称：基本单位名称, 不传或为空则默认为’无’（String，选填）
	UnitName string `json:"unit_name,omitempty"`
	// 辅助单位名称：辅助单位名称, 不传或为空则默认为’无’（String，选填）
	AuxUnitName string `json:"aux_unit_name,omitempty"`
	// 标记名称：货品标记名称, 不传或为空则默认为’无’（String，选填）
	FlagName string `json:"flag_name,omitempty"`
	// 货品类别：默认0, 0：其它1：销售货品2：原材料3：包装物4：周转材料5：虚拟商品6：固定资产8：分装箱9：周期送货品10：赠品（Int，选填）
	GoodsType int `json:"goods_type,omitempty"`
	// 货品简称：货品简称（String，选填）
	ShortName string `json:"short_name,omitempty"`
	// 货品别名：货品别名（String，选填）
	Alias string `json:"alias,omitempty"`
	// 产地：产地（String，选填）
	Origin string `json:"origin,omitempty"`
	// 备注：货品备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 货品自定义属性1：货品自定义属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 货品自定义属性2：货品自定义属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 货品自定义属性3：货品自定义属性3（String，选填）
	Prop3 string `json:"prop3,omitempty"`
	// 货品自定义属性4：货品自定义属性4（String，选填）
	Prop4 string `json:"prop4,omitempty"`
	// 货品自定义属性5：货品自定义属性5（String，选填）
	Prop5 string `json:"prop5,omitempty"`
	// 货品自定义属性6：货品自定义属性6（String，选填）
	Prop6 string `json:"prop6,omitempty"`
	// 货品自定义属性7：货品自定义属性7（String，选填）
	Prop7 string `json:"prop7,omitempty"`
	// 货品自定义属性8：货品自定义属性8（String，选填）
	Prop8 string `json:"prop8,omitempty"`
	// 货品自定义属性9：货品自定义属性9（String，选填）
	Prop9 string `json:"prop9,omitempty"`
	// 货品自定义属性10：货品自定义属性10（String，选填）
	Prop10 string `json:"prop10,omitempty"`
	// 货品自定义属性11：货品自定义属性11（String，选填）
	Prop11 string `json:"prop11,omitempty"`
	// 货品自定义属性12：货品自定义属性12（String，选填）
	Prop12 string `json:"prop12,omitempty"`
	// 货品自定义属性13：货品自定义属性13（String，选填）
	Prop13 string `json:"prop13,omitempty"`
	// 货品自定义属性14：货品自定义属性14（String，选填）
	Prop14 string `json:"prop14,omitempty"`
	// 货品自定义属性15：货品自定义属性15（String，选填）
	Prop15 string `json:"prop15,omitempty"`
	// 货品自定义属性16：货品自定义属性16（String，选填）
	Prop16 string `json:"prop16,omitempty"`
	// 货品自定义属性17：货品自定义属性17（String，选填）
	Prop17 string `json:"prop17,omitempty"`
	// 货品自定义属性18：货品自定义属性18（String，选填）
	Prop18 string `json:"prop18,omitempty"`
	// 货品自定义属性19：货品自定义属性19（String，选填）
	Prop19 string `json:"prop19,omitempty"`
	// 货品自定义属性20：货品自定义属性20（String，选填）
	Prop20 string `json:"prop20,omitempty"`
	// 是否自动创建品牌和分类：如果品牌,分类不存在,是否自动创建.不填默认为false（bool，选填）
	AutoCreateBc bool `json:"auto_create_bc,omitempty"`
}

type GoodsPushSpecInfo struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 规格码：规格码（String，选填）
	SpecCode string `json:"spec_code,omitempty"`
	// 条码：条码（String，选填）
	Barcode string `json:"barcode,omitempty"`
	// 规格名称：规格名称（String，选填）
	SpecName string `json:"spec_name,omitempty"`
	// 仓库流程：默认0 （需要的仓库流程相加）2、无需验货 8、需要质检 16、无需拣货32、无需唯一码64、无需自动打印吊牌（Int，选填）
	WmsProcessMask int `json:"wms_process_mask,omitempty"`
	// 货品标签：默认无,可选值:自定义货品标签的名称(参考属性名称编辑页面->货品标签)多个标签使用英文逗号拼接（String，选填）
	GoodsLabel string `json:"goods_label,omitempty"`
	// 启用序列号：默认0,0不启用序列号 1强序列号 2弱序列号（Int，选填）
	SnType int `json:"sn_type,omitempty"`
	// 最低价：最低价（Decimal(19,4)，选填）
	LowestPrice float64 `json:"lowest_price,omitempty"`
	// 零售价：零售价（Decimal(19,4)，选填）
	RetailPrice float64 `json:"retail_price,omitempty"`
	// 批发价：批发价（Decimal(19,4)，选填）
	WholesalePrice float64 `json:"wholesale_price,omitempty"`
	// 会员价：会员价（Decimal(19,4)，选填）
	MemberPrice float64 `json:"member_price,omitempty"`
	// 市场价：市场价（Decimal(19,4)，选填）
	MarketPrice float64 `json:"market_price,omitempty"`
	// 有效期天数：有效期天数（smallint，选填）
	ValidityDays any `json:"validity_days,omitempty"`
	// 最佳销售天数：最佳销售天数（Int，选填）
	SalesDays int `json:"sales_days,omitempty"`
	// 最佳收货天数：最佳收货天数（Int，选填）
	ReceiveDays int `json:"receive_days,omitempty"`
	// 重量：重量（Decimal(19,4)，选填）
	Weight float64 `json:"weight,omitempty"`
	// 高：高（Decimal(19,4)，选填）
	Height float64 `json:"height,omitempty"`
	// 长：长（Decimal(19,4)，选填）
	Length float64 `json:"length,omitempty"`
	// 宽：宽（Decimal(19,4)，选填）
	Width float64 `json:"width,omitempty"`
	// 拆分：默认0, 0非大件1普通大件2独立大件（不可和小件一起发) 3按箱规拆分 -1非单发件（Int，选填）
	LargeType int `json:"large_type,omitempty"`
	// 单品自定义属性1：单品自定义属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 单品自定义属性2：单品自定义属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 单品自定义属性3：单品自定义属性3（String，选填）
	Prop3 string `json:"prop3,omitempty"`
	// 单品自定义属性4：单品自定义属性4（String，选填）
	Prop4 string `json:"prop4,omitempty"`
	// 单品自定义属性5：单品自定义属性5（String，选填）
	Prop5 string `json:"prop5,omitempty"`
	// 单品自定义属性6：单品自定义属性6（String，选填）
	Prop6 string `json:"prop6,omitempty"`
	// 单品自定义属性7：单品自定义属性7（String，选填）
	Prop7 string `json:"prop7,omitempty"`
	// 单品自定义属性8：单品自定义属性8（String，选填）
	Prop8 string `json:"prop8,omitempty"`
	// 单品自定义属性9：单品自定义属性9（String，选填）
	Prop9 string `json:"prop9,omitempty"`
	// 单品自定义属性10：单品自定义属性10（String，选填）
	Prop10 string `json:"prop10,omitempty"`
	// 单品自定义属性11：单品自定义属性11（String，选填）
	Prop11 string `json:"prop11,omitempty"`
	// 单品自定义属性12：单品自定义属性12（String，选填）
	Prop12 string `json:"prop12,omitempty"`
	// 单品自定义属性13：单品自定义属性13（String，选填）
	Prop13 string `json:"prop13,omitempty"`
	// 单品自定义属性14：单品自定义属性14（String，选填）
	Prop14 string `json:"prop14,omitempty"`
	// 单品自定义属性15：单品自定义属性15（String，选填）
	Prop15 string `json:"prop15,omitempty"`
	// 单品自定义属性16：单品自定义属性16（String，选填）
	Prop16 string `json:"prop16,omitempty"`
	// 单品自定义属性17：单品自定义属性17（String，选填）
	Prop17 string `json:"prop17,omitempty"`
	// 单品自定义属性18：单品自定义属性18（String，选填）
	Prop18 string `json:"prop18,omitempty"`
	// 单品自定义属性19：单品自定义属性19（String，选填）
	Prop19 string `json:"prop19,omitempty"`
	// 单品自定义属性20：单品自定义属性20（String，选填）
	Prop20 string `json:"prop20,omitempty"`
	// 自定义价格1：自定义价格1（Decimal(19,4)，选填）
	CustomPrice1 float64 `json:"custom_price1,omitempty"`
	// 自定义价格2：自定义价格2（Decimal(19,4)，选填）
	CustomPrice2 float64 `json:"custom_price2,omitempty"`
	// 允许低于成本：默认0,0:不允许,1 允许（boolean，选填）
	IsLowerCost bool `json:"is_lower_cost,omitempty"`
	// 图片链接：图片链接（String，选填）
	ImgUrl string `json:"img_url,omitempty"`
	// 单品备注：单品备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 销售积分：销售积分（Decimal(19,4)，选填）
	SaleScore float64 `json:"sale_score,omitempty"`
	// 打包积分：打包积分（Decimal(19,4)，选填）
	PackScore float64 `json:"pack_score,omitempty"`
	// 拣货积分：拣货积分（Decimal(19,4)，选填）
	PickScore float64 `json:"pick_score,omitempty"`
	// 分拣积分：分拣积分（Decimal(19,4)，选填）
	SortScore float64 `json:"sort_score,omitempty"`
	// 扫描积分：扫描积分（Decimal(19,4)，选填）
	ScanScore float64 `json:"scan_score,omitempty"`
	// 补货积分：补货积分（Decimal(19,4)，选填）
	SupplyScore float64 `json:"supply_score,omitempty"`
	// 上架积分：上架积分（Decimal(19,4)，选填）
	ShelveScore float64 `json:"shelve_score,omitempty"`
	// 入库积分：入库积分（Decimal(19,4)，选填）
	StockinScore float64 `json:"stockin_score,omitempty"`
	// 质检积分：质检积分（Decimal(19,4)，选填）
	InspectScore float64 `json:"inspect_score,omitempty"`
	// 分装积分：分装积分（Decimal(19,4)，选填）
	PackingScore float64 `json:"packing_score,omitempty"`
	// 操作积分：操作积分（Decimal(19,4)，选填）
	OperateScore float64 `json:"operate_score,omitempty"`
	// 称重积分：称重积分（Decimal(19,4)，选填）
	WeighScore float64 `json:"weigh_score,omitempty"`
	// 发货积分：发货积分（Decimal(19,4)，选填）
	ConsignScore float64 `json:"consign_score,omitempty"`
	// 税务编码：税务编码（String，选填）
	TaxCode string `json:"tax_code,omitempty"`
	// 基本单位名称：基本单位名称（String，选填）
	UnitName string `json:"unit_name,omitempty"`
	// 辅助单位名称：辅助单位名称（String，选填）
	AuxUnitName string `json:"aux_unit_name,omitempty"`
	// 辅助箱体积：记录单品按照箱规辅助单位计算出的完整箱规的体积（Decimal(19,4)，选填）
	AuxVolume float64 `json:"aux_volume,omitempty"`
	// 保质期计算方式：保质期计算方式0：按天1：按月默认0（Int，选填）
	ValidityType int `json:"validity_type,omitempty"`
}

type GoodsPush2GoodsInfo struct {
	// 货品编号：货品编号（String，必填）
	GoodsNo string `json:"goods_no"`
	// 货品名称：货品名称’（String，必填）
	GoodsName string `json:"goods_name"`
	// 分类名称：分类名称,不传或为空则默认为’无’（String，选填）
	ClassName string `json:"class_name,omitempty"`
	// 品牌名称：品牌名称, 不传或为空则默认为’无’（String，选填）
	BrandName string `json:"brand_name,omitempty"`
	// 基本单位名称：基本单位名称, 不传或为空则默认为’无’（String，选填）
	UnitName string `json:"unit_name,omitempty"`
	// 辅助单位名称：辅助单位名称, 不传或为空则默认为’无’（String，选填）
	AuxUnitName string `json:"aux_unit_name,omitempty"`
	// 标记名称：货品标记名称, 不传或为空则默认为’无’（String，选填）
	FlagName string `json:"flag_name,omitempty"`
	// 货品类别：默认0, 0：其它1：销售货品2：原材料3：包装物4：周转材料5：虚拟商品6：固定资产8：分装箱9：周期送货品10：赠品（Int，选填）
	GoodsType int `json:"goods_type,omitempty"`
	// 货品简称：货品简称（String，选填）
	ShortName string `json:"short_name,omitempty"`
	// 货品别名：货品别名（String，选填）
	Alias string `json:"alias,omitempty"`
	// 产地：产地（String，选填）
	Origin string `json:"origin,omitempty"`
	// 备注：货品备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 货品自定义属性1：货品自定义属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 货品自定义属性2：货品自定义属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 货品自定义属性3：货品自定义属性3（String，选填）
	Prop3 string `json:"prop3,omitempty"`
	// 货品自定义属性4：货品自定义属性4（String，选填）
	Prop4 string `json:"prop4,omitempty"`
	// 货品自定义属性5：货品自定义属性5（String，选填）
	Prop5 string `json:"prop5,omitempty"`
	// 货品自定义属性6：货品自定义属性6（String，选填）
	Prop6 string `json:"prop6,omitempty"`
	// 货品自定义属性7：货品自定义属性7（String，选填）
	Prop7 string `json:"prop7,omitempty"`
	// 货品自定义属性8：货品自定义属性8（String，选填）
	Prop8 string `json:"prop8,omitempty"`
	// 货品自定义属性9：货品自定义属性9（String，选填）
	Prop9 string `json:"prop9,omitempty"`
	// 货品自定义属性10：货品自定义属性10（String，选填）
	Prop10 string `json:"prop10,omitempty"`
	// 货品自定义属性11：货品自定义属性11（String，选填）
	Prop11 string `json:"prop11,omitempty"`
	// 货品自定义属性12：货品自定义属性12（String，选填）
	Prop12 string `json:"prop12,omitempty"`
	// 货品自定义属性13：货品自定义属性13（String，选填）
	Prop13 string `json:"prop13,omitempty"`
	// 货品自定义属性14：货品自定义属性14（String，选填）
	Prop14 string `json:"prop14,omitempty"`
	// 货品自定义属性15：货品自定义属性15（String，选填）
	Prop15 string `json:"prop15,omitempty"`
	// 货品自定义属性16：货品自定义属性16（String，选填）
	Prop16 string `json:"prop16,omitempty"`
	// 货品自定义属性17：货品自定义属性17（String，选填）
	Prop17 string `json:"prop17,omitempty"`
	// 货品自定义属性18：货品自定义属性18（String，选填）
	Prop18 string `json:"prop18,omitempty"`
	// 货品自定义属性19：货品自定义属性19（String，选填）
	Prop19 string `json:"prop19,omitempty"`
	// 货品自定义属性20：货品自定义属性20（String，选填）
	Prop20 string `json:"prop20,omitempty"`
	// 是否自动创建品牌和分类：如果品牌,分类不存在,是否自动创建.不填默认为false（bool，选填）
	AutoCreateBc bool `json:"auto_create_bc,omitempty"`
}

type GoodsPush2SpecInfo struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 规格码：规格码（String，选填）
	SpecCode string `json:"spec_code,omitempty"`
	// 条码：条码（String，选填）
	Barcode string `json:"barcode,omitempty"`
	// 规格名称：规格名称（String，选填）
	SpecName string `json:"spec_name,omitempty"`
	// 仓库流程：默认0 （需要的仓库流程相加）2、无需验货 8、需要质检 16、无需拣货32、无需唯一码64、无需自动打印吊牌（Int，选填）
	WmsProcessMask int `json:"wms_process_mask,omitempty"`
	// 货品标签：默认无,可选值:自定义货品标签的名称(参考属性名称编辑页面->货品标签)多个标签使用英文逗号拼接（String，选填）
	GoodsLabel string `json:"goods_label,omitempty"`
	// 启用序列号：默认0,0不启用序列号 1强序列号 2弱序列号（Int，选填）
	SnType int `json:"sn_type,omitempty"`
	// 最低价：最低价（Decimal(19,4)，选填）
	LowestPrice float64 `json:"lowest_price,omitempty"`
	// 零售价：零售价（Decimal(19,4)，选填）
	RetailPrice float64 `json:"retail_price,omitempty"`
	// 批发价：批发价（Decimal(19,4)，选填）
	WholesalePrice float64 `json:"wholesale_price,omitempty"`
	// 会员价：会员价（Decimal(19,4)，选填）
	MemberPrice float64 `json:"member_price,omitempty"`
	// 市场价：市场价（Decimal(19,4)，选填）
	MarketPrice float64 `json:"market_price,omitempty"`
	// 有效期天数：有效期天数（smallint，选填）
	ValidityDays any `json:"validity_days,omitempty"`
	// 最佳销售天数：最佳销售天数（Int，选填）
	SalesDays int `json:"sales_days,omitempty"`
	// 最佳收货天数：最佳收货天数（Int，选填）
	ReceiveDays int `json:"receive_days,omitempty"`
	// 重量：重量（Decimal(19,4)，选填）
	Weight float64 `json:"weight,omitempty"`
	// 高：高（Decimal(19,4)，选填）
	Height float64 `json:"height,omitempty"`
	// 长：长（Decimal(19,4)，选填）
	Length float64 `json:"length,omitempty"`
	// 宽：宽（Decimal(19,4)，选填）
	Width float64 `json:"width,omitempty"`
	// 拆分：默认0, 0非大件1普通大件2独立大件（不可和小件一起发) 3按箱规拆分 -1非单发件（Int，选填）
	LargeType int `json:"large_type,omitempty"`
	// 单品自定义属性1：单品自定义属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 单品自定义属性2：单品自定义属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 单品自定义属性3：单品自定义属性3（String，选填）
	Prop3 string `json:"prop3,omitempty"`
	// 单品自定义属性4：单品自定义属性4（String，选填）
	Prop4 string `json:"prop4,omitempty"`
	// 单品自定义属性5：单品自定义属性5（String，选填）
	Prop5 string `json:"prop5,omitempty"`
	// 单品自定义属性6：单品自定义属性6（String，选填）
	Prop6 string `json:"prop6,omitempty"`
	// 单品自定义属性7：单品自定义属性7（String，选填）
	Prop7 string `json:"prop7,omitempty"`
	// 单品自定义属性8：单品自定义属性8（String，选填）
	Prop8 string `json:"prop8,omitempty"`
	// 单品自定义属性9：单品自定义属性9（String，选填）
	Prop9 string `json:"prop9,omitempty"`
	// 单品自定义属性10：单品自定义属性10（String，选填）
	Prop10 string `json:"prop10,omitempty"`
	// 单品自定义属性11：单品自定义属性11（String，选填）
	Prop11 string `json:"prop11,omitempty"`
	// 单品自定义属性12：单品自定义属性12（String，选填）
	Prop12 string `json:"prop12,omitempty"`
	// 单品自定义属性13：单品自定义属性13（String，选填）
	Prop13 string `json:"prop13,omitempty"`
	// 单品自定义属性14：单品自定义属性14（String，选填）
	Prop14 string `json:"prop14,omitempty"`
	// 单品自定义属性15：单品自定义属性15（String，选填）
	Prop15 string `json:"prop15,omitempty"`
	// 单品自定义属性16：单品自定义属性16（String，选填）
	Prop16 string `json:"prop16,omitempty"`
	// 单品自定义属性17：单品自定义属性17（String，选填）
	Prop17 string `json:"prop17,omitempty"`
	// 单品自定义属性18：单品自定义属性18（String，选填）
	Prop18 string `json:"prop18,omitempty"`
	// 单品自定义属性19：单品自定义属性19（String，选填）
	Prop19 string `json:"prop19,omitempty"`
	// 单品自定义属性20：单品自定义属性20（String，选填）
	Prop20 string `json:"prop20,omitempty"`
	// 自定义价格1：自定义价格1（Decimal(19,4)，选填）
	CustomPrice1 float64 `json:"custom_price1,omitempty"`
	// 自定义价格2：自定义价格2（Decimal(19,4)，选填）
	CustomPrice2 float64 `json:"custom_price2,omitempty"`
	// 允许低于成本：默认0,0:不允许,1 允许（boolean，选填）
	IsLowerCost bool `json:"is_lower_cost,omitempty"`
	// 图片链接：图片链接（String，选填）
	ImgUrl string `json:"img_url,omitempty"`
	// 单品备注：单品备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 销售积分：销售积分（Decimal(19,4)，选填）
	SaleScore float64 `json:"sale_score,omitempty"`
	// 打包积分：打包积分（Decimal(19,4)，选填）
	PackScore float64 `json:"pack_score,omitempty"`
	// 拣货积分：拣货积分（Decimal(19,4)，选填）
	PickScore float64 `json:"pick_score,omitempty"`
	// 分拣积分：分拣积分（Decimal(19,4)，选填）
	SortScore float64 `json:"sort_score,omitempty"`
	// 扫描积分：扫描积分（Decimal(19,4)，选填）
	ScanScore float64 `json:"scan_score,omitempty"`
	// 补货积分：补货积分（Decimal(19,4)，选填）
	SupplyScore float64 `json:"supply_score,omitempty"`
	// 上架积分：上架积分（Decimal(19,4)，选填）
	ShelveScore float64 `json:"shelve_score,omitempty"`
	// 入库积分：入库积分（Decimal(19,4)，选填）
	StockinScore float64 `json:"stockin_score,omitempty"`
	// 质检积分：质检积分（Decimal(19,4)，选填）
	InspectScore float64 `json:"inspect_score,omitempty"`
	// 分装积分：分装积分（Decimal(19,4)，选填）
	PackingScore float64 `json:"packing_score,omitempty"`
	// 操作积分：操作积分（Decimal(19,4)，选填）
	OperateScore float64 `json:"operate_score,omitempty"`
	// 称重积分：称重积分（Decimal(19,4)，选填）
	WeighScore float64 `json:"weigh_score,omitempty"`
	// 发货积分：发货积分（Decimal(19,4)，选填）
	ConsignScore float64 `json:"consign_score,omitempty"`
	// 税务编码：税务编码（String，选填）
	TaxCode string `json:"tax_code,omitempty"`
	// 基本单位名称：基本单位名称（String，选填）
	UnitName string `json:"unit_name,omitempty"`
	// 辅助单位名称：辅助单位名称（String，选填）
	AuxUnitName string `json:"aux_unit_name,omitempty"`
	// 辅助箱体积：记录单品按照箱规辅助单位计算出的完整箱规的体积（Decimal(19,4)，选填）
	AuxVolume float64 `json:"aux_volume,omitempty"`
	// 保质期计算方式：保质期计算方式0：按天1：按月默认0（Int，选填）
	ValidityType int `json:"validity_type,omitempty"`
}

type GoodsBatchPushGoodsInfo struct {
	// 货品编号：货品编号（String，必填）
	GoodsNo string `json:"goods_no"`
	// 货品名称：货品名称（String，必填）
	GoodsName string `json:"goods_name"`
	// 分类名称：分类名称,不传或为空则默认为’无’（String，选填）
	ClassName string `json:"class_name,omitempty"`
	// 品牌名称：品牌名称, 不传或为空则默认为’无’（String，选填）
	BrandName string `json:"brand_name,omitempty"`
	// 基本单位名称：基本单位名称, 不传或为空则默认为’无’（String，选填）
	UnitName string `json:"unit_name,omitempty"`
	// 辅助单位名称：辅助单位名称, 不传或为空则默认为’无’（String，选填）
	AuxUnitName string `json:"aux_unit_name,omitempty"`
	// 货品标记名称：货品标记名称, 不传或为空则默认为’无’（String，选填）
	FlagName string `json:"flag_name,omitempty"`
	// 货品类别：默认0, 0：其它1：销售货品2：原材料3：包装物4：周转材料5：虚拟商品6：固定资产8：分装箱（Int，选填）
	GoodsType int `json:"goods_type,omitempty"`
	// 货品简称：货品简称（String，选填）
	ShortName string `json:"short_name,omitempty"`
	// 货品别名：货品别名（String，选填）
	Alias string `json:"alias,omitempty"`
	// 拼音：拼音（String，选填）
	Pinyin string `json:"pinyin,omitempty"`
	// 产地：产地（String，选填）
	Origin string `json:"origin,omitempty"`
	// 货品备注：货品备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 是否自动创建品牌和分类：如果品牌,分类不存在,是否自动创建.不填默认为false（bool，选填）
	AutoCreateBc bool `json:"auto_create_bc,omitempty"`
	// 货品自定义属性1：货品自定义属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 货品自定义属性2：货品自定义属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 货品自定义属性3：货品自定义属性3（String，选填）
	Prop3 string `json:"prop3,omitempty"`
	// 货品自定义属性4：货品自定义属性4（String，选填）
	Prop4 string `json:"prop4,omitempty"`
	// 货品自定义属性5：货品自定义属性5（String，选填）
	Prop5 string `json:"prop5,omitempty"`
	// 货品自定义属性6：货品自定义属性6（String，选填）
	Prop6 string `json:"prop6,omitempty"`
	// 货品自定义属性7：货品自定义属性7（String，选填）
	Prop7 string `json:"prop7,omitempty"`
	// 货品自定义属性8：货品自定义属性8（String，选填）
	Prop8 string `json:"prop8,omitempty"`
	// 货品自定义属性9：货品自定义属性9（String，选填）
	Prop9 string `json:"prop9,omitempty"`
	// 货品自定义属性10：货品自定义属性10（String，选填）
	Prop10 string `json:"prop10,omitempty"`
	// 货品自定义属性11：货品自定义属性11（String，选填）
	Prop11 string `json:"prop11,omitempty"`
	// 货品自定义属性12：货品自定义属性12（String，选填）
	Prop12 string `json:"prop12,omitempty"`
	// 货品自定义属性13：货品自定义属性13（String，选填）
	Prop13 string `json:"prop13,omitempty"`
	// 货品自定义属性14：货品自定义属性14（String，选填）
	Prop14 string `json:"prop14,omitempty"`
	// 货品自定义属性15：货品自定义属性15（String，选填）
	Prop15 string `json:"prop15,omitempty"`
	// 货品自定义属性16：货品自定义属性16（String，选填）
	Prop16 string `json:"prop16,omitempty"`
	// 货品自定义属性17：货品自定义属性17（String，选填）
	Prop17 string `json:"prop17,omitempty"`
	// 货品自定义属性18：货品自定义属性18（String，选填）
	Prop18 string `json:"prop18,omitempty"`
	// 货品自定义属性19：货品自定义属性19（String，选填）
	Prop19 string `json:"prop19,omitempty"`
	// 货品自定义属性20：货品自定义属性20（String，选填）
	Prop20 string `json:"prop20,omitempty"`
	// 单品信息列表：单品信息列表（List<Map<String, Object>>，必填）
	SpecList []*GoodsBatchPushGoodsInfoSpec `json:"spec_list"`
}

type GoodsBatchPushGoodsInfoSpec struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 规格码：规格码（String，选填）
	SpecCode string `json:"spec_code,omitempty"`
	// 条码：条码（String，选填）
	Barcode string `json:"barcode,omitempty"`
	// 规格名称：规格名称（String，选填）
	SpecName string `json:"spec_name,omitempty"`
	// 仓库流程：默认0 （需要的仓库流程相加）2、无需验货 8、需要质检 16、无需拣货32、无需唯一码64、无需自动打印吊牌（Int，选填）
	WmsProcessMask int `json:"wms_process_mask,omitempty"`
	// 货品标签：默认无,可选值:自定义货品标签的名称(参考属性名称编辑页面->货品标签)多个标签使用英文逗号拼接（String，选填）
	GoodsLabel string `json:"goods_label,omitempty"`
	// 启用序列号：默认0,0不启用序列号 1强序列号 2弱序列号（Int，选填）
	SnType int `json:"sn_type,omitempty"`
	// 最低价：最低价（Decimal(19,4)，选填）
	LowestPrice float64 `json:"lowest_price,omitempty"`
	// 零售价：零售价（Decimal(19,4)，选填）
	RetailPrice float64 `json:"retail_price,omitempty"`
	// 批发价：批发价（Decimal(19,4)，选填）
	WholesalePrice float64 `json:"wholesale_price,omitempty"`
	// 会员价：会员价（Decimal(19,4)，选填）
	MemberPrice float64 `json:"member_price,omitempty"`
	// 市场价：市场价（Decimal(19,4)，选填）
	MarketPrice float64 `json:"market_price,omitempty"`
	// 有效期天数：有效期天数（smallint，选填）
	ValidityDays any `json:"validity_days,omitempty"`
	// 有效期计算方式：默认0,0按天，1按月（int，选填）
	ValidityType int `json:"validity_type,omitempty"`
	// 最佳销售天数：最佳销售天数（Int，选填）
	SalesDays int `json:"sales_days,omitempty"`
	// 最佳收货天数：最佳收货天数（Int，选填）
	ReceiveDays int `json:"receive_days,omitempty"`
	// 重量：重量（Decimal(19,4)，选填）
	Weight float64 `json:"weight,omitempty"`
	// 高：高（Decimal(19,4)，选填）
	Height float64 `json:"height,omitempty"`
	// 长：长（Decimal(19,4)，选填）
	Length float64 `json:"length,omitempty"`
	// 宽：宽（Decimal(19,4)，选填）
	Width float64 `json:"width,omitempty"`
	// 拆分：默认0, 0非大件1普通大件2独立大件（不可和小件一起发) 3按箱规拆分 -1非单发件（Int，选填）
	LargeType int `json:"large_type,omitempty"`
	// 自定义价格1：自定义价格1（Decimal(19,4)，选填）
	CustomPrice1 float64 `json:"custom_price1,omitempty"`
	// 自定义价格2：自定义价格2（Decimal(19,4)，选填）
	CustomPrice2 float64 `json:"custom_price2,omitempty"`
	// 允许低于成本：默认0,0:不允许,1 允许（boolean，选填）
	IsLowerCost bool `json:"is_lower_cost,omitempty"`
	// 图片链接：图片链接（String，选填）
	ImgUrl string `json:"img_url,omitempty"`
	// 单品备注：单品备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 销售积分：销售积分（Decimal(19,4)，选填）
	SaleScore float64 `json:"sale_score,omitempty"`
	// 打包积分：打包积分（Decimal(19,4)，选填）
	PackScore float64 `json:"pack_score,omitempty"`
	// 拣货积分：拣货积分（Decimal(19,4)，选填）
	PickScore float64 `json:"pick_score,omitempty"`
	// 分拣积分：分拣积分（Decimal(19,4)，选填）
	SortScore float64 `json:"sort_score,omitempty"`
	// 扫描积分：扫描积分（Decimal(19,4)，选填）
	ScanScore float64 `json:"scan_score,omitempty"`
	// 补货积分：补货积分（Decimal(19,4)，选填）
	SupplyScore float64 `json:"supply_score,omitempty"`
	// 上架积分：上架积分（Decimal(19,4)，选填）
	ShelveScore float64 `json:"shelve_score,omitempty"`
	// 入库积分：入库积分（Decimal(19,4)，选填）
	StockinScore float64 `json:"stockin_score,omitempty"`
	// 质检积分：质检积分（Decimal(19,4)，选填）
	InspectScore float64 `json:"inspect_score,omitempty"`
	// 分装积分：分装积分（Decimal(19,4)，选填）
	PackingScore float64 `json:"packing_score,omitempty"`
	// 操作积分：操作积分（Decimal(19,4)，选填）
	OperateScore float64 `json:"operate_score,omitempty"`
	// 称重积分：称重积分（Decimal(19,4)，选填）
	WeighScore float64 `json:"weigh_score,omitempty"`
	// 发货积分：发货积分（Decimal(19,4)，选填）
	ConsignScore float64 `json:"consign_score,omitempty"`
	// 税务编码：税务编码（String，选填）
	TaxCode string `json:"tax_code,omitempty"`
	// 基本单位名称：基本单位名称（String，选填）
	UnitName string `json:"unit_name,omitempty"`
	// 辅助单位名称：辅助单位名称（String，选填）
	AuxUnitName string `json:"aux_unit_name,omitempty"`
	// 辅助箱体积：记录单品按照箱规辅助单位计算出的完整箱规的体积（Decimal(19,4)，选填）
	AuxVolume float64 `json:"aux_volume,omitempty"`
	// 单品自定义属性1：单品自定义属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 单品自定义属性2：单品自定义属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 单品自定义属性3：单品自定义属性3（String，选填）
	Prop3 string `json:"prop3,omitempty"`
	// 单品自定义属性4：单品自定义属性4（String，选填）
	Prop4 string `json:"prop4,omitempty"`
	// 单品自定义属性7：单品自定义属性7（String，选填）
	Prop7 string `json:"prop7,omitempty"`
	// 单品自定义属性8：单品自定义属性8（String，选填）
	Prop8 string `json:"prop8,omitempty"`
	// 单品自定义属性9：单品自定义属性9（String，选填）
	Prop9 string `json:"prop9,omitempty"`
	// 单品自定义属性10：单品自定义属性10（String，选填）
	Prop10 string `json:"prop10,omitempty"`
	// 单品自定义属性11：单品自定义属性11（String，选填）
	Prop11 string `json:"prop11,omitempty"`
	// 单品自定义属性12：单品自定义属性12（String，选填）
	Prop12 string `json:"prop12,omitempty"`
	// 单品自定义属性13：单品自定义属性13（String，选填）
	Prop13 string `json:"prop13,omitempty"`
	// 单品自定义属性14：单品自定义属性14（String，选填）
	Prop14 string `json:"prop14,omitempty"`
	// 单品自定义属性15：单品自定义属性15（String，选填）
	Prop15 string `json:"prop15,omitempty"`
	// 单品自定义属性16：单品自定义属性16（String，选填）
	Prop16 string `json:"prop16,omitempty"`
	// 单品自定义属性17：单品自定义属性17（String，选填）
	Prop17 string `json:"prop17,omitempty"`
	// 单品自定义属性18：单品自定义属性18（String，选填）
	Prop18 string `json:"prop18,omitempty"`
	// 单品自定义属性19：单品自定义属性19（String，选填）
	Prop19 string `json:"prop19,omitempty"`
	// 单品自定义属性20：单品自定义属性20（String，选填）
	Prop20 string `json:"prop20,omitempty"`
}

type GoodsQueryWithSpecParams struct {
	// 商家编码：商家编码（如果不传时间，则spec_no和goods_no必须传一个）（String，选填）
	SpecNo string `json:"spec_no,omitempty"`
	// 货品编号：货品编号（String，选填）
	GoodsNo string `json:"goods_no,omitempty"`
	// 品牌名称：品牌名称（String，选填）
	BrandName string `json:"brand_name,omitempty"`
	// 分类名称：分类名称（String，选填）
	ClassName string `json:"class_name,omitempty"`
	// 条码：条码（String，选填）
	Barcode string `json:"barcode,omitempty"`
	// 是否隐藏已删除的货品。：0:返回全部;1:隐藏已删除 默认隐藏（boolean，选填）
	HideDeleted bool `json:"hide_deleted,omitempty"`
	// 开始时间：起始修改时间 最大跨度为30天（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束修改时间, 不填默认为当前时间 最大跨度为30天（String，选填）
	EndTime string `json:"end_time,omitempty"`
}

type SuiteSearchParams struct {
	// 商家编码：商家编码（String，选填）
	SpecNo string `json:"spec_no,omitempty"`
	// 货品编号：货品编号（String，选填）
	GoodsNo string `json:"goods_no,omitempty"`
	// 品牌编号：品牌编号（String，选填）
	BrandName string `json:"brand_name,omitempty"`
	// 分类名称：分类名称（String，选填）
	ClassName string `json:"class_name,omitempty"`
	// 条码：条码（String，选填）
	Barcode string `json:"barcode,omitempty"`
	// 组合装商家编码：组合装商家编码（如果不传时间，组合装商家编码必传）（String，选填）
	SuiteNo string `json:"suite_no,omitempty"`
	// 组合装名称：组合装名称（String，选填）
	SuiteName string `json:"suite_name,omitempty"`
	// 是否隐藏已删除的货品：默认隐藏（boolean，选填）
	HideDeleted bool `json:"hide_deleted,omitempty"`
	// 开始时间：起始修改时间（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束修改时间, 不填默认为当前时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
}

type SuiteUpload2Suite struct {
	// 组合装名称：组合装名称（String，必填）
	SuiteName string `json:"suite_name"`
	// 组合装编号：组合装编号（String，必填）
	SuiteNo string `json:"suite_no"`
	// 分类名称：分类名称（String，选填）
	ClassName string `json:"class_name,omitempty"`
	// 品牌名称：品牌名称（String，选填）
	BrandName string `json:"brand_name,omitempty"`
	// 基本单位名称：基本单位名称（String，选填）
	UnitName string `json:"unit_name,omitempty"`
	// 辅助单位名称：辅助单位名称（String，选填）
	AuxUnitName string `json:"aux_unit_name,omitempty"`
	// 简称：简称（String，选填）
	ShortName string `json:"short_name,omitempty"`
	// 条码：条码（String，选填）
	Barcode string `json:"barcode,omitempty"`
	// 重量：重量（Decimal(19,4)，选填）
	Weight float64 `json:"weight,omitempty"`
	// 货品自定义属性1：货品自定义属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 货品自定义属性2：货品自定义属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 货品自定义属性3：货品自定义属性3（String，选填）
	Prop3 string `json:"prop3,omitempty"`
	// 货品自定义属性4：货品自定义属性4（String，选填）
	Prop4 string `json:"prop4,omitempty"`
	// 货品自定义属性5：货品自定义属性5（String，选填）
	Prop5 string `json:"prop5,omitempty"`
	// 货品自定义属性6：货品自定义属性6（String，选填）
	Prop6 string `json:"prop6,omitempty"`
	// 货品自定义属性7：货品自定义属性7（String，选填）
	Prop7 string `json:"prop7,omitempty"`
	// 货品自定义属性8：货品自定义属性8（String，选填）
	Prop8 string `json:"prop8,omitempty"`
	// 货品自定义属性9：货品自定义属性9（String，选填）
	Prop9 string `json:"prop9,omitempty"`
	// 货品自定义属性10：货品自定义属性10（String，选填）
	Prop10 string `json:"prop10,omitempty"`
	// 货品自定义属性11：货品自定义属性11（String，选填）
	Prop11 string `json:"prop11,omitempty"`
	// 货品自定义属性12：货品自定义属性12（String，选填）
	Prop12 string `json:"prop12,omitempty"`
	// 货品自定义属性13：货品自定义属性13（String，选填）
	Prop13 string `json:"prop13,omitempty"`
	// 货品自定义属性14：货品自定义属性14（String，选填）
	Prop14 string `json:"prop14,omitempty"`
	// 货品自定义属性15：货品自定义属性15（String，选填）
	Prop15 string `json:"prop15,omitempty"`
	// 货品自定义属性16：货品自定义属性16（String，选填）
	Prop16 string `json:"prop16,omitempty"`
	// 货品自定义属性17：货品自定义属性17（String，选填）
	Prop17 string `json:"prop17,omitempty"`
	// 货品自定义属性18：货品自定义属性18（String，选填）
	Prop18 string `json:"prop18,omitempty"`
	// 货品自定义属性19：货品自定义属性19（String，选填）
	Prop19 string `json:"prop19,omitempty"`
	// 货品自定义属性20：货品自定义属性20（String，选填）
	Prop20 string `json:"prop20,omitempty"`
	// 零售价：零售价（Decimal(19,4)，选填）
	RetailPrice float64 `json:"retail_price,omitempty"`
	// 批发价：批发价（Decimal(19,4)，选填）
	WholesalePrice float64 `json:"wholesale_price,omitempty"`
	// 会员价：会员价（Decimal(19,4)，选填）
	MemberPrice float64 `json:"member_price,omitempty"`
	// 市场价：市场价（Decimal(19,4)，选填）
	MarketPrice float64 `json:"market_price,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 打印模式：0:组合装明细1:组合装及明细 2: 组合装 默认0（Byte，选填）
	PrintSuiteMode int `json:"print_suite_mode,omitempty"`
	// 货品标签：打印方式为明细时不允许设置标签(1)当不设置标签时，需传入空字符串(2)当传入客户端不存在的货品标签时，原货品标签会重置为空值（String，必填）
	GoodsLabelName string `json:"goods_label_name"`
	// 拆分属性：0: 非大件 1:普通大件 2: 独立大件 默认0（Byte，选填）
	LargeType int `json:"large_type,omitempty"`
}

type SuiteUpload2SuiteDetail struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 是否固定价格：默认false（Boolean，选填）
	IsFixedPrice bool `json:"is_fixed_price,omitempty"`
	// 数量：数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 固定价格：仅is_fixed_price=true 有效. -1: 使用货品档案内单品零售价（Decimal(19,4)，选填）
	FixedPrice float64 `json:"fixed_price,omitempty"`
	// 金额占比：-1: 按照明细金额自动计算比例（Decimal(19,4)，选填）
	Ratio float64 `json:"ratio,omitempty"`
}

type ApiGoodsSearchParams struct {
	// 店铺编号：店铺编号 当与 goods_id 组合查询时可不传时间（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
	// 平台货品ID：平台货品ID 当与 shop_no 组合查询时 可不传时间（String，选填）
	GoodsId string `json:"goods_id,omitempty"`
	// 平台规格ID：平台规格ID 当与 shop_no+goods_id 组合查询时 可不传时间（String，选填）
	SpecId string `json:"spec_id,omitempty"`
	// 开始时间：起始修改时间, 时间格式 YYYY-MM-DD HH:MM:SS（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束修改时间, 时间格式 YYYY-MM-DD HH:MM:SS（String，必填）
	EndTime string `json:"end_time"`
}

type ApiGoodsUploadParam struct {
	// 店铺编号：店铺编号（String，必填）
	ShopNo string `json:"shop_no"`
	// 平台货品明细：平台货品数据（List<Map<String,Object>>，必填）
	GoodsList []*ApiGoodsUploadParamGoods `json:"goods_list"`
}

type ApiGoodsUploadParamGoods struct {
	// 货品ID：平台货品ID, 不传默认为空（String，选填）
	GoodsId string `json:"goods_id,omitempty"`
	// 规格ID：平台规格ID, 不传默认为空（String，选填）
	SpecId string `json:"spec_id,omitempty"`
	// 平台货品编号：平台货品编号, 不传默认为空（String，选填）
	GoodsNo string `json:"goods_no,omitempty"`
	// 平台规格编码：平台规格编码, 不传默认为空（String，选填）
	SpecNo string `json:"spec_no,omitempty"`
	// 状态：0：删除1：在架2：下架不传默认1（Int，选填）
	Status int `json:"status,omitempty"`
	// 货品名称：平台货品名称, 不传默认为空（String，选填）
	GoodsName string `json:"goods_name,omitempty"`
	// 规格名称：平台规格名称, 不传默认为空（String，选填）
	SpecName string `json:"spec_name,omitempty"`
	// 图片url：图片url, 不传默认为空（String，选填）
	PicUrl string `json:"pic_url,omitempty"`
	// 平台售价：平台售价，不传默认为0（Decimal(19,4)，选填）
	Price float64 `json:"price,omitempty"`
	// 库存数量：库存数量，不传默认为0（Decimal(19,4)，选填）
	StockNum float64 `json:"stock_num,omitempty"`
}

type GoodsClassSearchParams struct {
	// 分类名称：分类名称（String，选填）
	ClassName string `json:"class_name,omitempty"`
	// 开始时间：开始时间（最后修改时间）（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束时间（最后修改时间）（String，选填）
	EndTime string `json:"end_time,omitempty"`
}

type GoodsClassUploadParams struct {
	// 父分类名称：默认情况下创建为一级分类（String，选填）
	ParentClassName string `json:"parent_class_name,omitempty"`
	// 分类名称：分类名称（String，必填）
	ClassName string `json:"class_name"`
	// 是否叶子节点：true:不允许有子节点，创建为分类false:允许有子节点，创建为分组（boolean，必填）
	IsLeaf bool `json:"is_leaf"`
}

type GoodsBrandSearchParams struct {
	// 开始时间：开始时间（最后修改时间）（Date，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束时间（最后修改时间）（Date，选填）
	EndTime string `json:"end_time,omitempty"`
	// 品牌编号：品牌编号（String，选填）
	BrandNo string `json:"brand_no,omitempty"`
	// 品牌名称：品牌名称（String，选填）
	BrandName string `json:"brand_name,omitempty"`
}

type GoodsBrandUploadParams struct {
	// 品牌编码：brand_no不为空时默认走更新逻辑如果库里不存在对应的brand_no则为新建（String，选填）
	BrandNo string `json:"brand_no,omitempty"`
	// 品牌名称：品牌名称（String，必填）
	BrandName string `json:"brand_name"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 是否停用：0：否1：是默认0（Int，选填）
	IsDisabled int `json:"is_disabled,omitempty"`
}

type CategorySearchParams struct {
	// 店铺编号：店铺编号（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
	// 开始时间：开始时间（最后修改时间）（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间（最后修改时间）（String，必填）
	EndTime string `json:"end_time"`
}

type BarcodeUploadBarcodeInfo struct {
	// 商家编码：单品/组合装商家编码（String，必填）
	MerchantNo string `json:"merchant_no"`
	// 条码：条码（String，选填）
	Barcode string `json:"barcode,omitempty"`
	// 操作类型：1：新增2：更新默认1（Int，选填）
	Type int `json:"type,omitempty"`
	// 数量：默认1（Int，选填）
	Num int `json:"num,omitempty"`
	// 原条码：原条码，仅更新操作有效（String，选填）
	OldBarcode string `json:"old_barcode,omitempty"`
}

type BomUploadParam struct {
	// 物料清单名称：物料清单名称（String，必填）
	BomName string `json:"bom_name"`
	// 生产费用：生产费用（Decimal(19,4)，选填）
	Fee float64 `json:"fee,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 货品列表：货品列表（List<Map<String,Object>>，必填）
	DetailList []*BomUploadParamDetail `json:"detail_list"`
}

type BomUploadParamDetail struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 数量：数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 是否成品：默认false（bool，选填）
	IsProduct bool `json:"is_product,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
}

type BomSearchParams struct {
	// 开始时间：物料清单最后修改时间（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：物料清单最后修改时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 物料清单编号：物料清单编号为空时，时间条件必填（String，选填）
	BomNo string `json:"bom_no,omitempty"`
	// 是否展示已停用清单：是：true否：false默认false（boolean，选填）
	ShowDisabled bool `json:"show_disabled,omitempty"`
	// 原料商家编码：原料商家编码（String，选填）
	MaterialSpecNo string `json:"material_spec_no,omitempty"`
	// 成品商家编码：成品商家编码（String，选填）
	ProductSpecNo string `json:"product_spec_no,omitempty"`
}

type ProcessUploadParam struct {
	// 出库仓库编号：出库仓库编号（String，必填）
	OutWarehouseNo string `json:"out_warehouse_no"`
	// 入库仓库编号：入库仓库编号（String，必填）
	InWarehouseNo string `json:"in_warehouse_no"`
	// 生产员昵称：生产员昵称（String，必填）
	OperatorName string `json:"operator_name"`
	// 生产商编号：生产商编号（String，必填）
	ProducerNo string `json:"producer_no"`
	// 生产次数：生产次数（Int，必填）
	ProcessCount int `json:"process_count"`
	// 标记名称：标记名称（String，选填）
	FlagName string `json:"flag_name,omitempty"`
	// 物料清单名称：物料清单名称（String，选填）
	BomName string `json:"bom_name,omitempty"`
	// 生产费用合计：生产费用合计（Decimal(19,4)，选填）
	TotalFee float64 `json:"total_fee,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 是否审核：是否审核，不传默认false（boolean，选填）
	IsCheck bool `json:"is_check,omitempty"`
	// 生产方式：0：分步生产1：快速生产默认0（Int，选填）
	Type int `json:"type,omitempty"`
	// 加工类型：加工类型，仅快速生产支持，内仓只能是0， 0：无1：仓内组合加工2：仓内组合拆分，（Int，选填）
	ServiceType int `json:"service_type,omitempty"`
	// 货品列表：货品列表（List<Map<String,Object>>，必填）
	DetailList []*ProcessUploadParamDetail `json:"detail_list"`
}

type ProcessUploadParamDetail struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 数量：数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 是否成品：默认false（bool，选填）
	IsProduct bool `json:"is_product,omitempty"`
	// 货位编号：货位编号（String，选填）
	PositionNo string `json:"position_no,omitempty"`
	// 批次号：批次号（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 生产日期：生产日期，不传默认当前时间（String，选填）
	ProductionDate string `json:"production_date,omitempty"`
	// 备注：商家编码是成品传输成品备注，是原材料传输原料备注（String，选填）
	Remark string `json:"remark,omitempty"`
}

type ProcessSearchParams struct {
	// 开始时间：yyyy-MM-dd HH:mm:ss格式, 最后修改时间。当不使用其它条件时必须使用时间条件（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束时间，上同开始时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 出库仓库编号：出库仓库编号（String，选填）
	OutWarehouseNo string `json:"out_warehouse_no,omitempty"`
	// 入库仓库编号：入库仓库编号（String，选填）
	InWarehouseNo string `json:"in_warehouse_no,omitempty"`
	// 当前状态：当前状态10:已取消;20:编辑中;30:待审核;40:待领料;45:已领料;50:执行中;60:生产结束;70:已完成（Int，选填）
	Status int `json:"status,omitempty"`
	// 生产单号：生产单号（String，选填）
	ProcessNo string `json:"process_no,omitempty"`
}

type SettleProcessSearchParams struct {
	// 生产单号：生产单号（String，选填）
	ProcessNo string `json:"process_no,omitempty"`
	// 结算单号：结算单号（String，选填）
	SettleNo string `json:"settle_no,omitempty"`
	// 生产商编码：生产商编码（String，选填）
	ProducerNo string `json:"producer_no,omitempty"`
	// 开始时间：开始时间（生产结算单的创建时间）（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束时间（生产结算单的创建时间）（String，选填）
	EndTime string `json:"end_time,omitempty"`
}

// Push 货品推送 - ①推送货品资料给ERP ②更新ERP货品档案资料
// （1）该接口是pushGoods的替代接口. 接口以goods_no和spec_no来匹配货品和单品, 所以如果接口传入已经存在的goods_no或spec_no的时候对应的操作是修改操作。（2）spu维度一次只能推一条，一个货品可以推送多条明细
//
// 对应接口：goods.Goods.push
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.Goods.push
func (s *GoodsService) Push(ctx context.Context, goodsInfo *GoodsPushGoodsInfo, specInfoList []*GoodsPushSpecInfo) (*Response, error) {
	return s.client.Call(ctx, "goods.Goods.push", goodsInfo, specInfoList)
}

// Push2 货品推送2 - ①推送货品资料给ERP ②更新ERP货品档案资料
// （1）接口以goods_no和spec_no来匹配货品和单品, 所以如果接口传入已经存在的goods_no或spec_no的时候对应的操作是修改操作。（2）spu维度一次只能推一条，一个货品可以推送多条明细
//
// 对应接口：goods.Goods.push2
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.Goods.push2
func (s *GoodsService) Push2(ctx context.Context, goodsInfo *GoodsPush2GoodsInfo, specInfoList []*GoodsPush2SpecInfo) (*Response, error) {
	return s.client.Call(ctx, "goods.Goods.push2", goodsInfo, specInfoList)
}

// BatchPush 货品批量推送 - ①批量推送货品资料给ERP ②更新ERP货品档案资料
// spu维度一次不超过50条，一个goodsInfo下sku维度一次不超过500条
//
// 对应接口：goods.Goods.batchPush
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.Goods.batchPush
func (s *GoodsService) BatchPush(ctx context.Context, goodsInfo []*GoodsBatchPushGoodsInfo) (*Response, error) {
	return s.client.Call(ctx, "goods.Goods.batchPush", goodsInfo)
}

// QueryWithSpec 货品档案查询 - 获取ERP的货品档案资料
// 支持
// start_time和end_time最大跨度为30天
// 开始时间和结束时间是 货品 或 单品 最后修改时间的范围【权限校验】：品牌权限（旺店通客户端-采购-采购权限管理界面控制品牌权限）
//
// 对应接口：goods.Goods.queryWithSpec
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.Goods.queryWithSpec
func (s *GoodsService) QueryWithSpec(ctx context.Context, params *GoodsQueryWithSpecParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "goods.Goods.queryWithSpec", pager, params)
}

// Search 组合装查询 - 获取ERP中组合装界面的组合装资料
// 支持
// start_time和end_time最大跨度为30天
// 1、【权限校验】：品牌权限（旺店通客户端-采购-采购权限管理界面控制品牌权限）2、开始时间和结束时间是 组合装 或 组合装明细 最后修改时间的范围3、组合装商家编码和时间同时传的情况下，按照商家编码查询，时间不生效
//
// 对应接口：goods.Suite.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.Suite.search
func (s *SuiteService) Search(ctx context.Context, params *SuiteSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "goods.Suite.search", pager, params)
}

// Upload2 组合装创建/更新 - 推送组合装信息
//
// 组合装更新的时候，需要保证suite_no不变，组合组信息，组合装明细行全量更新。并非只传更新的部分货品信息。（如原来明细是三个货品，更新时也需要完整传输三个货品的信息，如果只传两个货品，第三个货品会被删除）. 其他检验逻辑和客户端逻辑保持一致。
//
// 对应接口：goods.Suite.upload2
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.Suite.upload2
func (s *SuiteService) Upload2(ctx context.Context, suite *SuiteUpload2Suite, suiteDetailList []*SuiteUpload2SuiteDetail) (*Response, error) {
	return s.client.Call(ctx, "goods.Suite.upload2", suite, suiteDetailList)
}

// Search 平台货品查询 - 获取ERP的平台货品资料
// 支持
// start_time和end_time最大跨度为30天
// 【权限校验】：店铺权限开始时间和结束时间是平台货品数据最后修改时间的范围为了达到保护用户隐私数据安全的目的，本接口不返回淘系、拼多多及系统供销平台货品数据，淘系及系统供销平台相关规则点击这里，淘系及系统供销平台数据获取办法点击这里，拼多多请自行对接平台获取。
//
// 对应接口：goods.ApiGoods.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.ApiGoods.search
func (s *ApiGoodsService) Search(ctx context.Context, params *ApiGoodsSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "goods.ApiGoods.search", pager, params)
}

// Upload 平台货品推送 - 推送平台货品信息给ERP
//
// 【权限校验】：店铺权限 (1)仅支持创建自有平台的平台货品（2）接口只创建平台货品，不会关联系统货品，匹配方式为自动匹配（3）平台货品以店铺+goods_id+spec_id组成唯一，如果已存在数据则会覆盖
//
// 对应接口：goods.ApiGoods.upload
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.ApiGoods.upload
func (s *ApiGoodsService) Upload(ctx context.Context, param *ApiGoodsUploadParam) (*Response, error) {
	return s.client.Call(ctx, "goods.ApiGoods.upload", param)
}

// Search 货品分类查询 - 获取ERP的货品分类信息
//
// 对应接口：goods.GoodsClass.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.GoodsClass.search
func (s *GoodsClassService) Search(ctx context.Context, params *GoodsClassSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "goods.GoodsClass.search", pager, params)
}

// Upload 新建分类 - 新建分类
//
// 对应接口：goods.GoodsClass.upload
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.GoodsClass.upload
func (s *GoodsClassService) Upload(ctx context.Context, params *GoodsClassUploadParams) (*Response, error) {
	return s.client.Call(ctx, "goods.GoodsClass.upload", params)
}

// Search 品牌查询 - 获取ERP的货品品牌信息
// 支持
//
// 对应接口：goods.GoodsBrand.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.GoodsBrand.search
func (s *GoodsBrandService) Search(ctx context.Context, params *GoodsBrandSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "goods.GoodsBrand.search", pager, params)
}

// Upload 货品品牌新建/更新 - 新建/更新品牌信息
//
// 对应接口：goods.GoodsBrand.upload
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.GoodsBrand.upload
func (s *GoodsBrandService) Upload(ctx context.Context, params []*GoodsBrandUploadParams) (*Response, error) {
	return s.client.Call(ctx, "goods.GoodsBrand.upload", params)
}

// Search 平台类目查询 - 获取ERP平台类目数据
//
// 起止时间跨度不超过30天
// 【权限校验】：店铺权限1.为了达到保护用户隐私数据安全的目的，本接口不返回淘系及系统供销平台货品数据，相关平台规则点击这里，淘系及系统供销平台数据获取办法点击这里。2.本接口不返回类目下的平台货品信息，需要到平台货品查询接口进行类目关联
//
// 对应接口：goods.Category.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.Category.search
func (s *CategoryService) Search(ctx context.Context, params *CategorySearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "goods.Category.search", pager, params)
}

// Upload 条码上传 - 新建或更新条码
//
// 对应接口：goods.Barcode.upload
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=goods.Barcode.upload
func (s *BarcodeService) Upload(ctx context.Context, barcodeInfoList []*BarcodeUploadBarcodeInfo) (*Response, error) {
	return s.client.Call(ctx, "goods.Barcode.upload", barcodeInfoList)
}

// Upload 物料清单推送 - 推送物料清单给ERP
//
// 对应接口：process.Bom.upload
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=process.Bom.upload
func (s *BomService) Upload(ctx context.Context, param *BomUploadParam) (*Response, error) {
	return s.client.Call(ctx, "process.Bom.upload", param)
}

// Search 物料清单查询 - 获取ERP物料清单数据
// 支持
// start_time与end_time起止时间跨度不超过30天
//
// 对应接口：process.Bom.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=process.Bom.search
func (s *BomService) Search(ctx context.Context, params *BomSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "process.Bom.search", pager, params)
}

// Upload 生产单推送 - 推送生产单给ERP
//
// 【权限校验】：仓库权限
//
// 对应接口：process.Process.upload
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=process.Process.upload
func (s *ProcessService) Upload(ctx context.Context, param *ProcessUploadParam) (*Response, error) {
	return s.client.Call(ctx, "process.Process.upload", param)
}

// Search 生产单查询 - 获取ERP生产单信息
// 支持
// start_time与end_time 起止时间区间不能超过30天
//
// 对应接口：process.Process.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=process.Process.search
func (s *ProcessService) Search(ctx context.Context, params *ProcessSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "process.Process.search", pager, params)
}

// Search 生产结算单查询 - 获取ERP生产结算单信息
//
// 对应接口：finance.settle.process.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.settle.process.search
func (s *SettleProcessService) Search(ctx context.Context, params *SettleProcessSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "finance.settle.process.search", pager, params)
}
