// Code generated by scripts/gen_sdk.py from 旺店通旗舰版 API 文档; DO NOT EDIT.
// 重新生成：python scripts/gen_sdk.py

package wdt

import "context"

// ProviderGoodsService 提供 purchase.ProviderGoods.* 接口的封装。
type ProviderGoodsService struct{ client *Client }

// PurchaseOrderService 提供 purchase.PurchaseOrder.* 接口的封装。
type PurchaseOrderService struct{ client *Client }

// PurchaseReturnService 提供 purchase.PurchaseReturn.* 接口的封装。
type PurchaseReturnService struct{ client *Client }

// PurchaseApplyService 提供 purchase.PurchaseApply.* 接口的封装。
type PurchaseApplyService struct{ client *Client }

// StockInPreOrderService 提供 purchase.StockInPreOrder.* 接口的封装。
type StockInPreOrderService struct{ client *Client }

// StockinPurchaseService 提供 wms.stockin.Purchase.* 接口的封装。
type StockinPurchaseService struct{ client *Client }

// StockoutPurchaseReturnService 提供 wms.stockout.PurchaseReturn.* 接口的封装。
type StockoutPurchaseReturnService struct{ client *Client }

// SettlePurchaseService 提供 finance.settle.Purchase.* 接口的封装。
type SettlePurchaseService struct{ client *Client }

// SettlePurchaseReturnService 提供 finance.settle.PurchaseReturn.* 接口的封装。
type SettlePurchaseReturnService struct{ client *Client }

type ProviderGoodsQueryDetailParams struct {
	// 供应商编号：供应商编号（String，选填）
	ProviderNo string `json:"provider_no,omitempty"`
	// 货品编号：货品编号（String，选填）
	GoodsNo string `json:"goods_no,omitempty"`
	// 商家编码：商家编码（String，选填）
	SpecNo string `json:"spec_no,omitempty"`
	// 供应商货号：供应商货号（String，选填）
	ProviderGoodsNo string `json:"provider_goods_no,omitempty"`
	// 货品名称：货品名称（String，选填）
	GoodsName string `json:"goods_name,omitempty"`
	// 条码：条码（String，选填）
	Barcode string `json:"barcode,omitempty"`
}

type ProviderGoodsUploadPurchaseProviderGoods struct {
	// 供应商编号：供应商编号（String，必填）
	ProviderNo string `json:"provider_no"`
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 最小采购量：默认1（Decimal(19,4)，选填）
	MinPurchaseNum float64 `json:"min_purchase_num,omitempty"`
	// 采购单位：默认无，传入的采购单位必须和基本单位(单品无基本单位则取货品的基本单位)匹配（String，选填）
	PurchaseUnitName string `json:"purchase_unit_name,omitempty"`
	// 折扣率：折扣字段，默认值为1，1代表原价，无折扣；假设需要折扣为一折时，可将字段值传为0.1，同理，折扣为5折时，传值0.5；折扣为八折时，传值0.8，以此类推（Decimal(19,4)，选填）
	Discount float64 `json:"discount,omitempty"`
	// 供应商货号：默认空串（String，选填）
	ProviderGoodsNo string `json:"provider_goods_no,omitempty"`
	// 采购价：默认0（Decimal(19,4)，选填）
	Price float64 `json:"price,omitempty"`
	// 最低采购价：默认0（Decimal(19,4)，选填）
	LowestPrice float64 `json:"lowest_price,omitempty"`
	// 采购周期：默认0（Int，选填）
	PurchaseCycleDay int `json:"purchase_cycle_day,omitempty"`
	// 税率：默认0（Decimal(19,4)，选填）
	TaxRate float64 `json:"tax_rate,omitempty"`
	// 是否主供应商：默认true（boolean，选填）
	IsMaster bool `json:"is_master,omitempty"`
	// 备注：默认空（String，选填）
	Remark string `json:"remark,omitempty"`
}

type PurchaseOrderQueryWithDetailParams struct {
	// 采购单号：采购单号（String，选填）
	PurchaseNo string `json:"purchase_no,omitempty"`
	// 供应商编号：供应商编号（String，选填）
	ProviderNo string `json:"provider_no,omitempty"`
	// 预计入库仓编号：预计入库仓（String，选填）
	ExpectWarehouseNo string `json:"expect_warehouse_no,omitempty"`
	// 收货仓编号：收货仓（String，选填）
	ReceiveWarehouseNo string `json:"receive_warehouse_no,omitempty"`
	// 开始时间：采购单修改时间（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：采购单修改时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 入库状态：入库状态,0 未入库 1部分入库 2已入库 3停止入库 4超量入库 5部分-超量入库（Int，选填）
	StockinStatus int `json:"stockin_status,omitempty"`
	// 采购单状态：10 已取消20 编辑中30 待审核35 待财审40 已审核50 部分到货60 已到货70 待结算80 部分结算90 已完成多个状态间使用英文逗号隔开（String，选填）
	Status string `json:"status,omitempty"`
	// 模糊查询：默认false,业务单号进行模糊查询匹配，匹配数量大于1条时会报错（boolean，选填）
	FuzzyQuery bool `json:"fuzzy_query,omitempty"`
}

type PurchaseOrderCreateOrderParams struct {
	// 采购单编号：采购单编号（String，选填）
	PurchaseNo string `json:"purchase_no,omitempty"`
	// 供应商编号：供应商编号（String，必填）
	ProviderNo string `json:"provider_no"`
	// 收货仓编号：收货仓编号（不⽀持分销委外仓，开启系统配置 路径：设置--系统设置--采购设置--采购协同--采购入库支持使用采购预约单入库后，⽀持传⼊多个平台仓编号）（String，必填）
	ReceiveWarehouseNos string `json:"receive_warehouse_nos"`
	// 预计入库仓库编号：预计入库仓库编号（不支持分销委外仓）（String，必填）
	ExpectWarehouseNo string `json:"expect_warehouse_no"`
	// 采购员：采购员（员工页面对应"昵称"字段，员工的"工种"需要有"采购员"）（String，必填）
	PurchaserName string `json:"purchaser_name"`
	// 是否要审核：审核：true不审核：false不传默认为false（bool，选填）
	IsCheck bool `json:"is_check,omitempty"`
	// 引用的采购申请单编号：采购申请单编号,使用英文逗号隔开（String，选填）
	ApplyNos string `json:"apply_nos,omitempty"`
	// 收货地址：收货地址（String，选填）
	ReceiveAddress string `json:"receive_address,omitempty"`
	// 联系人：联系人（String，选填）
	Contact string `json:"contact,omitempty"`
	// 电话：电话（String，选填）
	Telno string `json:"telno,omitempty"`
	// 标记名称：标记名称（String，选填）
	FlagName string `json:"flag_name,omitempty"`
	// 预计到货时间：预计到货时间，例如：2021-07-10 10:35:001. 若系统不启用【采购开单时自动完善期望到货时间】配置，则采用接口传递的时间2. 若系统启用【采购开单时自动完善期望到货时间】配置： - 供应商未设置或设置到货天数为0，仍使用接口传递的时间 - 供应商设置了到货天数，以单据创建时间加到货天数来计算（String，选填）
	ExpectTime string `json:"expect_time,omitempty"`
	// 创建时间：不传或为空,则为当前时间，例如：2021-07-10 10:30:01（String，选填）
	Created string `json:"created,omitempty"`
	// 付款方式：1:现付 2:到付 3:挂账（Int，选填）
	PayType int `json:"pay_type,omitempty"`
	// 运费支付方式：0 无 1 现付 2 到付 3 包邮（Int，选填）
	PostfeePayType int `json:"postfee_pay_type,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 邮费：邮费（Decimal(19,4)，选填）
	PostFee float64 `json:"post_fee,omitempty"`
	// 其他费用：其他费用（Decimal(19,4)，选填）
	OtherFee float64 `json:"other_fee,omitempty"`
	// 物流公司编号：ERP内维护的采购业务类型的物流公司编号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 采购单自定义属性1：采购单自定义属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 采购单自定义属性2：采购单自定义属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 采购单自定义属性3：采购单自定义属性3（String，选填）
	Prop3 string `json:"prop3,omitempty"`
	// 采购单自定义属性4：采购单自定义属性4（String，选填）
	Prop4 string `json:"prop4,omitempty"`
	// 采购单详情：采购单详情（List<Map<String, Object>>，选填）
	PurchaseDetails []*PurchaseOrderCreateOrderParamsPurchaseDetails `json:"purchase_details,omitempty"`
}

type PurchaseOrderCreateOrderParamsPurchaseDetails struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 采购数量：采购数量（Int，必填）
	Num int `json:"num"`
	// 采购单位：采购单位（对应辅助单位）（String，选填）
	PurchaseUnitName string `json:"purchase_unit_name,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 自定义属性1：自定义属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 自定义属性2：自定义属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 自定义属性3：自定义属性3（String，选填）
	Prop3 string `json:"prop3,omitempty"`
	// 自定义属性4：自定义属性4（String，选填）
	Prop4 string `json:"prop4,omitempty"`
	// 税前单价：税前单价（当接口账户没有采购价字段权限时，price推送值无效，客户端税前单价字段按照供应商货品页面维护的采购价进行引用）（Decimal(19,4)，选填）
	Price float64 `json:"price,omitempty"`
	// 税后单价：税后单价（1、需系统配置【采购、采购退货-开单&结算价格计算方式】为【已知税后单价&税率求税前折后单价】时有效 2、当接口账户没有采购价字段权限时，tax_price推送值无效）（Decimal(19,4)，选填）
	TaxPrice float64 `json:"tax_price,omitempty"`
	// 折扣：折扣字段，默认值为1，1代表原价，无折扣；假设需要折扣为一折时，可将字段值传为0.1，同理，折扣为5折时，传值0.5；折扣为八折时，传值0.8，以此类推（Decimal(19,4)，选填）
	Discount float64 `json:"discount,omitempty"`
	// 税率：税率（当接口账户没有采购价字段权限时，tax_rate推送值无效）（Decimal(19,4)，选填）
	TaxRate float64 `json:"tax_rate,omitempty"`
	// 批次号：批次号（如需使用，需要单独开通配置，开启配置的情况下不允许超量入库，开启配置情况下支持创建不存在的批次）（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 有效期：有效期（如需使用，需要单独开通配置，开启配置的情况下不允许超量入库）（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// 单品预计到货时间：单品预计到货时间（String，选填）
	SkuArriveDate string `json:"sku_arrive_date,omitempty"`
}

type PurchaseOrderCancelByTypeParams struct {
	// 采购单操作类型：0：采购单取消1：采购单停止等待2：wms停止等待（Int，必填）
	OperateType int `json:"operate_type"`
	// 采购单批量列表节点：采购单号（List<String>，必填）
	PurchaseNoList []string `json:"purchase_no_list"`
	// 采购单是否允许已审核的单子取消：0：待审核、已审核单据无法取消1：待审核、已审核单据先进行反审核、反编辑再取消默认0（Int，选填）
	AllowCancelCheckedOrder int `json:"allow_cancel_checked_order,omitempty"`
}

type PurchaseOrderUpdatePurchaseInfoParams struct {
	// 采购单号：采购单号（String，必填）
	PurchaseNo string `json:"purchase_no"`
	// 标记名称：标记名称必须是采购单所属标记当传入无时，清除采购单标记（String，必填）
	FlagName string `json:"flag_name"`
}

type PurchaseReturnQueryWithDetailParams struct {
	// 供应商编号：供应商编号（String，选填）
	ProviderNo string `json:"provider_no,omitempty"`
	// 采购退货单号：采购退货单号（String，选填）
	ReturnNo string `json:"return_no,omitempty"`
	// 采购退货单状态：10 已取消,20 编辑中,30 待审核,40 已审核,60 已完成（Int，选填）
	Status int `json:"status,omitempty"`
	// 开始时间：修改时间（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：修改时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 模糊查询：默认false，业务单号进行模糊查询匹配，匹配数量大于1条时会报错（boolean，选填）
	FuzzyQuery bool `json:"fuzzy_query,omitempty"`
}

type PurchaseReturnCreateOrderOrderInfo struct {
	// 外部单号：外部单号（创建成功后作为系统退货单号）（String，必填）
	OuterNo string `json:"outer_no"`
	// 仓库编码：仓库编码（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 供应商编号：供应商编号（String，必填）
	ProviderNo string `json:"provider_no"`
	// 物流公司编号：ERP内维护的采购业务类型的物流公司编号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 邮费：邮费（Decimal(19,4)，选填）
	PostFee float64 `json:"post_fee,omitempty"`
	// 其他费用：其他费用（Decimal(19,4)，选填）
	OtherFee float64 `json:"other_fee,omitempty"`
	// 联系人：联系人（若未传该参数，使用供应商默认的联系人）（String，选填）
	Contact string `json:"contact,omitempty"`
	// 联系电话：联系电话（若未传该参数，使用供应商默认的电话）（String，选填）
	Telno string `json:"telno,omitempty"`
	// 收件地址：收件地址（当省份、城市、区域、地址字段皆为空时，默认使用供应商的省市区及地址信息）（String，选填）
	ReceiveAddress string `json:"receive_address,omitempty"`
	// 省：省编码，可以查看城市代码表，（当省份、城市、区域、地址字段皆为空时，默认使用供应商的省市区及地址信息）（String，选填）
	ReceiveProvince string `json:"receive_province,omitempty"`
	// 市：市编码，可以查看城市代码表（当省份、城市、区域、地址字段皆为空时，默认使用供应商的省市区及地址信息）（String，选填）
	ReceiveCity string `json:"receive_city,omitempty"`
	// 区：区编码，可以查看城市代码表（当省份、城市、区域、地址字段皆为空时，默认使用供应商的省市区及地址信息）（String，选填）
	ReceiveDistrict string `json:"receive_district,omitempty"`
	// 自定义属性1：自定义属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 自定义属性2：自定义属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 引用的采购单号：引用的采购单号，采购单状态要大于已审核（String[]，选填）
	RefPurchaseNos []string `json:"ref_purchase_nos,omitempty"`
	// 审核失败是否取消单据：0：不取消1：审核失败后取消默认0（Int，选填）
	CheckFailCancel int `json:"check_fail_cancel,omitempty"`
	// 是否强制校验地址：0否 （默认值）1是 （没传省市区编码， 按照address解析编码， 解析失败会报错）（Int，选填）
	ForceCheckAddress int `json:"force_check_address,omitempty"`
}

type PurchaseReturnCreateOrderDetail struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 退货数量：退货数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 折扣：折扣字段，默认值为1，1代表原价，无折扣；假设需要折扣为一折时，可将字段值传为0.1，同理，折扣为5折时，传值0.5；折扣为八折时，传值0.8，以此类推（Decimal(19,4)，选填）
	Discount float64 `json:"discount,omitempty"`
	// 税率：税率，不传默认值0（Decimal(19,4)，选填）
	TaxRate float64 `json:"tax_rate,omitempty"`
	// 单价：单价，不传为默认值0（Decimal(19,4)，选填）
	Price float64 `json:"price,omitempty"`
	// 基本单位：退货单位（辅助单位）（String，选填）
	UnitName string `json:"unit_name,omitempty"`
	// 是否残次品：是否残次品true:残次品false:正品（boolean，选填）
	Defect bool `json:"defect,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 批次号：批次号（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 有效期：有效期：样例:2020-04-20 00:00:00（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// 税后金额：税后金额（Decimal(19,4)，选填）
	TaxPrice float64 `json:"tax_price,omitempty"`
	// 采购退货明细自定义属性1：采购退货明细自定义属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 采购退货明细自定义属性2：采购退货明细自定义属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
}

type PurchaseApplyUploadParams struct {
	// 采购申请单明细：采购申请单明细（List<Map<String, Object>>，必填）
	DetailList []*PurchaseApplyUploadParamsDetail `json:"detail_list"`
	// 申请仓库编号：申请仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 期望到货时间：期望到货时间（String，选填）
	ExpectedTime string `json:"expected_time,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 采购申请单号：采购申请单号（String，选填）
	PurchaseApplyNo string `json:"purchase_apply_no,omitempty"`
	// 是否提交：是否提交申请单 true:提交后状态是 待引用 false:受【 开启采购申请量确认流程 】配置影响，开启配置 状态是待确认，关闭配置，状态是编辑中默认true（bool，选填）
	IsSubmit bool `json:"is_submit,omitempty"`
}

type PurchaseApplyUploadParamsDetail struct {
	// 商家编码：单品商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 数量：数量（Int，必填）
	Num int `json:"num"`
	// 供应商编号：供应商编号如果每条明细中的供应商相同，那么该供应商就是申请单的供应商，否则该申请单没有供应商（String，选填）
	ProviderNo string `json:"provider_no,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
}

type PurchaseApplySearchParams struct {
	// 开始时间：开始时间，格式: yyyy-MM-dd HH:mm:ss（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束时间，格式: yyyy-MM-dd HH:mm:ss（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 采购申请单号：采购申请单号 V1.5.1.0版本以上支持（String，选填）
	PurchaseApplyNo string `json:"purchase_apply_no,omitempty"`
}

type StockInPreOrderSearchParams struct {
	// 开始时间：最后修改时间 不传入单号的情况下必须传入时间条件, 时间范围最大7天（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：最后修改时间 不传入单号的情况下必须传入时间条件, 时间范围最大7天（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 预约单单号：预约单单号（String，选填）
	PreOrderNo string `json:"pre_order_no,omitempty"`
}

type StockinPurchaseUploadStockinOrder struct {
	// 采购单号：采购单号（String，必填）
	PurchaseNo string `json:"purchase_no"`
	// 仓库编号：仓库编号（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 物流编码：系统内自定义物流的编码（String，选填）
	LogisticsCode string `json:"logistics_code,omitempty"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 创建模式：默认00：编辑中1：已提交/待审核2：已完成（Int，选填）
	CreateMode int `json:"create_mode,omitempty"`
	// 入库预约单号：传该字段时 可以不传purchase_no、warehouse_no（String，选填）
	PreOrderNo string `json:"pre_order_no,omitempty"`
}

type StockinPurchaseUploadStockinDetail struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 数量：数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 是否残次品：默认为非残次品（boolean，选填）
	Defect bool `json:"defect,omitempty"`
	// 采购单位：（辅助单位）默认为”无”（String，选填）
	UnitName string `json:"unit_name,omitempty"`
	// 批次号：批次号，如采购入库单内批次与采购单内批次不一致，单据推送无法成功，但批次依然自动建立（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 有效期：有效期（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// 货位编号：货位编号（String，选填）
	PositionNo string `json:"position_no,omitempty"`
	// sn码：sn码，用英文逗号分隔（1.6.0.9版本及以上支持强序列号产品 ，1.6.1.1版本及以支持弱序列号产品 create_mode=2 直接推送已完成状态的入库单 ）（String，选填）
	SnStrings string `json:"sn_strings,omitempty"`
	// 生产日期：生产日期（String，选填）
	ProductionDate string `json:"production_date,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 序列号信息：序列号和辅助序列号之间的对应关系,有辅助序列号的情况下需要传该字段（List<SnInfo>，选填）
	SnInfos []*StockinPurchaseUploadStockinDetailSn `json:"sn_infos,omitempty"`
}

type StockinPurchaseUploadStockinDetailSn struct {
	// 序列号：序列号（String，选填）
	Sn string `json:"sn,omitempty"`
	// 辅助序列号：辅助序列号（String，选填）
	SecondSn string `json:"second_sn,omitempty"`
}

type StockinPurchaseQueryWithDetailParams struct {
	// 开始时间：入库单修改时间, yyyy-MM-dd HH:mm:ss格式（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：入库单修改时间，结束时间（String，必填）
	EndTime string `json:"end_time"`
	// 入库单状态：英文逗号拼接的状态值:10=已取消；20=编辑中；30=待审核；37=待质检；40=质检确认；80=已完成（String，选填）
	Status string `json:"status,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 入库单号：入库单号（String，选填）
	StockinNo string `json:"stockin_no,omitempty"`
	// 采购单号：采购单号（String，选填）
	PurchaseNo string `json:"purchase_no,omitempty"`
}

type StockinPurchaseQuickCreateByApiOrderInfo struct {
	// 仓库编码：ERP 内部仓库编码。系统会校验当前调用账号的仓库权限。（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 供应商编码：供应商编码。供应商必须存在、未停用且未删除。（String，必填）
	ProviderNo string `json:"provider_no"`
	// 采购员姓名：采购员姓名，系统按员工姓名匹配。purchaser_no同时传时优先使用 purchaser_name。（String，选填）
	PurchaserName string `json:"purchaser_name,omitempty"`
	// 采购员编号：采购员员工编号。仅在 purchaser_name 为空时使用（String，选填）
	PurchaserNo string `json:"purchaser_no,omitempty"`
	// 操作类型：0：保存；1：提交；2：提交并审核。默认值为 0。（Integer，选填）
	OperType int `json:"oper_type,omitempty"`
	// 物流公司编码：系统物流公司编码。物流公司必须存在且为采购类型。（String，选填）
	LogisticsCode string `json:"logistics_code,omitempty"`
	// 物流单号：采购入库物流单号，最长 40 个字符。（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 联系人：联系人（String，选填）
	Contact string `json:"contact,omitempty"`
	// 联系电话：联系电话（String，选填）
	Telno string `json:"telno,omitempty"`
	// 收货地址：收货地址（String，选填）
	ReceiveAddress string `json:"receive_address,omitempty"`
	// 其它金额：默认值为 0，必须为非负数。（Decimal，选填）
	OtherFee float64 `json:"other_fee,omitempty"`
	// 邮资：默认值为 0，必须为非负数。（Decimal，选填）
	PostFee float64 `json:"post_fee,omitempty"`
	// 标记名称：采购单标记名称。只能使用未停用的非内置采购标记。（String，选填）
	FlagName string `json:"flag_name,omitempty"`
	// 单据备注：采购入库单备注，最长 255 个字符。（String，选填）
	Remark string `json:"remark,omitempty"`
	// 采购单号：为空时，自动生成， 不为空时会做唯一校验（String，选填）
	PurchaseNo string `json:"purchase_no,omitempty"`
}

type StockinPurchaseQuickCreateByApiOrderDetail struct {
	// 商家编码：货品商家编码。系统根据该编码匹配未删除的单品。（String，必填）
	SpecNo string `json:"spec_no"`
	// 入库数量：入库数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 是否残次品：是否按残次品入库，默认值为 false。（Boolean，选填）
	Defect bool `json:"defect,omitempty"`
	// 实际重量：实际重量，默认值为 0，必须为非负数。（Decimal，选填）
	ActualWeight float64 `json:"actual_weight,omitempty"`
	// 基本采购价：基本单位采购价。与 unit_price、purchase_amount 同时传入时优先级最高；空字符串和 null 视为未传，显式 0 保留。（Decimal，选填）
	PurchasePrice float64 `json:"purchase_price,omitempty"`
	// 辅助采购价：辅助单位采购价。未传 purchase_price 时按换算系数反算基本采购价和总采购价。（Decimal，选填）
	UnitPrice float64 `json:"unit_price,omitempty"`
	// 总采购价：当前明细总采购价。未传前两个价格字段且数量不为 0 时按数量反算基本采购价和辅助采购价（Decimal，选填）
	PurchaseAmount float64 `json:"purchase_amount,omitempty"`
	// 批次号：货品批次号。批次存在时使用已有批次；批次不存在时由接口自动创建。（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 货位编码：当前仓库的货位编码。传值时必须能匹配该仓库的有效货位。（String，选填）
	PositionNo string `json:"position_no,omitempty"`
	// 辅助单位名称：辅助单位名称（String，选填）
	UnitName string `json:"unit_name,omitempty"`
	// 生产日期：支持 yyyy-MM-dd、yyyy-MM-dd HH:mm:ss、yyyy/MM/dd 格式。（String，选填）
	ProductionDate string `json:"production_date,omitempty"`
	// 有效期：支持 yyyy-MM-dd、yyyy-MM-dd HH:mm:ss、yyyy/MM/dd 格式。（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// 保质期：保质期天数或月数，取货品配置值为默认值；只允许整数 0 至 30000，1.0 可传，1.5 不可传。（Integer，选填）
	ValidityDays int `json:"validity_days,omitempty"`
	// 明细备注：货品明细备注。（String，选填）
	Remark string `json:"remark,omitempty"`
	// 采购明细自定义属性1：采购明细自定义属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 采购明细自定义属性2：采购明细自定义属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 采购明细自定义属性3：采购明细自定义属性3（String，选填）
	Prop3 string `json:"prop3,omitempty"`
	// 采购明细自定义属性4：采购明细自定义属性4（String，选填）
	Prop4 string `json:"prop4,omitempty"`
	// 序列号：序列号信息（List<String>，选填）
	SnList []string `json:"sn_list,omitempty"`
}

type StockoutPurchaseReturnQueryWithDetailParams struct {
	// 开始时间：开始时间，若无出库单号或采购退货单号，则为必填。（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束时间，上同开始时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 时间类型：时间类型1：出库时间2：创建时间3：最后修改时间默认1（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 仓库编号：限普通仓库（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 出库单号：出库单号（String，选填）
	StockoutNo string `json:"stockout_no,omitempty"`
	// 采购退货单号：采购退货单号（String，选填）
	SrcOrderNo string `json:"src_order_no,omitempty"`
	// 出库单状态：由逗号分隔的整数数组出库单状态: 5已取消 48 未确认 50 待审核77 拣货中,PDA拣货后110已完成（String，选填）
	Status string `json:"status,omitempty"`
}

type StockoutPurchaseReturnCreateOrderOrderInfo struct {
	// 采购退货单号：采购退货单号（String，必填）
	ReturnNo string `json:"return_no"`
	// 仓库编号：仓库编号（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 物流编码：系统物流编码（String，选填）
	LogisticsCode string `json:"logistics_code,omitempty"`
	// 创建模式：默认00：编辑中/未确认1：已提交/待审核2：已审核（Int，选填）
	CreateMode int `json:"create_mode,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
}

type StockoutPurchaseReturnCreateOrderDetail struct {
	// 单品信息：单品信息（String，必填）
	SpecNo string `json:"spec_no"`
	// 出库数量：出库数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 采购单位：采购单位（String，选填）
	UnitName string `json:"unit_name,omitempty"`
	// 货位编号：货位编号（String，选填）
	PositionNo string `json:"position_no,omitempty"`
	// 批次号：批次号（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 有效期：有效期（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// 是否残次品：是否残次品true:残次品false:正品（boolean，选填）
	Defect bool `json:"defect,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 序列号：序列号信息，多个序列号之间用英文逗号隔开(1.6.0.9版本及以上强序列号产品 ，1.6.1.1版本及以支持弱序列号产品支持推送 create_mode =2 直接入库 )（String，选填）
	SnStrings string `json:"sn_strings,omitempty"`
}

type SettlePurchaseSearchParams struct {
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 供应商编号：供应商编号（String，选填）
	ProviderNo string `json:"provider_no,omitempty"`
	// 采购员姓名：采购员姓名（String，选填）
	PurchaserName string `json:"purchaser_name,omitempty"`
	// 结算单号：结算单号（String，选填）
	SettleNo string `json:"settle_no,omitempty"`
	// 采购单号：采购单号（String，选填）
	PurchaseNo string `json:"purchase_no,omitempty"`
	// 结算单状态：10:编辑中,20:待审核,30:已审核,40 已取消.不传默认显示全部.（String，选填）
	Status string `json:"status,omitempty"`
	// 创建起始时间：创建起始时间（String，选填）
	CreateFrom string `json:"create_from,omitempty"`
	// 创建结束时间：创建结束时间（String，选填）
	CreateTo string `json:"create_to,omitempty"`
	// 修改开始时间：修改开始时间（String，选填）
	ModifiedFrom string `json:"modified_from,omitempty"`
	// 修改结束时间：修改结束时间（String，选填）
	ModifiedTo string `json:"modified_to,omitempty"`
}

type SettlePurchaseUploadSettleOrder struct {
	// 采购单号：采购单号（String，必填）
	PurchaseNo string `json:"purchase_no"`
	// 物流公司编号：ERP内手动维护的物流公司编号（String，选填）
	LogisticsCompanyNo string `json:"logistics_company_no,omitempty"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 发票类型：发票类型0：无发票1：电子普通发票2：纸质普通发票3：电子增值税专用发票4：纸质增值税专用发票（byte，选填）
	InvoiceType int `json:"invoice_type,omitempty"`
	// 发票号码：发票号码（String，选填）
	InvoiceNo string `json:"invoice_no,omitempty"`
	// 邮费：邮费（Decimal(19,4)，选填）
	PostFee float64 `json:"post_fee,omitempty"`
	// 其他费用：其他费用（Decimal(19,4)，选填）
	OtherFee float64 `json:"other_fee,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 是否审核：默认false,审核失败情况下单据会创建失败（boolean，选填）
	IsCheck bool `json:"is_check,omitempty"`
	// 模糊查询：默认false,业务单号进行模糊查询匹配，匹配数量大于1条时会报错（boolean，选填）
	FuzzyQuery bool `json:"fuzzy_query,omitempty"`
}

type SettlePurchaseUploadDetail struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 结算数量：结算数量（Decimal(19,4)，必填）
	SettleNum float64 `json:"settle_num"`
	// 结算数量（非残品）：默认值为传入的结算数量（Decimal(19,4)，选填）
	SettleNormalNum float64 `json:"settle_normal_num,omitempty"`
	// 发票数量：默认值为预期数量（Decimal(19,4)，选填）
	InvoiceNum float64 `json:"invoice_num,omitempty"`
	// 单价：默认值为采购单明细税前单价*单位系数（Decimal(19,4)，选填）
	Price float64 `json:"price,omitempty"`
	// 折扣：默认值为采购单明细折扣（折扣字段，默认值为1，1代表原价，无折扣；假设需要折扣为一折时，可将字段值传为0.1，同理，折扣为5折时，传值0.5；折扣为八折时，传值0.8，以此类推）（Decimal(19,4)，选填）
	Discount float64 `json:"discount,omitempty"`
	// 税率：默认值为采购单明细税率（Decimal(19,4)，选填）
	TaxRate float64 `json:"tax_rate,omitempty"`
	// 分摊邮费：分摊邮费（Decimal(19,4)，选填）
	SharePostFee float64 `json:"share_post_fee,omitempty"`
	// 其他分摊：其他分摊（Decimal(19,4)，选填）
	ShareOther float64 `json:"share_other,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 批次号：如果采购单包含批次则需传入（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 有效期：如果采购单包含有效期则需传入（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
}

type SettlePurchaseReturnSearchParams struct {
	// 结算单号：结算单号，精确查询 (可不传时间条件)（String，选填）
	SettleNo string `json:"settle_no,omitempty"`
	// 退货单号：采购退货单号，精确查询 (可不传时间条件)（String，选填）
	ReturnNo string `json:"return_no,omitempty"`
	// 供应商：供应商编码（String，选填）
	ProviderNo string `json:"provider_no,omitempty"`
	// 结算状态：可传多个状态分割符 : , (英文)10 : 编辑中20 : 待审核30 : 已审核40 : 已取消（String，选填）
	Status string `json:"status,omitempty"`
	// 起始时间：创建时间起始值，格式：yyyy-MM-dd HH:mm:ss（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：创建时间结束值，格式：yyyy-MM-dd HH:mm:ss（String，必填）
	EndTime string `json:"end_time"`
}

type SettlePurchaseReturnUploadSettleOrder struct {
	// 采购退货单号：采购退货单号（String，必填）
	ReturnNo string `json:"return_no"`
	// 物流公司编号：ERP内手动维护的物流公司编号（String，选填）
	LogisticsCompanyNo string `json:"logistics_company_no,omitempty"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 发票类型：发票类型0：无发票1：电子普通发票2：纸质普通发票3：电子增值税专用发票4：纸质增值税专用发票（byte，选填）
	InvoiceType int `json:"invoice_type,omitempty"`
	// 发票号码：发票号码（String，选填）
	InvoiceNo string `json:"invoice_no,omitempty"`
	// 邮费：邮费（Decimal(19,4)，选填）
	PostFee float64 `json:"post_fee,omitempty"`
	// 其他费用：其他费用（Decimal(19,4)，选填）
	OtherFee float64 `json:"other_fee,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 是否审核：默认false,审核失败情况下单据会创建失败（boolean，选填）
	IsCheck bool `json:"is_check,omitempty"`
	// 模糊查询：默认false,业务单号进行模糊查询匹配，匹配数量大于1条时会报错（boolean，选填）
	FuzzyQuery bool `json:"fuzzy_query,omitempty"`
}

type SettlePurchaseReturnUploadDetail struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 结算数量：结算数量（Decimal(19,4)，必填）
	SettleNum float64 `json:"settle_num"`
	// 单价：默认值为采购退货单明细税前单价*单位系数（Decimal(19,4)，选填）
	Price float64 `json:"price,omitempty"`
	// 税率：默认值为采购退货单明细税率（Decimal(19,4)，选填）
	TaxRate float64 `json:"tax_rate,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 批次号：如果采购退货单包含批次则需传入（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 有效期：如果采购退货单包含有效期则需传入（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
}

// QueryDetail 供应商货品查询 - 获取ERP中供应商货品界面的供应商货品资料
// 【权限校验】：供应商权限 PS：不传入业务请求参数的情况下，全量获取数据销量字段说明及计算方式，点击链接查看
//
// 对应接口：purchase.ProviderGoods.queryDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.ProviderGoods.queryDetail
func (s *ProviderGoodsService) QueryDetail(ctx context.Context, params *ProviderGoodsQueryDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "purchase.ProviderGoods.queryDetail", pager, params)
}

// Upload 供应商货品推送 - 推送/更新供应商货品信息
// (1)该接口支持创建和更新，provider_no+spec_no已存在则更新，不存在则新建； (2)接口用户需要有[采购价]字段权限; 开启供应商权限的情况下需要有对应供应商权限;status = 0且error_list不为空时, 跳过异常明细, 其他正常创建。
//
// 对应接口：purchase.ProviderGoods.upload
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.ProviderGoods.upload
func (s *ProviderGoodsService) Upload(ctx context.Context, purchaseProviderGoodsList []*ProviderGoodsUploadPurchaseProviderGoods) (*Response, error) {
	return s.client.Call(ctx, "purchase.ProviderGoods.upload", purchaseProviderGoodsList)
}

// QueryWithDetail 采购单及明细查询 - 获取ERP内采购单信息
// 支持
// start_time和end_time最大跨度为30天。
// 【权限校验】：仓库权限、供应商权限如果不填写采购单号则必须填写开始时间和结束时间；填写了采购单号的时候起止时间条件失效；
//
// 对应接口：purchase.PurchaseOrder.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseOrder.queryWithDetail
func (s *PurchaseOrderService) QueryWithDetail(ctx context.Context, params *PurchaseOrderQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "purchase.PurchaseOrder.queryWithDetail", pager, params)
}

// CreateOrder 采购单新建 - 推送采购单据给ERP
//
// 对应接口：purchase.PurchaseOrder.createOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseOrder.createOrder
func (s *PurchaseOrderService) CreateOrder(ctx context.Context, params *PurchaseOrderCreateOrderParams) (*Response, error) {
	return s.client.Call(ctx, "purchase.PurchaseOrder.createOrder", params)
}

// CancelOrder 采购单取消 - 取消采购单
// 【权限校验】：如果开启采购权限配置，则校验采购权限；该接口仅可以取消状态为编辑中状态下的采购单已审核未入库状态支持取消请使用新接口：purchase.PurchaseOrder.cancelByType
//
// 对应接口：purchase.PurchaseOrder.cancelOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseOrder.cancelOrder
func (s *PurchaseOrderService) CancelOrder(ctx context.Context, purchaseNo string) (*Response, error) {
	return s.client.Call(ctx, "purchase.PurchaseOrder.cancelOrder", purchaseNo)
}

// CancelByType 采购单取消（新） - 根据传入的类型进行采购单取消或停止等待，支持对推送委外仓的采购单进行取消
//
// 对应接口：purchase.PurchaseOrder.cancelByType
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseOrder.cancelByType
func (s *PurchaseOrderService) CancelByType(ctx context.Context, params *PurchaseOrderCancelByTypeParams) (*Response, error) {
	return s.client.Call(ctx, "purchase.PurchaseOrder.cancelByType", params)
}

// Pending 采购单停止等待 - 采购单停止等待
//
// 【权限校验】：采购权限
//
// 对应接口：purchase.PurchaseOrder.pending
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseOrder.pending
func (s *PurchaseOrderService) Pending(ctx context.Context, purchaseNos []string) (*Response, error) {
	return s.client.Call(ctx, "purchase.PurchaseOrder.pending", purchaseNos)
}

// UpdatePurchaseInfo 采购单标记更新 - 修改采购单标记
//
// 对应接口：purchase.PurchaseOrder.updatePurchaseInfo
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseOrder.updatePurchaseInfo
func (s *PurchaseOrderService) UpdatePurchaseInfo(ctx context.Context, params *PurchaseOrderUpdatePurchaseInfoParams) (*Response, error) {
	return s.client.Call(ctx, "purchase.PurchaseOrder.updatePurchaseInfo", params)
}

// QueryWithDetail 采购退货单及明细查询 - 获取ERP的采购退货单信息
// 支持
// start_time和end_time最大跨度为30天。
// 【权限校验】：仓库权限如果不填写采购退货单号则必须填写开始时间和结束时间；填写了采购退货单号则起止时间条件失效。
//
// 对应接口：purchase.PurchaseReturn.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseReturn.queryWithDetail
func (s *PurchaseReturnService) QueryWithDetail(ctx context.Context, params *PurchaseReturnQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "purchase.PurchaseReturn.queryWithDetail", pager, params)
}

// CreateOrder 采购退货单新建推送 - 推送采购退货单据给ERP
//
// 对应接口：purchase.PurchaseReturn.createOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseReturn.createOrder
func (s *PurchaseReturnService) CreateOrder(ctx context.Context, orderInfo *PurchaseReturnCreateOrderOrderInfo, detailList []*PurchaseReturnCreateOrderDetail, isCheck bool) (*Response, error) {
	return s.client.Call(ctx, "purchase.PurchaseReturn.createOrder", orderInfo, detailList, isCheck)
}

// CancelOrder 采购退货单取消推送 - 推送取消已生成的采购退货单据给ERP，支持对推送委外仓的采购退货单进行取消
// 该接口可以取消状态为编辑中、待审核、已审核 出库状态:未出库状态下的采购退货单
//
// 对应接口：purchase.PurchaseReturn.cancelOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseReturn.cancelOrder
func (s *PurchaseReturnService) CancelOrder(ctx context.Context, returnNo string) (*Response, error) {
	return s.client.Call(ctx, "purchase.PurchaseReturn.cancelOrder", returnNo)
}

// BatchCancelOrder 采购退货批量取消 - 推送取消已生成的采购退货单据给ERP,支持对推送委外仓的采购退货单进行取消
// 该接口仅可以取消状态为编辑中、待审核,已审核 出库状态:未出库状态下的采购退货单，一次推送不超过20条
//
// 对应接口：purchase.PurchaseReturn.batchCancelOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseReturn.batchCancelOrder
func (s *PurchaseReturnService) BatchCancelOrder(ctx context.Context, returnNos []string) (*Response, error) {
	return s.client.Call(ctx, "purchase.PurchaseReturn.batchCancelOrder", returnNos)
}

// Pending 采购退货单停止等待 - 采购退货单停止等待
// 一次请求退货单数量不可大于500
//
// 对应接口：purchase.PurchaseReturn.pending
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseReturn.pending
func (s *PurchaseReturnService) Pending(ctx context.Context, purchaseReturnNos []string) (*Response, error) {
	return s.client.Call(ctx, "purchase.PurchaseReturn.pending", purchaseReturnNos)
}

// Upload 采购申请单创建 - 推送采购申请单据给ERP
// 【权限校验】：供应商权限、仓库权限
//
// 对应接口：purchase.PurchaseApply.upload
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseApply.upload
func (s *PurchaseApplyService) Upload(ctx context.Context, params *PurchaseApplyUploadParams) (*Response, error) {
	return s.client.Call(ctx, "purchase.PurchaseApply.upload", params)
}

// Search 采购申请单查询 - 获取ERP内采购申请单信息
// 支持
// start_time和end_time最大跨度为30天。
//
// 对应接口：purchase.PurchaseApply.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseApply.search
func (s *PurchaseApplyService) Search(ctx context.Context, params *PurchaseApplySearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "purchase.PurchaseApply.search", pager, params)
}

// CancelForApi 采购申请单取消 - 取消待确认或编辑中状态的采购申请单
//
// 对应接口：purchase.PurchaseApply.cancelForApi
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseApply.cancelForApi
func (s *PurchaseApplyService) CancelForApi(ctx context.Context, applyList []string) (*Response, error) {
	return s.client.Call(ctx, "purchase.PurchaseApply.cancelForApi", applyList)
}

// StopForApi 采购申请单停止引用 - 停止引用部分引用状态的采购申请单
//
// 对应接口：purchase.PurchaseApply.stopForApi
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.PurchaseApply.stopForApi
func (s *PurchaseApplyService) StopForApi(ctx context.Context, applyList []string) (*Response, error) {
	return s.client.Call(ctx, "purchase.PurchaseApply.stopForApi", applyList)
}

// Search 预约入库单查询 - 分页查询
// 支持
// start_time和end_time最大跨度为7天
//
// 对应接口：purchase.StockInPreOrder.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=purchase.StockInPreOrder.search
func (s *StockInPreOrderService) Search(ctx context.Context, params *StockInPreOrderSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "purchase.StockInPreOrder.search", pager, params)
}

// Upload 采购入库单推送 - 推送采购单对应的入库单给ERP
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockin.Purchase.upload
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Purchase.upload
func (s *StockinPurchaseService) Upload(ctx context.Context, stockinOrder *StockinPurchaseUploadStockinOrder, stockinDetailList []*StockinPurchaseUploadStockinDetail) (*Response, error) {
	return s.client.Call(ctx, "wms.stockin.Purchase.upload", stockinOrder, stockinDetailList)
}

// QueryWithDetail 采购入库单查询 - 获取ERP内的采购入库单
// 支持增量获取
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限、供应商权限。
//
// 对应接口：wms.stockin.Purchase.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Purchase.queryWithDetail
func (s *StockinPurchaseService) QueryWithDetail(ctx context.Context, params *StockinPurchaseQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockin.Purchase.queryWithDetail", pager, params)
}

// Cancel 采购入库单取消 - 采购入库单取消
//
// 对应接口：wms.stockin.Purchase.cancel
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Purchase.cancel
func (s *StockinPurchaseService) Cancel(ctx context.Context, stockinNo string) (*Response, error) {
	return s.client.Call(ctx, "wms.stockin.Purchase.cancel", stockinNo)
}

// QuickCreateByApi 快速采购入库单创建 - 创建快速采购入库单，同时创建并关联采购单。
// 【仓库权限】
//
// 对应接口：wms.stockin.Purchase.quickCreateByApi
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Purchase.quickCreateByApi
func (s *StockinPurchaseService) QuickCreateByApi(ctx context.Context, orderInfo *StockinPurchaseQuickCreateByApiOrderInfo, orderDetailList []*StockinPurchaseQuickCreateByApiOrderDetail, scCodeList []any) (*Response, error) {
	return s.client.Call(ctx, "wms.stockin.Purchase.quickCreateByApi", orderInfo, orderDetailList, scCodeList)
}

// QueryWithDetail 采购退货出库单查询 - 获取ERP采购退货出库单信息
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockout.PurchaseReturn.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.PurchaseReturn.queryWithDetail
func (s *StockoutPurchaseReturnService) QueryWithDetail(ctx context.Context, params *StockoutPurchaseReturnQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockout.PurchaseReturn.queryWithDetail", pager, params)
}

// CreateOrder 采购退货出库单创建 - 推送采购退货出库单据给ERP
//
// 对应接口：wms.stockout.PurchaseReturn.createOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.PurchaseReturn.createOrder
func (s *StockoutPurchaseReturnService) CreateOrder(ctx context.Context, orderInfo *StockoutPurchaseReturnCreateOrderOrderInfo, detailList []*StockoutPurchaseReturnCreateOrderDetail) (*Response, error) {
	return s.client.Call(ctx, "wms.stockout.PurchaseReturn.createOrder", orderInfo, detailList)
}

// Search 采购结算单查询 - 获取ERP采购结算单信息
// 支持
// 【权限校验】：仓库权限
//
// 对应接口：finance.settle.Purchase.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.settle.Purchase.search
func (s *SettlePurchaseService) Search(ctx context.Context, params *SettlePurchaseSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "finance.settle.Purchase.search", pager, params)
}

// Upload 创建采购结算单 - 创建采购结算单给ERP
//
// 对应接口：finance.settle.Purchase.upload
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.settle.Purchase.upload
func (s *SettlePurchaseService) Upload(ctx context.Context, settleOrder *SettlePurchaseUploadSettleOrder, detailList []*SettlePurchaseUploadDetail) (*Response, error) {
	return s.client.Call(ctx, "finance.settle.Purchase.upload", settleOrder, detailList)
}

// Search 采购退货结算单查询 - 采购结算单查询
// 【权限校验】：仓库权限
//
// 对应接口：finance.settle.PurchaseReturn.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.settle.PurchaseReturn.search
func (s *SettlePurchaseReturnService) Search(ctx context.Context, params *SettlePurchaseReturnSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "finance.settle.PurchaseReturn.search", pager, params)
}

// Upload 创建采购退货结算单 - 创建采购退换结算单给ERP
//
// 对应接口：finance.settle.PurchaseReturn.upload
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.settle.PurchaseReturn.upload
func (s *SettlePurchaseReturnService) Upload(ctx context.Context, settleOrder *SettlePurchaseReturnUploadSettleOrder, detailList []*SettlePurchaseReturnUploadDetail) (*Response, error) {
	return s.client.Call(ctx, "finance.settle.PurchaseReturn.upload", settleOrder, detailList)
}
