// Code generated by scripts/gen_sdk.py from 旺店通旗舰版 API 文档; DO NOT EDIT.
// 重新生成：python scripts/gen_sdk.py

package wdt

import "context"

// StockinRefundService 提供 wms.stockin.Refund.* 接口的封装。
type StockinRefundService struct{ client *Client }

// PreStockinService 提供 wms.stockin.PreStockin.* 接口的封装。
type PreStockinService struct{ client *Client }

// SmartRefundService 提供 wms.stockin.SmartRefund.* 接口的封装。
type SmartRefundService struct{ client *Client }

// RawRefundService 提供 aftersales.refund.RawRefund.* 接口的封装。
type RawRefundService struct{ client *Client }

// RefundService 提供 aftersales.refund.Refund.* 接口的封装。
type RefundService struct{ client *Client }

type StockinRefundQueryWithDetailParams struct {
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 入库单号：入库单号（String，选填）
	StockinNo string `json:"stockin_no,omitempty"`
	// 退换单号：退换单号（String，选填）
	RefundNo string `json:"refund_no,omitempty"`
	// 店铺编号：多个编号间使用英文逗号分隔（String，选填）
	ShopNos string `json:"shop_nos,omitempty"`
	// 入库单状态：英文逗号拼接的状态值:10=已取消；20=编辑中；30=待审核/待处理；80=已完成（String，选填）
	Status string `json:"status,omitempty"`
	// 时间条件类型：查询的时间条件类型, 0:修改时间; 1:入库时间 不传默认为0（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 开始时间：起始时间, yyyy-MM-dd HH:mm:ss格式（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间, yyyy-MM-dd HH:mm:ss格式（String，必填）
	EndTime string `json:"end_time"`
	// 是否使用从库查询：使用：true 不使用：false（仅对开通从库配置客户生效）（boolean，选填）
	IsSlave bool `json:"is_slave,omitempty"`
	// 是否返回sn信息：返回：true不返回：false（boolean，选填）
	NeedSn bool `json:"need_sn,omitempty"`
	// 是否需要汇总数据：需要：true不需要：false默认false（bool，选填）
	NeedSummary bool `json:"need_summary,omitempty"`
	// 是否需要国补信息：0：不需要1：需要默认0（boolean，选填）
	NeedGovSubsidyInfo bool `json:"need_gov_subsidy_info,omitempty"`
	// 是否仅获取库存记录：0：否1：是默认0（Int，选填）
	FetchStockOnly int `json:"fetch_stock_only,omitempty"`
	// 平台id：平台id，详见平台代码表（Int，选填）
	PlatformId int `json:"platform_id,omitempty"`
}

type StockinRefundQueryHisWithDetailParams struct {
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 入库单号：入库单号（String，选填）
	StockinNo string `json:"stockin_no,omitempty"`
	// 退换单号：退换单号（String，选填）
	RefundNo string `json:"refund_no,omitempty"`
	// 店铺编号：多个编号间使用英文逗号分隔（String，选填）
	ShopNos string `json:"shop_nos,omitempty"`
	// 入库单状态：英文逗号拼接的状态值:10=已取消；20=编辑中；30=待审核/待处理；80=已完成（String，选填）
	Status string `json:"status,omitempty"`
	// 时间条件类型：查询的时间条件类型, 0:修改时间; 1:入库时间 不传默认为0（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 开始时间：起始时间, yyyy-MM-dd HH:mm:ss格式（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间, yyyy-MM-dd HH:mm:ss格式（String，必填）
	EndTime string `json:"end_time"`
	// 是否使用从库查询：使用：true 不使用：false（仅对开通从库配置客户生效）（boolean，选填）
	IsSlave bool `json:"is_slave,omitempty"`
	// 是否返回sn信息：返回：true不返回：false（boolean，选填）
	NeedSn bool `json:"need_sn,omitempty"`
}

type StockinRefundCreateOrderStockinOrder struct {
	// 退换单号：退换单号（String，必填）
	RefundNo string `json:"refund_no"`
	// 外部单号：外部单号（String，选填）
	OutStockinNo string `json:"out_stockin_no,omitempty"`
	// 仓库编号：仓库编号（不支持传入多个仓库编号）（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 系统物流公司编号：系统物流公司编号（String，选填）
	LogisticsCode string `json:"logistics_code,omitempty"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 创建模式：默认00：编辑中1：已提交2：已审核（Int，选填）
	CreateMode int `json:"create_mode,omitempty"`
	// 是否创建批次：true：创建false：不创建默认不创建（boolean，选填）
	IsCreateBatch bool `json:"is_create_batch,omitempty"`
	// 单据明细：明细信息（List<Map<String, Object>>，必填）
	DetailList []*StockinRefundCreateOrderStockinOrderDetail `json:"detail_list"`
}

type StockinRefundCreateOrderStockinOrderDetail struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 数量：数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 是否残次品：true：残次品false：正品默认false（boolean，选填）
	Defect bool `json:"defect,omitempty"`
	// sn码：多个之间使用英文逗号分隔，当传入sn信息时，create_mode需要传为0（String，选填）
	SnStrings string `json:"sn_strings,omitempty"`
	// 批次号：批次号（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 有效期：有效期（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// 货位编号：货位编号（String，选填）
	PositionNo string `json:"position_no,omitempty"`
	// 生产日期：生产日期（String，选填）
	ProductionDate string `json:"production_date,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 批次备注：批次备注（String，选填）
	BatchRemark string `json:"batch_remark,omitempty"`
	// 入库价：不传默认取退换单明细中的价格字段（Decimal(19,4)，选填）
	StockinPrice float64 `json:"stockin_price,omitempty"`
}

type StockinRefundReturnLogisticsPackageQueryParams struct {
	// 开始时间：最后修改时间（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：最后修改时间（String，必填）
	EndTime string `json:"end_time"`
	// 物流单号：物流单号（当传入物流单号，其他不校验）（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 入库单状态：-2待处理，10已取消，20编辑者，30待审核，37待质检，40质检待确认，80已完成（bytre，选填）
	StockinStatus any `json:"stockin_status,omitempty"`
}

type PreStockinCreateExtStockinOrder struct {
	// 仓库编号：仓库编号（不支持外部仓储）（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 入库单号：入库单号（String，必填）
	StockinNo string `json:"stockin_no"`
	// 备注：备注，若无可为””（String，必填）
	Remark string `json:"remark"`
	// 寄回物流单号：寄回物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 自定义属性1：自定义属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 自定义属性2：自定义属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 客户网名：客户网名（String，选填）
	CustomerNickname string `json:"customer_nickname,omitempty"`
	// 客户姓名：客户姓名（String，选填）
	CustomerName string `json:"customer_name,omitempty"`
	// 客户手机：客户手机号（String，选填）
	CustomerPhone string `json:"customer_phone,omitempty"`
	// 入库标记：入库标记（String，选填）
	FlagName string `json:"flag_name,omitempty"`
}

type PreStockinCreateExtSpec struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 备注：备注（String，必填）
	Remark string `json:"remark"`
	// 数量：入库数量（Int，必填）
	Num int `json:"num"`
	// 残次品：是否为残次品（Boolean，必填）
	Defect bool `json:"defect"`
}

type PreStockinSearchParams struct {
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 入库单号：入库单号（String，选填）
	StockinNo string `json:"stockin_no,omitempty"`
	// 寄回物流单号：寄回物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 修改起始时间：修改起始时间（datetime，选填）
	MtFrom string `json:"mt_from,omitempty"`
	// 修改结束时间：修改结束时间（datetime，选填）
	MtTo string `json:"mt_to,omitempty"`
	// 创建起始时间：创建起始时间（datetime，选填）
	CtFrom string `json:"ct_from,omitempty"`
	// 创建结束时间：创建结束时间（datetime，选填）
	CtTo string `json:"ct_to,omitempty"`
	// 退货人姓名：退货人姓名（String，选填）
	SenderName string `json:"sender_name,omitempty"`
	// 客户网名：客户网名（String，选填）
	BuyerNick string `json:"buyer_nick,omitempty"`
	// 退货人手机：退货人手机（String，选填）
	SenderMobile string `json:"sender_mobile,omitempty"`
	// 商家编码：商家编码（String，选填）
	SpecNo string `json:"spec_no,omitempty"`
	// 货品编号：货品编号（String，选填）
	GoodsNo string `json:"goods_no,omitempty"`
	// 货品名称：货品名称（String，选填）
	GoodsName string `json:"goods_name,omitempty"`
	// 条码：条码（String，选填）
	Barcode string `json:"barcode,omitempty"`
	// 货品简称：货品简称（String，选填）
	ShortName string `json:"short_name,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 入库单状态：10:已取消;20编辑中;30:待审核;80:已完成（int，选填）
	Status int `json:"status,omitempty"`
}

type SmartRefundUploadRefundInfo struct {
	// 原始单号：原始单号（String，必填）
	Tid string `json:"tid"`
	// 退货入库仓编号：退货入库仓编号（不支持外部仓库）（String，必填）
	ReturnWarehouseNo string `json:"return_warehouse_no"`
	// 退货备注：退货备注,无备注可以传空字符串（String，必填）
	Remark string `json:"remark"`
	// 退货物流单号：退货物流单号（String，选填）
	ReturnLogisticsNo string `json:"return_logistics_no,omitempty"`
}

type SmartRefundUploadDetailMap struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 入库数量：入库数量（Decimal，必填）
	StockinNum float64 `json:"stockin_num"`
	// 备注：备注,无备注可以传空字符串（String，必填）
	Remark string `json:"remark"`
}

type RawRefundUploadOrder struct {
	// 原始退款单号：原始退款单号（String，必填）
	RefundNo string `json:"refund_no"`
	// 货品数量：货品数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 原始单号：原始单号（String，必填）
	Tid string `json:"tid"`
	// 原始子单号：原始子单号（String，必填）
	Oid string `json:"oid"`
	// 退款单类型：0取消订单1退款(未发货，退款申请)2退货退款 4退款不退货当type=3时原始退款单递交不会生成系统退货单（Int，必填）
	Type int `json:"type"`
	// 平台状态：1取消退款,2已申请退款,3等待退货,4等待收货,5退款成功（Int，必填）
	Status int `json:"status"`
	// 退款版本：退款版本，默认传1即可（String，必填）
	RefundVersion string `json:"refund_version"`
	// 申请退款金额：申请退款金额（Decimal(19,4)，必填）
	RefundAmount float64 `json:"refund_amount"`
	// 实际退款金额：实际退款金额（Decimal(19,4)，必填）
	ActualRefundAmount float64 `json:"actual_refund_amount"`
	// 标题：标题，对应原始退款单页面主单货品字段,若无传空字符串（String，必填）
	Title string `json:"title"`
	// 物流公司名称：物流公司名称（支持自定义推送），若无传空字符串（String，选填）
	LogisticsName string `json:"logistics_name,omitempty"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 客户网名：客户网名（String，必填）
	BuyerNick string `json:"buyer_nick"`
	// 退款创建时间：退款创建时间（String，选填）
	RefundTime string `json:"refund_time,omitempty"`
	// 退款成功时间：退款成功时间（String，选填）
	CurrentPhaseTimeout string `json:"current_phase_timeout,omitempty"`
	// 是否售后退款单：是否售后退款单（Int，必填）
	IsAftersale int `json:"is_aftersale"`
	// 退款原因：退款原因（String，必填）
	Reason string `json:"reason"`
	// 单价：单价（Decimal(19,4)，选填）
	Price float64 `json:"price,omitempty"`
	// 买家支付帐号：买家支付帐号（String，选填）
	PayAccount string `json:"pay_account,omitempty"`
	// 支付订单号：支付订单号（String，选填）
	PayNo string `json:"pay_no,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 退款货品总价：退款货品总价（Decimal(19,4)，选填）
	TotalAmount float64 `json:"total_amount,omitempty"`
	// 平台规格编号：平台规格编号（String，选填）
	SpecNo string `json:"spec_no,omitempty"`
	// 平台规格id：平台规格id（String，选填）
	SpecId string `json:"spec_id,omitempty"`
	// 平台货品编号：平台货品编号（String，选填）
	GoodsNo string `json:"goods_no,omitempty"`
	// 平台货品id：平台货品id（String，选填）
	GoodsId string `json:"goods_id,omitempty"`
	// 是否拒收：是否拒收 1 : 是 0 : 否（boolean，选填）
	IsRejectReturn bool `json:"is_reject_return,omitempty"`
}

type RawRefundUpload2Order struct {
	// 原始退款单号：原始退款单号（String，必填）
	RefundNo string `json:"refund_no"`
	// 货品数量：货品数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 原始单号：原始单号（String，必填）
	Tid string `json:"tid"`
	// 原始子单号：原始子单号（String，必填）
	Oid string `json:"oid"`
	// 退款单类型：0取消订单1退款(未发货，退款申请)2退货退款 4退款不退货当type=3时原始退款单递交不会生成系统退货单（Int，必填）
	Type int `json:"type"`
	// 平台状态：1取消退款,2已申请退款,3等待退货,4等待收货,5退款成功（Int，必填）
	Status int `json:"status"`
	// 退款版本：退款版本，默认传1即可（String，必填）
	RefundVersion string `json:"refund_version"`
	// 申请退款金额：申请退款金额（Decimal(19,4)，必填）
	RefundAmount float64 `json:"refund_amount"`
	// 实际退款金额：实际退款金额（Decimal(19,4)，必填）
	ActualRefundAmount float64 `json:"actual_refund_amount"`
	// 标题：标题，对应原始退款单页面主单货品字段，若无传空字符串（String，必填）
	Title string `json:"title"`
	// 物流公司名称：物流公司名称（支持自定义推送），若无传空字符串（String，选填）
	LogisticsName string `json:"logistics_name,omitempty"`
	// 物流单号：物流单号，若无传空字符串（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 客户网名：客户网名（String，必填）
	BuyerNick string `json:"buyer_nick"`
	// 退款创建时间：退款创建时间（String，选填）
	RefundTime string `json:"refund_time,omitempty"`
	// 退款成功时间：退款成功时间（String，选填）
	CurrentPhaseTimeout string `json:"current_phase_timeout,omitempty"`
	// 是否售后退款单：是否售后退款单0：否1：是（Int，必填）
	IsAftersale int `json:"is_aftersale"`
	// 退款原因：退款原因（String，必填）
	Reason string `json:"reason"`
	// 单价：单价（Decimal(19,4)，选填）
	Price float64 `json:"price,omitempty"`
	// 买家支付帐号：买家支付帐号（String，选填）
	PayAccount string `json:"pay_account,omitempty"`
	// 支付订单号：支付订单号（String，选填）
	PayNo string `json:"pay_no,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 退款货品总价：退款货品总价（Decimal(19,4)，选填）
	TotalAmount float64 `json:"total_amount,omitempty"`
	// 平台规格编号：平台规格编号（String，选填）
	SpecNo string `json:"spec_no,omitempty"`
	// 平台规格id：平台规格id（String，选填）
	SpecId string `json:"spec_id,omitempty"`
	// 平台货品编号：平台货品编号（String，选填）
	GoodsNo string `json:"goods_no,omitempty"`
	// 平台货品id：平台货品id（String，选填）
	GoodsId string `json:"goods_id,omitempty"`
	// 修改掩码：1:新订单2:状态变化4:金额变化（Int，选填）
	ModifyFlag int `json:"modify_flag,omitempty"`
	// 是否拒收：是否拒收 1 : 是 0 : 否（boolean，选填）
	IsRejectReturn bool `json:"is_reject_return,omitempty"`
}

type RawRefundSearchParams struct {
	// 开始时间：开始时间（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间（String，必填）
	EndTime string `json:"end_time"`
	// 时间条件类型：1：修改时间2：退款时间不传按照修改时间获取数据（Int，必填）
	TimeType int `json:"time_type"`
	// 原始退单号：原始退单号(1.5.8.2及以上版本可以只传refund_no)（String，选填）
	RefundNo string `json:"refund_no,omitempty"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 平台id：平台id，映射表点击详情查看（Int，选填）
	PlatformId int `json:"platform_id,omitempty"`
	// 店铺编号：店铺编号（暂不支持批量查询）（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
	// 原始单号：原始单号（String，选填）
	Tid string `json:"tid,omitempty"`
	// 原始子单号：原始子单号（String，选填）
	Oid string `json:"oid,omitempty"`
	// 明细掩码：0：不返回原始退款单优惠1：返回原始退款单优惠默认0（Int，选填）
	DetailMask int `json:"detail_mask,omitempty"`
	// 是否过滤明细：0：不过滤（默认会返回type=1明细取自原始退款单主单的数据）1：过滤（只返回type=0明细取自原始退款单明细的数据，与客户端原始退款单明细展示的数据保持一致）（Int，选填）
	FilterDetail int `json:"filter_detail,omitempty"`
}

type RawRefundSearchHistoryParams struct {
	// 开始时间：开始时间（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间（String，必填）
	EndTime string `json:"end_time"`
	// 时间条件类型：1：修改时间2：退款时间不传按照修改时间获取数据（Int，必填）
	TimeType int `json:"time_type"`
	// 原始退单号：原始退单号（String，选填）
	RefundNo string `json:"refund_no,omitempty"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 平台id：平台id，映射表点击详情查看（Int，选填）
	PlatformId int `json:"platform_id,omitempty"`
	// 店铺编号：店铺编号（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
	// 原始单号：原始单号（String，选填）
	Tid string `json:"tid,omitempty"`
	// 原始子单号：原始子单号（String，选填）
	Oid string `json:"oid,omitempty"`
	// 明细掩码：0：不返回原始退款单优惠1：返回原始退款单优惠默认0（Int，选填）
	DetailMask int `json:"detail_mask,omitempty"`
}

type RefundSearchParams struct {
	// 店铺编号：由英文逗号分隔的店铺编号（String，选填）
	ShopNos string `json:"shop_nos,omitempty"`
	// 原始单号：原始单号（String，选填）
	Tid string `json:"tid,omitempty"`
	// 客户网名：客户网名（String，选填）
	BuyerNick string `json:"buyer_nick,omitempty"`
	// 系统订单编号：系统订单编号（String，选填）
	TradeNo string `json:"trade_no,omitempty"`
	// 退换单号：退换单号（String，选填）
	RefundNo string `json:"refund_no,omitempty"`
	// 物流单号：物流单号（退换单上的退回物流单号）（String，选填）
	ReturnLogisticsNo string `json:"return_logistics_no,omitempty"`
	// 修改起始时间：修改起始时间（String，选填）
	ModifiedFrom string `json:"modified_from,omitempty"`
	// 修改结束时间：修改结束时间（String，选填）
	ModifiedTo string `json:"modified_to,omitempty"`
	// 开始时间：结算时间（String，选填）
	SettleFrom string `json:"settle_from,omitempty"`
	// 结束时间：结算时间（String，选填）
	SettleTo string `json:"settle_to,omitempty"`
	// 审核起始时间：审核起始时间（String，选填）
	AgreeFrom string `json:"agree_from,omitempty"`
	// 审核结束时间：审核结束时间（String，选填）
	AgreeTo string `json:"agree_to,omitempty"`
	// 退换单状态：10:已取消;20:待审核;30:已审核;40已推送:80:已结算;81:待回传;85:待过账;86:已过账;87:成本确认;90:已完成（Int，选填）
	Status int `json:"status,omitempty"`
	// 入库状态：0:无需入库;1:待入库;2:部分入库;3:全部入库;4:终止入库（Int，选填）
	StockinStatus int `json:"stockin_status,omitempty"`
	// 退回仓库编号：退回仓库编号，用英文逗号分隔（String，选填）
	ReturnWarehouseNos string `json:"return_warehouse_nos,omitempty"`
	// 退换单类型：1:售前退款;2:退货;3:换货;4:退款不退货;6:保价退款 7:批发退货退款（Int，选填）
	Type int `json:"type,omitempty"`
	// 模糊查询：默认false,业务单号进行模糊查询匹配，匹配数量大于1条时会报错（boolean，选填）
	FuzzyQuery bool `json:"fuzzy_query,omitempty"`
	// 是否为拦截件：0：否 1：是不传不判断（boolean，选填）
	ReturnMaskManualIntercept bool `json:"return_mask_manual_intercept,omitempty"`
	// 是否拒收：0：否 1：是不传不判断（boolean，选填）
	RefundMaskRejectReturn bool `json:"refund_mask_reject_return,omitempty"`
	// 排序类型：0：默认排序1：修改时间降序（Int，选填）
	OrderType int `json:"order_type,omitempty"`
	// 平台状态：1:取消退款2:申请退款3:等待退货4:等待收货5:退款成功7:卖家拒绝退款20:换货待处理30:待买家退货40:买家已退货，待收货50:待买家修改60:待发出换货商品65:换货转退款不退货75:已发货，待买家收货70:换货转退货10:换货关闭80:换货成功不传默认全部（Int，选填）
	RrStatus int `json:"rr_status,omitempty"`
	// 退款成功时间起始：退款成功时间起始（String，选填）
	CurrentPhaseTimeoutFrom string `json:"current_phase_timeout_from,omitempty"`
	// 退款成功时间结束：退款成功时间结束（String，选填）
	CurrentPhaseTimeoutTo string `json:"current_phase_timeout_to,omitempty"`
	// 是否需要国补信息：0：不需要1：需要默认0（boolean，选填）
	NeedGovSubsidyInfo bool `json:"need_gov_subsidy_info,omitempty"`
	// 原始退款单号：原始退款单号（String，选填）
	RawRefundNos string `json:"raw_refund_nos,omitempty"`
}

type RefundSearchHistoryParams struct {
	// 开始时间：起始时间, 针对最后变更时间检索。如果退换单号为空则时间条件必填（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 店铺编号：店铺编号（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
	// 退换单号：退换单号（String，选填）
	RefundNo string `json:"refund_no,omitempty"`
	// 类型：1：售前退款；2：退货；3：换货；4：退款不退货（Int，选填）
	Type int `json:"type,omitempty"`
	// 退换单状态：用逗号分隔开数字的字符串。10：已取消；90：已完成（String，选填）
	Status string `json:"status,omitempty"`
}

// QueryWithDetail 退货入库单查询 - 获取ERP的退货入库单单据信息
// 支持
// start_time和end_time最大跨度为30天。
// 【权限校验】：仓库权限，店铺权限为了达到保护用户隐私数据安全的目的，本接口不返回淘系、拼多多及系统供销平台数据，淘系相关平台规则点击这里，淘系及系统供销平台数据获取办法点击这里，拼多多请自行对接平台获取。本接口中涉及到用户隐私的字段数据仅自有平台及线下平台订单返回。具体字段详情见下面表格；
//
// 对应接口：wms.stockin.Refund.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Refund.queryWithDetail
func (s *StockinRefundService) QueryWithDetail(ctx context.Context, params *StockinRefundQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockin.Refund.queryWithDetail", pager, params)
}

// QueryHisWithDetail 历史退货入库单查询 - 获取ERP的历史退货入库单单据信息
// 支持
// start_time和end_time最大跨度为30天。
// 【权限校验】：仓库权限，店铺权限为了达到保护用户隐私数据安全的目的，本接口不返回淘系、拼多多及系统供销平台数据，淘系相关平台规则点击这里，淘系及系统供销平台数据获取办法点击这里，拼多多请自行对接平台获取。本接口中涉及到用户隐私的字段数据仅自有平台及线下平台订单返回。具体字段详情见下面表格；
//
// 对应接口：wms.stockin.Refund.queryHisWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Refund.queryHisWithDetail
func (s *StockinRefundService) QueryHisWithDetail(ctx context.Context, params *StockinRefundQueryHisWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockin.Refund.queryHisWithDetail", pager, params)
}

// CreateOrder 退货入库单推送 - 推送退货入库单给ERP
//
// 不支持批量创建、不支持委外仓储
//
// 对应接口：wms.stockin.Refund.createOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Refund.createOrder
func (s *StockinRefundService) CreateOrder(ctx context.Context, stockinOrder *StockinRefundCreateOrderStockinOrder) (*Response, error) {
	return s.client.Call(ctx, "wms.stockin.Refund.createOrder", stockinOrder)
}

// ReturnLogisticsPackageQuery 退货物流包裹查询 - 退货物流分页查询
// 支持
// start_time和end_time最大跨度为30天
//
// 对应接口：wms.stockin.Refund.returnLogisticsPackageQuery
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Refund.returnLogisticsPackageQuery
func (s *StockinRefundService) ReturnLogisticsPackageQuery(ctx context.Context, params *StockinRefundReturnLogisticsPackageQueryParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockin.Refund.returnLogisticsPackageQuery", pager, params)
}

// CreateExt 创建退货预入库 - 推送退货预入库单据给ERP
//
// 【权限校验】：仓库权限、 不支持外部仓储
//
// 对应接口：wms.stockin.PreStockin.createExt
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.PreStockin.createExt
func (s *PreStockinService) CreateExt(ctx context.Context, stockinOrder *PreStockinCreateExtStockinOrder, specList []*PreStockinCreateExtSpec) (*Response, error) {
	return s.client.Call(ctx, "wms.stockin.PreStockin.createExt", stockinOrder, specList)
}

// Search 预入库单据查询 - 获取ERP预入库单单据信息
// 支持增量获取
//
// 【权限校验】：仓库权限 ,此接口仅支持奇门自定场景访问
//
// 对应接口：wms.stockin.PreStockin.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.PreStockin.search
func (s *PreStockinService) Search(ctx context.Context, params *PreStockinSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockin.PreStockin.search", pager, params)
}

// Cancel 退货预入库单取消 - 取消编辑中/待审核状态的预入库单
// 不支持
// start_time和end_time最大跨度为30天。
// 【权限校验】：无
//
// 对应接口：wms.stockin.PreStockin.cancel
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.PreStockin.cancel
func (s *PreStockinService) Cancel(ctx context.Context, preStockinNo string) (*Response, error) {
	return s.client.Call(ctx, "wms.stockin.PreStockin.cancel", preStockinNo)
}

// Upload 快速退货推送 - 推送快速退货单据信息给ERP
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockin.SmartRefund.upload
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.SmartRefund.upload
func (s *SmartRefundService) Upload(ctx context.Context, refundInfo *SmartRefundUploadRefundInfo, detailMapList []*SmartRefundUploadDetailMap, createPreStockin bool) (*Response, error) {
	return s.client.Call(ctx, "wms.stockin.SmartRefund.upload", refundInfo, detailMapList, createPreStockin)
}

// Upload 原始退款单推送 - 创建售后退货单给ERP，更新售后单退货物流信息、退货单退款金额等
//
// 【权限校验】：店铺权限
//
// 对应接口：aftersales.refund.RawRefund.upload
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=aftersales.refund.RawRefund.upload
func (s *RawRefundService) Upload(ctx context.Context, shopNo string, orderList []*RawRefundUploadOrder) (*Response, error) {
	return s.client.Call(ctx, "aftersales.refund.RawRefund.upload", shopNo, orderList)
}

// Upload2 原始退款单推送2 - 创建售后退货单给ERP，更新售后单退货物流信息、退货单退款金额等
//
// 【权限校验】：店铺权限单次推送建议单量不超过100单
//
// 对应接口：aftersales.refund.RawRefund.upload2
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=aftersales.refund.RawRefund.upload2
func (s *RawRefundService) Upload2(ctx context.Context, shopNo string, orderList []*RawRefundUpload2Order) (*Response, error) {
	return s.client.Call(ctx, "aftersales.refund.RawRefund.upload2", shopNo, orderList)
}

// Search 原始退款单查询 - 获取ERP原始退款单信息
// 支持
// start_time和end_time最大跨度为30天。
//
// 对应接口：aftersales.refund.RawRefund.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=aftersales.refund.RawRefund.search
func (s *RawRefundService) Search(ctx context.Context, params *RawRefundSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "aftersales.refund.RawRefund.search", pager, params)
}

// SearchHistory 历史原始退款单查询 - 获取ERP已归档的原始退款单信息
// 支持
// start_time和end_time最大跨度为30天。
//
// 对应接口：aftersales.refund.RawRefund.searchHistory
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=aftersales.refund.RawRefund.searchHistory
func (s *RawRefundService) SearchHistory(ctx context.Context, params *RawRefundSearchHistoryParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "aftersales.refund.RawRefund.searchHistory", pager, params)
}

// Search 退换单查询 - 获取ERP销售退货（换货）订单信息
// 支持
// 请求时间最大跨度为30天。
// 【权限校验】：店铺权限 为了达到保护用户隐私数据安全的目的，本接口不返回淘系、拼多多及系统供销平台货品数据，相关平台规则点击这里，淘系及系统供销平台数据获取办法点击这里，拼多多请自行对接平台获取。本接口中涉及到用户隐私的字段数据仅自有平台及线下平台订单返回。具体字段详情见下面表格；
//
// 对应接口：aftersales.refund.Refund.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=aftersales.refund.Refund.search
func (s *RefundService) Search(ctx context.Context, params *RefundSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "aftersales.refund.Refund.search", pager, params)
}

// SearchHistory 历史退换单查询 - 查询已经归档的退换单信息
// 支持
// 请求时间最大跨度为30天。
// 【权限校验】：店铺权限 为了达到保护用户隐私数据安全的目的，本接口不返回淘系、拼多多及系统供销平台货品数据，相关平台规则点击这里，淘系及系统供销平台数据获取办法点击这里，拼多多请自行对接平台获取。本接口中涉及到用户隐私的字段数据仅自有平台及线下平台订单返回。具体字段详情见下面表格；
//
// 对应接口：aftersales.refund.Refund.searchHistory
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=aftersales.refund.Refund.searchHistory
func (s *RefundService) SearchHistory(ctx context.Context, params *RefundSearchHistoryParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "aftersales.refund.Refund.searchHistory", pager, params)
}
