// Code generated by scripts/gen_sdk.py from 旺店通旗舰版 API 文档; DO NOT EDIT.
// 重新生成：python scripts/gen_sdk.py

package wdt

// Services 按业务主题分组暴露全部开放平台接口。
type Services struct {
	TradeQuery             *TradeQueryService
	RawTrade               *RawTradeService
	LogisticsSync          *LogisticsSyncService
	StockSync              *StockSyncService
	TradeEdit              *TradeEditService
	TradeImport            *TradeImportService
	SalesPayment           *SalesPaymentService
	SalesJitRefund         *SalesJitRefundService
	StockoutSales          *StockoutSalesService
	InvoiceOrder           *InvoiceOrderService
	RawPayment             *RawPaymentService
	AlipayAccountCheck     *AlipayAccountCheckService
	FinancePayment         *FinancePaymentService
	CustomAttr             *CustomAttrService
	Logistics              *LogisticsService
	PurchaseProvider       *PurchaseProviderService
	Warehouse              *WarehouseService
	Shop                   *ShopService
	Employee               *EmployeeService
	VirtualWarehouse       *VirtualWarehouseService
	OperationReason        *OperationReasonService
	Address                *AddressService
	Composite              *CompositeService
	Goods                  *GoodsService
	Suite                  *SuiteService
	ApiGoods               *ApiGoodsService
	GoodsClass             *GoodsClassService
	GoodsBrand             *GoodsBrandService
	Category               *CategoryService
	Barcode                *BarcodeService
	Bom                    *BomService
	Process                *ProcessService
	SettleProcess          *SettleProcessService
	ProviderGoods          *ProviderGoodsService
	PurchaseOrder          *PurchaseOrderService
	PurchaseReturn         *PurchaseReturnService
	PurchaseApply          *PurchaseApplyService
	StockInPreOrder        *StockInPreOrderService
	StockinPurchase        *StockinPurchaseService
	StockoutPurchaseReturn *StockoutPurchaseReturnService
	SettlePurchase         *SettlePurchaseService
	SettlePurchaseReturn   *SettlePurchaseReturnService
	StockSpec              *StockSpecService
	StockPd                *StockPdService
	MoveOrder              *MoveOrderService
	StockinOther           *StockinOtherService
	StockoutOther          *StockoutOtherService
	StockoutOtherQuery     *StockoutOtherQueryService
	StockinTransfer        *StockinTransferService
	StockoutTransfer       *StockoutTransferService
	StockTransfer          *StockTransferService
	StockTransferEdit      *StockTransferEditService
	StockShelve            *StockShelveService
	StockotherIn           *StockotherInService
	StockotherInQuery      *StockotherInQueryService
	StockotherOut          *StockotherOutService
	StockotherOutQuery     *StockotherOutQueryService
	StockoutProcess        *StockoutProcessService
	StockinProcess         *StockinProcessService
	OuterOut               *OuterOutService
	OuterIn                *OuterInService
	OuterTransfer          *OuterTransferService
	DefectChange           *DefectChangeService
	SalesPick              *SalesPickService
	PositionCapacity       *PositionCapacityService
	Pack                   *PackService
	StockinJitRefund       *StockinJitRefundService
	StockoutJitOrder       *StockoutJitOrderService
	GoodsSN                *GoodsSNService
	GoodsBatch             *GoodsBatchService
	GoodsPack              *GoodsPackService
	StockinBase            *StockinBaseService
	StockoutBase           *StockoutBaseService
	ErrorCorrection        *ErrorCorrectionService
	StockCost              *StockCostService
	SettleTransfer         *SettleTransferService
	SettleLogistics        *SettleLogisticsService
	SettleOtherIn          *SettleOtherInService
	StockoutCollect        *StockoutCollectService
	StockinCollect         *StockinCollectService
	StockinRefund          *StockinRefundService
	PreStockin             *PreStockinService
	SmartRefund            *SmartRefundService
	RawRefund              *RawRefundService
	Refund                 *RefundService
	System                 *SystemService
}

// newServices 初始化各业务服务。
func newServices(c *Client) {
	c.TradeQuery = &TradeQueryService{client: c}
	c.RawTrade = &RawTradeService{client: c}
	c.LogisticsSync = &LogisticsSyncService{client: c}
	c.StockSync = &StockSyncService{client: c}
	c.TradeEdit = &TradeEditService{client: c}
	c.TradeImport = &TradeImportService{client: c}
	c.SalesPayment = &SalesPaymentService{client: c}
	c.SalesJitRefund = &SalesJitRefundService{client: c}
	c.StockoutSales = &StockoutSalesService{client: c}
	c.InvoiceOrder = &InvoiceOrderService{client: c}
	c.RawPayment = &RawPaymentService{client: c}
	c.AlipayAccountCheck = &AlipayAccountCheckService{client: c}
	c.FinancePayment = &FinancePaymentService{client: c}
	c.CustomAttr = &CustomAttrService{client: c}
	c.Logistics = &LogisticsService{client: c}
	c.PurchaseProvider = &PurchaseProviderService{client: c}
	c.Warehouse = &WarehouseService{client: c}
	c.Shop = &ShopService{client: c}
	c.Employee = &EmployeeService{client: c}
	c.VirtualWarehouse = &VirtualWarehouseService{client: c}
	c.OperationReason = &OperationReasonService{client: c}
	c.Address = &AddressService{client: c}
	c.Composite = &CompositeService{client: c}
	c.Goods = &GoodsService{client: c}
	c.Suite = &SuiteService{client: c}
	c.ApiGoods = &ApiGoodsService{client: c}
	c.GoodsClass = &GoodsClassService{client: c}
	c.GoodsBrand = &GoodsBrandService{client: c}
	c.Category = &CategoryService{client: c}
	c.Barcode = &BarcodeService{client: c}
	c.Bom = &BomService{client: c}
	c.Process = &ProcessService{client: c}
	c.SettleProcess = &SettleProcessService{client: c}
	c.ProviderGoods = &ProviderGoodsService{client: c}
	c.PurchaseOrder = &PurchaseOrderService{client: c}
	c.PurchaseReturn = &PurchaseReturnService{client: c}
	c.PurchaseApply = &PurchaseApplyService{client: c}
	c.StockInPreOrder = &StockInPreOrderService{client: c}
	c.StockinPurchase = &StockinPurchaseService{client: c}
	c.StockoutPurchaseReturn = &StockoutPurchaseReturnService{client: c}
	c.SettlePurchase = &SettlePurchaseService{client: c}
	c.SettlePurchaseReturn = &SettlePurchaseReturnService{client: c}
	c.StockSpec = &StockSpecService{client: c}
	c.StockPd = &StockPdService{client: c}
	c.MoveOrder = &MoveOrderService{client: c}
	c.StockinOther = &StockinOtherService{client: c}
	c.StockoutOther = &StockoutOtherService{client: c}
	c.StockoutOtherQuery = &StockoutOtherQueryService{client: c}
	c.StockinTransfer = &StockinTransferService{client: c}
	c.StockoutTransfer = &StockoutTransferService{client: c}
	c.StockTransfer = &StockTransferService{client: c}
	c.StockTransferEdit = &StockTransferEditService{client: c}
	c.StockShelve = &StockShelveService{client: c}
	c.StockotherIn = &StockotherInService{client: c}
	c.StockotherInQuery = &StockotherInQueryService{client: c}
	c.StockotherOut = &StockotherOutService{client: c}
	c.StockotherOutQuery = &StockotherOutQueryService{client: c}
	c.StockoutProcess = &StockoutProcessService{client: c}
	c.StockinProcess = &StockinProcessService{client: c}
	c.OuterOut = &OuterOutService{client: c}
	c.OuterIn = &OuterInService{client: c}
	c.OuterTransfer = &OuterTransferService{client: c}
	c.DefectChange = &DefectChangeService{client: c}
	c.SalesPick = &SalesPickService{client: c}
	c.PositionCapacity = &PositionCapacityService{client: c}
	c.Pack = &PackService{client: c}
	c.StockinJitRefund = &StockinJitRefundService{client: c}
	c.StockoutJitOrder = &StockoutJitOrderService{client: c}
	c.GoodsSN = &GoodsSNService{client: c}
	c.GoodsBatch = &GoodsBatchService{client: c}
	c.GoodsPack = &GoodsPackService{client: c}
	c.StockinBase = &StockinBaseService{client: c}
	c.StockoutBase = &StockoutBaseService{client: c}
	c.ErrorCorrection = &ErrorCorrectionService{client: c}
	c.StockCost = &StockCostService{client: c}
	c.SettleTransfer = &SettleTransferService{client: c}
	c.SettleLogistics = &SettleLogisticsService{client: c}
	c.SettleOtherIn = &SettleOtherInService{client: c}
	c.StockoutCollect = &StockoutCollectService{client: c}
	c.StockinCollect = &StockinCollectService{client: c}
	c.StockinRefund = &StockinRefundService{client: c}
	c.PreStockin = &PreStockinService{client: c}
	c.SmartRefund = &SmartRefundService{client: c}
	c.RawRefund = &RawRefundService{client: c}
	c.Refund = &RefundService{client: c}
	c.System = &SystemService{client: c}
}
