// Code generated by scripts/gen_sdk.py from 旺店通旗舰版 API 文档; DO NOT EDIT.
// 重新生成：python scripts/gen_sdk.py

package wdt

import "context"

// StockSpecService 提供 wms.StockSpec.* 接口的封装。
type StockSpecService struct{ client *Client }

// StockPdService 提供 wms.StockPd.* 接口的封装。
type StockPdService struct{ client *Client }

// MoveOrderService 提供 wms.MoveOrder.* 接口的封装。
type MoveOrderService struct{ client *Client }

// StockinOtherService 提供 wms.stockin.Other.* 接口的封装。
type StockinOtherService struct{ client *Client }

// StockoutOtherService 提供 wms.stockout.Other.* 接口的封装。
type StockoutOtherService struct{ client *Client }

// StockoutOtherQueryService 提供 wms.stockout.OtherQuery.* 接口的封装。
type StockoutOtherQueryService struct{ client *Client }

// StockinTransferService 提供 wms.stockin.Transfer.* 接口的封装。
type StockinTransferService struct{ client *Client }

// StockoutTransferService 提供 wms.stockout.Transfer.* 接口的封装。
type StockoutTransferService struct{ client *Client }

// StockTransferService 提供 wms.stocktransfer.Manage.* 接口的封装。
type StockTransferService struct{ client *Client }

// StockTransferEditService 提供 wms.stocktransfer.Edit.* 接口的封装。
type StockTransferEditService struct{ client *Client }

// StockShelveService 提供 wms.StockShelve.* 接口的封装。
type StockShelveService struct{ client *Client }

// StockotherInService 提供 wms.stockother.In.* 接口的封装。
type StockotherInService struct{ client *Client }

// StockotherInQueryService 提供 wms.stockother.InQuery.* 接口的封装。
type StockotherInQueryService struct{ client *Client }

// StockotherOutService 提供 wms.stockother.Out.* 接口的封装。
type StockotherOutService struct{ client *Client }

// StockotherOutQueryService 提供 wms.stockother.OutQuery.* 接口的封装。
type StockotherOutQueryService struct{ client *Client }

// StockoutProcessService 提供 wms.stockout.Process.* 接口的封装。
type StockoutProcessService struct{ client *Client }

// StockinProcessService 提供 wms.stockin.Process.* 接口的封装。
type StockinProcessService struct{ client *Client }

// OuterOutService 提供 wms.outer.OuterOut.* 接口的封装。
type OuterOutService struct{ client *Client }

// OuterInService 提供 wms.outer.OuterIn.* 接口的封装。
type OuterInService struct{ client *Client }

// OuterTransferService 提供 wms.outer.OuterTransfer.* 接口的封装。
type OuterTransferService struct{ client *Client }

// DefectChangeService 提供 wms.stockdefect.DefectChange.* 接口的封装。
type DefectChangeService struct{ client *Client }

// SalesPickService 提供 wms.stockout.SalesPick.* 接口的封装。
type SalesPickService struct{ client *Client }

// PositionCapacityService 提供 wms.PositionCapacity.* 接口的封装。
type PositionCapacityService struct{ client *Client }

// PackService 提供 wms.stockout.Pack.* 接口的封装。
type PackService struct{ client *Client }

// StockinJitRefundService 提供 wms.stockin.JitRefund.* 接口的封装。
type StockinJitRefundService struct{ client *Client }

// StockoutJitOrderService 提供 wms.stockout.JitOrder.* 接口的封装。
type StockoutJitOrderService struct{ client *Client }

// GoodsSNService 提供 wms.GoodsSN.* 接口的封装。
type GoodsSNService struct{ client *Client }

// GoodsBatchService 提供 wms.GoodsBatch.* 接口的封装。
type GoodsBatchService struct{ client *Client }

// GoodsPackService 提供 wms.GoodsPack.* 接口的封装。
type GoodsPackService struct{ client *Client }

// StockinBaseService 提供 wms.stockin.Base.* 接口的封装。
type StockinBaseService struct{ client *Client }

// StockoutBaseService 提供 wms.stockout.Base.* 接口的封装。
type StockoutBaseService struct{ client *Client }

// ErrorCorrectionService 提供 wms.ErrorCorrection.* 接口的封装。
type ErrorCorrectionService struct{ client *Client }

// StockCostService 提供 finance.StockCost.* 接口的封装。
type StockCostService struct{ client *Client }

// SettleTransferService 提供 finance.settle.Transfer.* 接口的封装。
type SettleTransferService struct{ client *Client }

// SettleLogisticsService 提供 finance.settle.Logistics.* 接口的封装。
type SettleLogisticsService struct{ client *Client }

// SettleOtherInService 提供 finance.settle.OtherIn.* 接口的封装。
type SettleOtherInService struct{ client *Client }

// StockoutCollectService 提供 statistic.StockoutCollect.* 接口的封装。
type StockoutCollectService struct{ client *Client }

// StockinCollectService 提供 statistic.StockinCollect.* 接口的封装。
type StockinCollectService struct{ client *Client }

type StockSpecSearchParams struct {
	// 开始时间：开始时间(最后更新时间) , 传入商家编码时可传空值（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束时间(最后更新时间), 传入商家编码时可传空值（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 商家编码：商家编码列表（List<String>，选填）
	SpecNos []string `json:"spec_nos,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 掩码：1: 返回销量统计数据; 2: 返回成本价数据; 3:返回销售统计数据和成本价数据不传默认为0（Int，选填）
	Mask int `json:"mask,omitempty"`
	// 是否需要警戒相关信息：0：否1：是 （比较影响性能 慎用）不传默认为0（Int，选填）
	NeedAlarmInfo int `json:"need_alarm_info,omitempty"`
	// 状态：N 状态：0 未启用 1 启用 2 停用 注：1、不传，则默认全部。2、多个使用逗号拼接，例如 未启用+ 启用为：0,1（String，选填）
	Status string `json:"status,omitempty"`
}

type StockSpecSearch2Params struct {
	// 开始时间：开始时间(最后更新时间) , 传入商家编码时可传空值（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束时间(最后更新时间), 传入商家编码时可传空值（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 商家编码：商家编码列表（List<String>，选填）
	SpecNos []string `json:"spec_nos,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 掩码：1: 返回销量统计数据; 2: 返回成本价数据; 3:返回销售统计数据和成本价数据不传默认为0（Int，选填）
	Mask int `json:"mask,omitempty"`
	// 是否需要警戒相关信息：0：否1：是 （比较影响性能 慎用）不传默认为0（Int，选填）
	NeedAlarmInfo int `json:"need_alarm_info,omitempty"`
	// 状态：状态：0 未启用 1 启用 2 停用 注：1、不传，则默认全部。2、多个使用逗号拼接，例如 未启用+ 启用为：0,1（String，选填）
	Status string `json:"status,omitempty"`
}

type StockSpecQueryAvailableStockParams struct {
	// 开始时间：开始时间(最后更新时间)（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束时间(最后更新时间)（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 商家编码：商家编码，为空时时间段必填（String，选填）
	SpecNo string `json:"spec_no,omitempty"`
	// 货品编号：货品编号（String，选填）
	GoodsNo string `json:"goods_no,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
}

type StockSpecQueryChangeHistoryParams struct {
	// 开始时间：开始时间(最后更新时间)（String，必填）
	StartDate string `json:"start_date"`
	// 结束时间：结束时间(最后更新时间)（String，必填）
	EndDate string `json:"end_date"`
	// 商家编码：商家编码（String，选填）
	SpecNo string `json:"spec_no,omitempty"`
	// 类型：1.入库 2.出库 不传为出入库（Int，选填）
	Type int `json:"type,omitempty"`
	// 是否残次品：true：残次品；false：正品默认false只返回正品库存变化（boolean，选填）
	Defect bool `json:"defect,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
}

type StockSpecStockDetailSearchParams struct {
	// 主键id：库存管理主键id 取值来源：配合库存查询接口使用，库存查询接口返回的rec_id作为该接口的入参（Int，必填）
	StockSpecId int `json:"stock_spec_id"`
	// 主键id（批量）：库存管理主键id,多个用逗号隔开 例："1,2,3,4,5" 取值来源：配合库存查询接口使用，库存查询接口返回的rec_id作为该接口的入参（String，必填）
	StockSpecIdList string `json:"stock_spec_id_list"`
}

type StockPdStockSyncByPdPdOrder struct {
	// 仓库编号：仓库编号（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 正残次品处理方式：正残次品处理方式: 0 全部 1 只盘正品 2 只盘残品（Int，必填）
	DefectMode int `json:"defect_mode"`
	// 备注：备注，若无可为””（String，必填）
	Remark string `json:"remark"`
	// 是否严格模式：0：非严格模式1：严格模式（盘点单中某个单品不存在时会报错，单据创建失败）默认0（bool，选填）
	IsPostError bool `json:"is_post_error,omitempty"`
}

type StockPdStockSyncByPdSpec struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 备注：备注(盘点录入的备注)（String，必填）
	Remark string `json:"remark"`
	// 盘点数量：盘点数量（仅支持正数盘点）（String，必填）
	NewNum string `json:"new_num"`
	// 残次品：是否为残次品（Boolean，必填）
	Defect bool `json:"defect"`
}

type StockPdQueryStockPdParams struct {
	// 开始时间：开始时间，按照最后修改时间增量查询数据，yyyy-MM-dd HH:mm:ss格式（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间，上同开始时间（String，必填）
	EndTime string `json:"end_time"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 盘点单号：系统盘点单编号，默认PD开头（String，选填）
	PdNo string `json:"pd_no,omitempty"`
	// 商家编码：商家编码（String，选填）
	SpecNo string `json:"spec_no,omitempty"`
	// 货品编号：货品编号（String，选填）
	GoodsNo string `json:"goods_no,omitempty"`
	// 状态：不传默认获取全部10：已取消20：编辑中30：待盘点31：盘点中33：部分盘点35：待结算40：已完成（Int，选填）
	Status int `json:"status,omitempty"`
	// 制单人：制单人（员工编号）（String，选填）
	EmployeeNo string `json:"employee_no,omitempty"`
}

type StockPdQueryStockPdDetailParams struct {
	// 盘点单号：系统盘点单编号，默认PD开头（String，选填）
	PdNo string `json:"pd_no,omitempty"`
}

type StockPdQueryStockPdInDetailParams struct {
	// 开始时间：起始时间，若无入库单号或源单号，则为必填。（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间，上同开始时间（String，必填）
	EndTime string `json:"end_time"`
	// 时间类型：查询时间限制类型。1:最后修改时间2:审核时间默认1（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 入库单状态：英文逗号拼接的状态值: 10=已取消20=编辑中30=待审核37=待质检40=质检确认60=待结算70=暂估结算80=已完成（String，选填）
	Status string `json:"status,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 入库单号：入库单号（String，选填）
	StockinNo string `json:"stockin_no,omitempty"`
	// 盘点单号：盘点单号（String，选填）
	SrcOrderNo string `json:"src_order_no,omitempty"`
}

type StockPdQueryStockPdOutDetailParams struct {
	// 开始时间：起始时间，若无出库单号或源单号，则为必填。（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间，上同开始时间（String，必填）
	EndTime string `json:"end_time"`
	// 时间类型：查询时间限制类型。1:最后修改时间2:发货时间默认1（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 出库单号：出库单号（String，选填）
	StockoutNo string `json:"stockout_no,omitempty"`
	// 盘点单号：盘点单号（String，选填）
	SrcOrderNo string `json:"src_order_no,omitempty"`
	// 出库单状态：出库单状态: 50待审核90延时发货110已完成（String，选填）
	Status string `json:"status,omitempty"`
}

type MoveOrderQueryWithDetailParams struct {
	// 开始时间：开始时间(最后更新时间)（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束时间(最后更新时间)（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 商家编码：商家编码（String，选填）
	SpecNo string `json:"spec_no,omitempty"`
	// 移位单号：移位单号，不填则需要填写时间条件（String，选填）
	OrderNo string `json:"order_no,omitempty"`
	// 业务类型：0：移位1：采购入库上架2：补货上架3：销退上架4：拣货放回5：货位清点6：拣货下架7：货位调优8：清点处理9：货品归集10：其它入库上架11：补货下架12：补货放回15：其它下架16：其它上架17：销退质检上架18：补货暂存上架19：补货移位20：出库单驳回（Int，选填）
	Type int `json:"type,omitempty"`
	// 移位单状态：5:已取消,10:待审核,20:已审核（Int，选填）
	Status int `json:"status,omitempty"`
	// 仓库编号：仓库编号（String，必填）
	WarehouseNo string `json:"warehouse_no"`
}

type StockinOtherCreateOtherOrderStockinOrder struct {
	// 外部单号：外部单号，创建到ERP后最为入库单号展示（String，必填）
	OuterNo string `json:"outer_no"`
	// 业务单号：当不传入业务单号的情况下，自动创建业务单并关联（String，选填）
	SrcOrderNo string `json:"src_order_no,omitempty"`
	// 仓库编码：仓库编码（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 物流编号：物流编号（ERP系统物流编号）（String，选填）
	LogisticsCode string `json:"logistics_code,omitempty"`
	// 创建后的单据状态：0：待审核1：已审核2：编辑中默认0（Int，选填）
	IsCheck int `json:"is_check,omitempty"`
	// 入库原因：入库原因（ERP 系统预设的入库库原因标识。需在「设置 → 基本设置 → 原因列表」中提前维护，传入对应值）（String，选填）
	Reason string `json:"reason,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 自定义属性1：业务单自定义属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 自定义属性2：业务单自定义属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 自定义属性3：业务单自定义属性3（String，选填）
	Prop3 string `json:"prop3,omitempty"`
	// 自定义属性4：业务单自定义属性4（String，选填）
	Prop4 string `json:"prop4,omitempty"`
	// 自定义属性5：业务单自定义属性5（String，选填）
	Prop5 string `json:"prop5,omitempty"`
	// 自定义属性6：业务单自定义属性6（String，选填）
	Prop6 string `json:"prop6,omitempty"`
	// 货品详情：货品详情（List<Map<String, Object>>，必填）
	GoodsList []*StockinOtherCreateOtherOrderStockinOrderGoods `json:"goods_list"`
}

type StockinOtherCreateOtherOrderStockinOrderGoods struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 入库数量：入库数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 批次号：批次号（如果传入系统内不存在的批次信息, 将自动创建此批次信息）（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 货位编号：货位编号（String，选填）
	PositionNo string `json:"position_no,omitempty"`
	// 生产日期：生产日期（String，选填）
	ProductionDate string `json:"production_date,omitempty"`
	// 有效期：有效期（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// 残次品：残次品true：是false：否（bool，选填）
	Defect bool `json:"defect,omitempty"`
	// 入库价：不填取该货品在对应仓库下的实际成本或计划成本（以系统配置中的【系统运行成本价(实际成本)计算方式】为准）（Decimal(19,4)，选填）
	StockinPrice float64 `json:"stockin_price,omitempty"`
	// 序列号：序列号（序列号个数要与入库数量保持一致）（List<String>，选填）
	SnList []*StockinOtherCreateOtherOrderStockinOrderGoodsSn `json:"sn_list,omitempty"`
	// sn新列表：sn新列表sn_list和sn_new_list当存在序列号的情况下 有一个必传，sn_list优先级最高（List<Map<String, Object>>，选填）
	SnNewList []any `json:"sn_new_list,omitempty"`
}

type StockinOtherCreateOtherOrderStockinOrderGoodsSn struct {
	// 序列号：序列号（String，必填）
	SnNo string `json:"sn_no"`
	// 序列号集合码：序列号集合码（String，必填）
	SnSuiteNo string `json:"sn_suite_no"`
}

type StockinOtherQueryWithDetailParams struct {
	// 开始时间：起始修改时间，若无入库单号或源单号，则为必填。（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束修改时间，上同开始时间（String，必填）
	EndTime string `json:"end_time"`
	// 入库单状态：英文逗号拼接的状态值:10=已取消，20=编辑中，30=待审核/待处理，37=待质检 ，40=质检待确认，80=已完成（String，选填）
	Status string `json:"status,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 入库单号：入库单号（String，选填）
	StockinNo string `json:"stockin_no,omitempty"`
	// 其它入库业务单号：其它入库业务单号（String，选填）
	OtherStockinNo string `json:"other_stockin_no,omitempty"`
	// 入库原因：入库原因（String，选填）
	ReasonName string `json:"reason_name,omitempty"`
	// wms借调单号：wms借调单号（String，选填）
	WmsStockChangeNo string `json:"wms_stock_change_no,omitempty"`
}

type StockoutOtherCreateOtherStockoutOrder struct {
	// 外部单号：外部单号（创建成功后作为系统出库单号）（String，必填）
	OuterNo string `json:"outer_no"`
	// 业务单号：当不传入业务单号的情况下，自动创建业务单并关联（String，选填）
	SrcOrderNo string `json:"src_order_no,omitempty"`
	// 仓库编号：仓库编号（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 物流编号：物流编号（系统物流编号）（String，选填）
	LogisticsCode string `json:"logistics_code,omitempty"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 邮费：邮费（Decimal(19,4)，选填）
	PostFee float64 `json:"post_fee,omitempty"`
	// 创建后的单据状态：0：待审核1：已审核2：未确认默认0（Int，选填）
	IsCheck int `json:"is_check,omitempty"`
	// 出库原因：出库原因（ERP 系统预设的出库原因标识。需在「设置 → 基本设置 → 原因列表」中提前维护，传入对应值）（String，选填）
	Reason string `json:"reason,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 业务单自定义属性1：业务单自定义属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 业务单自定义属性2：业务单自定义属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 业务单自定义属性3：业务单自定义属性3（String，选填）
	Prop3 string `json:"prop3,omitempty"`
	// 业务单自定义属性4：业务单自定义属性4（String，选填）
	Prop4 string `json:"prop4,omitempty"`
	// 业务单自定义属性5：业务单自定义属性5（String，选填）
	Prop5 string `json:"prop5,omitempty"`
	// 业务单自定义属性6：业务单自定义属性6（String，选填）
	Prop6 string `json:"prop6,omitempty"`
	// 校验库存：0创建校验库存，1审核校验库存，默认1（int，选填）
	CreateCheckStock int `json:"create_check_stock,omitempty"`
	// 货品详情：货品详情（List<Map<String, Object>>，必填）
	GoodsList []*StockoutOtherCreateOtherStockoutOrderGoods `json:"goods_list"`
}

type StockoutOtherCreateOtherStockoutOrderGoods struct {
	// 单品信息：单品信息（String，必填）
	SpecNo string `json:"spec_no"`
	// 出库数量：出库数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 货位编号：货位编号（String，选填）
	PositionNo string `json:"position_no,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 批次号：批次号（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 生产日期：生产日期（String，选填）
	ProductionDate string `json:"production_date,omitempty"`
	// 有效期：有效期（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// 是否残次品：是：true否：false（bool，选填）
	Defect bool `json:"defect,omitempty"`
	// 是否开启序列号：0：不开启1：开启默认不开启（Int，选填）
	IsEnableSn int `json:"is_enable_sn,omitempty"`
	// 序列号列表：序列号列表，多个序列号用","分隔，例如："xxx1,xxx2,xxx3"，开启序列号后序列号数量要与出库数量保持一致（String，选填）
	SnList string `json:"sn_list,omitempty"`
}

type StockoutOtherQueryWithDetailParams struct {
	// 时间类型：1：发货时间；2：创建时间；3：最后修改时间不传默认为发货时间（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 开始时间：起始时间，若无出库单号或源单号，则为必填。（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间，上同开始时间.（String，必填）
	EndTime string `json:"end_time"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 业务单号：业务单号（String，选填）
	SrcOrderNo string `json:"src_order_no,omitempty"`
	// 出库单号：出库单号（String，选填）
	StockoutNo string `json:"stockout_no,omitempty"`
	// 业务单据状态：其他出库业务单据状态：1:编辑中;10:待审核;20:已审核;60:部分出库;65:待结算;70:已完成;80:已取消（Int，选填）
	Status int `json:"status,omitempty"`
	// 出库原因：出库原因（String，选填）
	ReasonName string `json:"reason_name,omitempty"`
}

type StockinTransferQueryWithDetailParams struct {
	// 开始时间：修改起始时间，若无入库单号或调拨单号，则为必填。（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：修改结束时间，上同开始时间（String，必填）
	EndTime string `json:"end_time"`
	// 入库单状态：英文逗号拼接的状态值: 10=已取消，20=编辑中，30=待审核，37=待质检，40=质检确认，80=已完成（String，选填）
	Status string `json:"status,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 入库单号：入库单号（String，选填）
	StockinNo string `json:"stockin_no,omitempty"`
	// 调拨单号：调拨单号（String，选填）
	TransferNo string `json:"transfer_no,omitempty"`
}

type StockinTransferCreateOrderOrderInfo struct {
	// 源调拨单号：源调拨单号（String，必填）
	SrcOrderNo string `json:"src_order_no"`
	// 调入仓库编码：调入仓库编码（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 物流编号：物流编号（系统物流编号）（String，选填）
	LogisticsCode string `json:"logistics_code,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 创建后的单据状态：0：待审核1：已审核2：编辑中默认0（Int，选填）
	IsCheck int `json:"is_check,omitempty"`
	// 是否创建批次：true：创建false：不创建默认不创建（boolean，选填）
	IsCreateBatch bool `json:"is_create_batch,omitempty"`
}

type StockinTransferCreateOrderDetail struct {
	// 单品信息：单品信息（String，必填）
	SpecNo string `json:"spec_no"`
	// 调拨数量：调拨数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 基本单位：基本单位，不传默认为调拨单明细对应货品的基本单位（String，选填）
	UnitName string `json:"unit_name,omitempty"`
	// 调入货位：调入货位，不传默认取调拨单中设置的入库货位，如果有多个相同货品随机取一条明细填充信息（String，选填）
	PositionNo string `json:"position_no,omitempty"`
	// 批次号：批次号，不传默认取调拨单中设置的批次号，如果有多个相同货品随机取一条明细填充信息（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 有效期：有效期，不传默认取调拨单中设置的有效期，如果有多个相同货品随机取一条明细填充信息（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// 残次品：true：残次品false：正品（Bool，选填）
	Defect bool `json:"defect,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 是否开启序列号：0：不开启1：开启默认不开启（Int，选填）
	IsEnableSn int `json:"is_enable_sn,omitempty"`
	// 序列号列表：序列号列表，多个序列号用","分隔，例如："xxx1,xxx2,xxx3"，开启序列号后序列号数量要与出库数量保持一致（String，选填）
	SnList string `json:"sn_list,omitempty"`
}

type StockoutTransferQueryWithDetailParams struct {
	// 开始时间：按照发货时间返回，若无出库单号或调拨单号，则为必填。（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：按照发货时间返回，上同开始时间（String，必填）
	EndTime string `json:"end_time"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 调拨单号：调拨单号（String，选填）
	SrcOrderNo string `json:"src_order_no,omitempty"`
	// 出库单号：出库单号（String，选填）
	StockoutNo string `json:"stockout_no,omitempty"`
	// 是否按照货位分组：0: 否不传也为否（Int，选填）
	Position int `json:"position,omitempty"`
	// 出库单状态：由逗号隔开的整数字符串出库单状态: 5已取消 48 未确认 50 待审核77 拣货中110已完成（String，选填）
	Status string `json:"status,omitempty"`
}

type StockoutTransferCreateOrderOrderInfo struct {
	// 源调拨单号：源调拨单号（String，必填）
	SrcOrderNo string `json:"src_order_no"`
	// 调出仓库编号：调出仓库编号（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 物流编号：物流编号（系统物流公司编号）（String，选填）
	LogisticsCode string `json:"logistics_code,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 创建后的单据状态：0：待审核1：已审核2：未确认默认0（Int，选填）
	IsCheck int `json:"is_check,omitempty"`
}

type StockoutTransferCreateOrderDetail struct {
	// 单品信息：单品信息（String，必填）
	SpecNo string `json:"spec_no"`
	// 调拨数量：调拨数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 基本单位：基本单位（String，选填）
	UnitName string `json:"unit_name,omitempty"`
	// 调出货位：调出货位，不传取系统配置的默认货位（String，选填）
	PositionNo string `json:"position_no,omitempty"`
	// 批次号：批次号，不传随机匹配调拨单中的批次信息（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 有效期：有效期，不传随机匹配调拨单中的有效期（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// 残次品：true：残次品false：正品（Bool，选填）
	Defect bool `json:"defect,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 是否开启序列号：0：不开启1：开启默认不开启（Int，选填）
	IsEnableSn int `json:"is_enable_sn,omitempty"`
	// 序列号列表：序列号列表，多个序列号用","分隔，例如："xxx1,xxx2,xxx3"，开启序列号后序列号数量要与出库数量保持一致（String，选填）
	SnList string `json:"sn_list,omitempty"`
}

type StockTransferQueryWithDetailParams struct {
	// 开始时间：最后修改时间（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：最后修改时间（String，必填）
	EndTime string `json:"end_time"`
	// 源仓库编号：源仓库编号（String，选填）
	FromWarehouseNo string `json:"from_warehouse_no,omitempty"`
	// 目标仓库编号：目标仓库编号（String，选填）
	ToWarehouseNo string `json:"to_warehouse_no,omitempty"`
	// 调拨单号：调拨单号（String，选填）
	TransferNo string `json:"transfer_no,omitempty"`
	// 调拨单状态：10：已取消20：编辑中30：待审核40：已审核50：调拨中80：待结算90：调拨完成多个状态之间使用英文逗号分隔（String，选填）
	Status string `json:"status,omitempty"`
	// 模糊查询：默认false,业务单号进行模糊查询匹配，匹配数量大于1条时会报错（boolean，选填）
	FuzzyQuery bool `json:"fuzzy_query,omitempty"`
}

type StockTransferEditCreateOrderOrderInfo struct {
	// 外部单号：调拨单号（支持不传，不传此参数按照旺店通系统单号生成逻辑在系统生成调拨单号信息）（String，必填）
	OuterNo string `json:"outer_no"`
	// 调出仓库：调出仓库（String，必填）
	FromWarehouseNo string `json:"from_warehouse_no"`
	// 调入仓库：调入仓库（String，必填）
	ToWarehouseNo string `json:"to_warehouse_no"`
	// 调拨类型：调拨类型：0：单品调拨1：货位调拨2：明细调拨5：单品调拨(出+入)6：货位调拨(出+入)7：明细调拨(出+入)分步调拨使用类型：0,1,2；快速调拨使用类型：5,6,7（Int，必填）
	Mode int `json:"mode"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 目标仓联系人：目标仓联系人（String，选填）
	Contact string `json:"contact,omitempty"`
	// 联系电话：联系电话（String，选填）
	Telno string `json:"telno,omitempty"`
	// 目标仓省份：目标仓省份，不校验是否与系统地址库匹配（String，选填）
	Province string `json:"province,omitempty"`
	// 目标仓城市：目标仓城市，不校验是否与系统地址库匹配（String，选填）
	City string `json:"city,omitempty"`
	// 目标仓地区：目标仓地区，不校验是否与系统地址库匹配（String，选填）
	District string `json:"district,omitempty"`
	// 目标仓地址：目标仓地址，不校验是否与系统地址库匹配（String，选填）
	Address string `json:"address,omitempty"`
	// 物流公司编号：物流公司编号，设置-基本设置-物流界面查看（String，选填）
	LogisticsCompanyNo string `json:"logistics_company_no,omitempty"`
	// 自定义属性1：调拨单自定义属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 自定义属性2：调拨单自定义属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 自定义属性3：调拨单自定义属性3（String，选填）
	Prop3 string `json:"prop3,omitempty"`
	// 自定义属性4：调拨单自定义属性4（String，选填）
	Prop4 string `json:"prop4,omitempty"`
}

type StockTransferEditCreateOrderDetail struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 调拨数量：调拨数量，若调拨数量小于可用库存数量会提示报错（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 调出货位：调出货位（String，选填）
	FromPositionNo string `json:"from_position_no,omitempty"`
	// 调入货位：调入货位（String，选填）
	ToPositionNo string `json:"to_position_no,omitempty"`
	// 批次号：批次号，mode=2或者7，才有效（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 有效期：有效期，mode=2或者7，才有效（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// 是否残次品：是否残次品残次品：true正品：false（bool，选填）
	Defect bool `json:"defect,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
}

type StockShelveQueryWithDetailParams struct {
	// 开始时间：开始时间(最后更新时间)（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束时间(最后更新时间)（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 商家编码：商家编码（String，选填）
	SpecNo string `json:"spec_no,omitempty"`
	// 补货单号：补货单号（String，选填）
	OrderNo string `json:"order_no,omitempty"`
	// 仓库编号：仓库编号（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 类型：0通用，1下架，2上架，3预补（Int，选填）
	Type int `json:"type,omitempty"`
}

type StockotherInPushOrder struct {
	// 仓库编号：仓库编号（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 物流公司编号：ERP系统内自行维护的物流公司的编号（String，选填）
	LogisticsCode string `json:"logistics_code,omitempty"`
	// 入库原因：入库原因 (ERP 系统预设的入库原因标识。需在「设置 → 基本设置 → 原因列表」中提前维护，传入对应值)（String，选填）
	Reason string `json:"reason,omitempty"`
	// 标记名称：标记名称（String，选填）
	FlagName string `json:"flag_name,omitempty"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 其它入库业务单属性1：其他入库业务单属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 其它入库业务单属性2：其他入库业务单属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 其它入库业务单属性3：其他入库业务单属性3（String，选填）
	Prop3 string `json:"prop3,omitempty"`
	// 其它入库业务单属性4：其他入库业务单属性4（String，选填）
	Prop4 string `json:"prop4,omitempty"`
	// 其它入库业务单属性5：其他入库业务单属性5（String，选填）
	Prop5 string `json:"prop5,omitempty"`
	// 其它入库业务单属性6：其他入库业务单属性6（String，选填）
	Prop6 string `json:"prop6,omitempty"`
	// 外部单号：传入外部单号则使用外部单号作为系统内业务单号（String，选填）
	OuterNo string `json:"outer_no,omitempty"`
	// 是否审核：审核传入true,不传默认false,传入false则创建的业务单为待审核状态（boolean，选填）
	IsCheck bool `json:"is_check,omitempty"`
	// 制单人：制单人 (员工昵称)，如果制单人不存在默认为接口appkey（String，选填）
	CreatorName string `json:"creator_name,omitempty"`
}

type StockotherInPushOrderDetails struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 数量：数量（Int，必填）
	Num int `json:"num"`
	// 货位：货位（String，选填）
	PositionNo string `json:"position_no,omitempty"`
	// 批次：批次，支持传入并创建ERP内不存在的批次信息（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 有效期：有效期（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// 生产日期：生产日期yyyy-MM-dd例： 2024-09-01（String，选填）
	ProductionDate string `json:"production_date,omitempty"`
	// 是否残次品：默认false（boolean，选填）
	Defect bool `json:"defect,omitempty"`
	// 辅助单位：基本单位取值：优先取单品，单品无则取货品基本单位，辅助单位需要和基本单位有匹配关系（String，选填）
	AuxUnitName string `json:"aux_unit_name,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 入库价：入库价（Decimal(19,4)，选填）
	Price float64 `json:"price,omitempty"`
}

type StockotherInQueryWithDetailParams struct {
	// 时间类型：1：创建时间；2：最后修改时间不传默认为创建时间（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 开始时间：起始时间，若无业务单号，则为必填。yyyy-MM-dd HH:mm:ss格式（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间，上同开始时间.（String，必填）
	EndTime string `json:"end_time"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 业务单号：业务单号（String，选填）
	OtherInNo string `json:"other_in_no,omitempty"`
	// 业务单据状态：业务单据状态：1:编辑中;10:待审核;20:已审核;40:已推送wms;60:部分入库65:待结算;70:已完成;80:已取消（string，选填）
	Status string `json:"status,omitempty"`
	// 模糊查询：默认false,业务单号模糊查询匹配，匹配数量大于1条时会报错（boolean，选填）
	FuzzyQuery bool `json:"fuzzy_query,omitempty"`
}

type StockotherOutPushOrder struct {
	// 仓库编号：仓库编号（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 物流公司编号：ERP系统内自行维护的物流公司的编号（String，选填）
	LogisticsCode string `json:"logistics_code,omitempty"`
	// 出库原因：出库原因（ERP 系统预设的出库原因标识。需在「设置 → 基本设置 → 原因列表」中提前维护，传入对应值）（String，选填）
	Reason string `json:"reason,omitempty"`
	// 标记名称：标记名称（String，选填）
	FlagName string `json:"flag_name,omitempty"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 收件人姓名：收件人姓名（外部仓库必须传入该字段）（String，选填）
	ReceiverName string `json:"receiver_name,omitempty"`
	// 收件人手机：收件人手机（外部仓库必须传入该字段）（String，选填）
	ReceiverMobile string `json:"receiver_mobile,omitempty"`
	// 省：省（外部仓库必须传入该字段）（String，选填）
	ReceiverProvince string `json:"receiver_province,omitempty"`
	// 市：市（外部仓库必须传入该字段）（String，选填）
	ReceiverCity string `json:"receiver_city,omitempty"`
	// 区：区（外部仓库必须传入该字段）（String，选填）
	ReceiverDistrict string `json:"receiver_district,omitempty"`
	// 地址：地址（外部仓库必须传入该字段）（String，选填）
	ReceiverAddress string `json:"receiver_address,omitempty"`
	// 其它出库业务单属性1：其它出库业务单属性1（String，选填）
	Prop1 string `json:"prop1,omitempty"`
	// 其它出库业务单属性2：其它出库业务单属性2（String，选填）
	Prop2 string `json:"prop2,omitempty"`
	// 其它出库业务单属性3：其它出库业务单属性3（String，选填）
	Prop3 string `json:"prop3,omitempty"`
	// 其它出库业务单属性4：其它出库业务单属性4（String，选填）
	Prop4 string `json:"prop4,omitempty"`
	// 其它出库业务单属性5：其它出库业务单属性5（String，选填）
	Prop5 string `json:"prop5,omitempty"`
	// 其它出库业务单属性6：其它出库业务单属性6（String，选填）
	Prop6 string `json:"prop6,omitempty"`
	// 外部单号：传入外部单号则使用外部单号作为系统内业务单号（String，选填）
	OuterNo string `json:"outer_no,omitempty"`
	// 是否审核：审核传入true,不传默认false,传入false则创建的业务单为待审核状态（boolean，选填）
	IsCheck bool `json:"is_check,omitempty"`
	// 创建单据时校验库存：0：创建单据时校验可用库存1：审核单据时校验可用库存默认1（Integer，选填）
	CreateCheckStock int `json:"create_check_stock,omitempty"`
}

type StockotherOutPushOrderDetails struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 数量：数量（Int，必填）
	Num int `json:"num"`
	// 货位：货位（String，选填）
	PositionNo string `json:"position_no,omitempty"`
	// 批次：批次（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 有效期：有效期（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// 生产日期：生产日期yyyy-MM-dd例： 2024-09-01（String，选填）
	ProductionDate string `json:"production_date,omitempty"`
	// 是否残次品：默认false（boolean，选填）
	Defect bool `json:"defect,omitempty"`
	// 辅助单位名称：基本单位取值：优先取单品，单品无则取货品基本单位，辅助单位需要和基本单位有匹配关系（String，选填）
	AuxUnitName string `json:"aux_unit_name,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
}

type StockotherOutQueryWithDetailParams struct {
	// 时间类型：1：创建时间；2：最后修改时间不传默认为创建时间（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 开始时间：起始时间，若无业务单号，则为必填。yyyy-MM-dd HH:mm:ss格式（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间，上同开始时间.（String，必填）
	EndTime string `json:"end_time"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 业务单号：业务单号（String，选填）
	OtherOutNo string `json:"other_out_no,omitempty"`
	// 业务单据状态：业务单据状态：1:编辑中;10:待审核;20:已审核;40:已推送wms;60:部分出库;65:待结算;70:已完成;80:已取消（string，选填）
	Status string `json:"status,omitempty"`
	// 模糊查询：默认false,业务单号进行模糊查询匹配，匹配数量大于1条时会报错（boolean，选填）
	FuzzyQuery bool `json:"fuzzy_query,omitempty"`
}

type StockoutProcessQueryWithDetailParams struct {
	// 开始时间：起始时间，若无出库单编码或生产单编码，则为必填。（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间，上同开始时间（String，必填）
	EndTime string `json:"end_time"`
	// 时间类型：时间判断的类型，1为建单时间，2为出库时间，3为最后修改时间默认为建单时间（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 出库单号：出库单号（String，选填）
	StockoutNo string `json:"stockout_no,omitempty"`
	// 生产单号：生产单号（String，选填）
	ProcessNo string `json:"process_no,omitempty"`
	// 出库单状态：出库单状态：5: 已取消48: 未确认50: 待审核77: 拣货中110: 已完成用逗号分隔开数字的分隔符（String，选填）
	Status string `json:"status,omitempty"`
}

type StockinProcessQueryWithDetailParams struct {
	// 开始时间：起始时间，若无入库单编码或生产单编码，则为必填。（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间，上同开始时间（String，必填）
	EndTime string `json:"end_time"`
	// 时间类型：时间判断的类型，1为建单时间，2为审核时间，3为最后修改时间默认为建单时间（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 入库单号：入库单号（String，选填）
	StockinNo string `json:"stockin_no,omitempty"`
	// 生产单号：生产单号（String，选填）
	ProcessNo string `json:"process_no,omitempty"`
	// 入库单状态：入库单状态10: 已取消20: 编辑中30: 待审核37: 待质检40: 质检待确认80: 已完成用逗号分隔开数字的分隔符（String，选填）
	Status string `json:"status,omitempty"`
}

type OuterOutCreateOrderOrder struct {
	// 仓库编号：仓库编号（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 外部单号：传入外部单号则使用外部单号作为系统内业务单号（String，选填）
	OrderNo string `json:"order_no,omitempty"`
	// 源单类型：0:调整出库，2:调拨出库，14:采购退货出库（Int，选填）
	SrcOrderType int `json:"src_order_type,omitempty"`
	// 源单号：源单类型为2和14需传源单号（String，选填）
	SrcOrderNo string `json:"src_order_no,omitempty"`
	// 出库原因：出库原因（String，选填）
	Reason string `json:"reason,omitempty"`
}

type OuterOutCreateOrderOrderDetails struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 数量：数量（Int，必填）
	Num int `json:"num"`
	// 辅助单位：辅助单位（String，选填）
	AuxUnitName string `json:"aux_unit_name,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 是否残次品：默认false（boolean，选填）
	Defect bool `json:"defect,omitempty"`
	// 批次编号：批次编号若不在会自动创建（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 有效期：有效期（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// 是否开启序列号：0：不开启1：开启默认不开启（Int，选填）
	IsEnableSn int `json:"is_enable_sn,omitempty"`
	// 序列号列表：序列号列表，多个序列号用","分隔，例如："xxx1,xxx2,xxx3"，开启序列号后序列号数量要与出库数量保持一致（String，选填）
	SnList string `json:"sn_list,omitempty"`
}

type OuterOutQueryWithDetailParams struct {
	// 出库单号：出库单号（String，必填）
	OuterOutNo string `json:"outer_out_no"`
	// 仓库编号：出库仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 开始时间：起始时间，若无出库单编号，则为必填。（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间，上同开始时间（String，必填）
	EndTime string `json:"end_time"`
	// 时间类型：时间判断的类型，1为建单时间，2为修改时间，默认为建单时间（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 出库类型：出库类型0，调整出库2，调拨出库4，盘点出库14，采购退货出库（Int，选填）
	OrderType int `json:"order_type,omitempty"`
	// 状态：用逗号分隔开数字的字符串，状态码10，已取消20，编辑中30，待审核40，待结算50，已完成（String，选填）
	Status string `json:"status,omitempty"`
}

type OuterInCreateOrderOrder struct {
	// 仓库编号：仓库编号（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 外部单号：传入外部单号则使用外部单号作为系统内业务单号（String，选填）
	OrderNo string `json:"order_no,omitempty"`
	// 源单类型：0:调整入库，2:调拨入库，10:采购入库 12:退货入库（Int，选填）
	SrcOrderType int `json:"src_order_type,omitempty"`
	// 源单号：源单类型为2、10、12需传源单号（String，选填）
	SrcOrderNo string `json:"src_order_no,omitempty"`
	// 入库原因：入库原因（String，选填）
	Reason string `json:"reason,omitempty"`
}

type OuterInCreateOrderOrderDetails struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 数量：数量（int，必填）
	Num int `json:"num"`
	// 辅助单位：辅助单位（String，选填）
	AuxUnitName string `json:"aux_unit_name,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 是否残次品：默认false（boolean，选填）
	Defect bool `json:"defect,omitempty"`
	// 批次编号：批次编号若不存在自动创建（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 有效期：有效期（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// 是否开启序列号：0：不开启1：开启默认不开启（Int，选填）
	IsEnableSn int `json:"is_enable_sn,omitempty"`
	// 序列号列表：序列号列表，多个序列号用","分隔，例如："xxx1,xxx2,xxx3"，开启序列号后序列号数量要与出库数量保持一致（String，选填）
	SnList string `json:"sn_list,omitempty"`
	// 辅助序列号信息：序列号和辅助序列号之间的对应关系,有辅助序列号的情况下需要传该字段（list<Sninfo>，选填）
	SnInfos []*OuterInCreateOrderOrderDetailsSn `json:"sn_infos,omitempty"`
}

type OuterInCreateOrderOrderDetailsSn struct {
	// 序列号：序列号（String，选填）
	Sn string `json:"sn,omitempty"`
	// 辅助序列号：辅助序列号（String，选填）
	SecondSn string `json:"second_sn,omitempty"`
}

type OuterInQueryWithDetailParams struct {
	// 入库单号：入库单号（String，选填）
	OuterInNo string `json:"outer_in_no,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 开始时间：起始时间，若无入库单编号，则为必填。（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间，上同开始时间（String，必填）
	EndTime string `json:"end_time"`
	// 时间类型：时间判断的类型，1为建单时间，2为修改时间，默认为建单时间（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 入库类型：入库类型0:调整入库2:调拨入库4:盘点入库10:采购入库12:退货入库（Int，选填）
	SrcOrderType int `json:"src_order_type,omitempty"`
	// 状态：用逗号分隔开数字的字符串，状态码10，已取消20，编辑中30，待审核40，待结算50，已完成（String，选填）
	Status string `json:"status,omitempty"`
}

type OuterTransferCreateByApiParams struct {
	// 创建模式：0：保存1：提交2：快速审核默认0（Int，选填）
	CreateMode int `json:"create_mode,omitempty"`
	// 调出仓库：调出仓库（String，必填）
	FromWarehouseNo string `json:"from_warehouse_no"`
	// 调入仓库：调入仓库（String，必填）
	ToWarehouseNo string `json:"to_warehouse_no"`
	// 执行wms借调单编辑中状态：0：否1：是默认0（Int，选填）
	WmsEdit int `json:"wms_edit,omitempty"`
	// 调拨方案：1：外仓单品调拨（出+入）2：外仓明细调拨（出+入）3：外仓单品调拨（出+入+接口）4：外仓明细调拨（出+入+接口）（Int，必填）
	Mode int `json:"mode"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
}

type OuterTransferCreateByApiDetail struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 调拨数量：调拨数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 批次号：批次号 mode=2/4有效（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 有效期：有效期 mode=2/4有效（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// 是否残次品：是否残次品0：否1：是（Int，选填）
	Defect int `json:"defect,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
}

type DefectChangeSearchParams struct {
	// 开始时间：起始时间，最后修改时间（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：最后修改时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 转换单号：转换单号（String，选填）
	ChangeNo string `json:"change_no,omitempty"`
	// 转换状态：10:已取消 20:编辑中 30: 待审核 40:已审核 45:待结算 50: 已完成（Byte，选填）
	Status int `json:"status,omitempty"`
	// 转换类型：true:残转正；false: 正转残（Boolean，选填）
	Type bool `json:"type,omitempty"`
}

type PositionCapacitySearchParams struct {
	// 开始时间：开始时间，最后修改时间（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束时间，最后修改时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 仓库编号：仓库编号（时间不传的情况下，仓库编号必传）（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 商家编码：商家编码（时间不传的情况下，商家编码必传）（String，选填）
	SpecNo string `json:"spec_no,omitempty"`
	// 货品编号：货品编号（String，选填）
	GoodsNo string `json:"goods_no,omitempty"`
}

type PackSearchParams struct {
	// 开始时间：最后修改时间, yyyy-MM-dd HH:mm:ss格式当出库单号和物流单号未传的情况下，时间条件必传（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：yyyy-MM-dd HH:mm:ss格式（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 单据类型：单据类型1：销售出库2：调拨出库4：盘库出库5：生产出库14：采购退货出库21：其它出库不传默认1（Byte，选填）
	SrcOrderType int `json:"src_order_type,omitempty"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 出库单号：出库单号（String，选填）
	StockoutNo string `json:"stockout_no,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
}

type StockinJitRefundSearchOrderWithDetailParams struct {
	// 开始时间：起始时间, yyyy-MM-dd HH:mm:ss格式（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间, yyyy-MM-dd HH:mm:ss格式（String，必填）
	EndTime string `json:"end_time"`
}

type StockoutJitOrderSearchParams struct {
	// 开始时间：起始时间, yyyy-MM-dd HH:mm:ss格式（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间, yyyy-MM-dd HH:mm:ss格式（String，必填）
	EndTime string `json:"end_time"`
}

type GoodsSNQueryWithDetailParams struct {
	// 开始时间：sn创建开始时间（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：sn创建结束时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 时间类型：0：创建时间1：更新时间默认0（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 单据类型：0：出库单1：入库单默认0（Byte，选填）
	OrderType int `json:"order_type,omitempty"`
	// 源单据类型：源单据类型1：销售出库2：调拨出库/调拨入库5：生产出库/生产原料入库6：生产入库10：采购入库12：退货入库14：采购退货出库20：其他入库21：其他出库（Byte，选填）
	SrcOrderType int `json:"src_order_type,omitempty"`
	// 序列号：序列号，传入该字段可以不传起止时间 （1.6.2.0版本及以上支持批量查询，多个sn之间用英文逗号隔开）（String，选填）
	Sn string `json:"sn,omitempty"`
	// 出入库单号：出入库单号，传入该字段可以不传起止时间（String，选填）
	OrderNo string `json:"order_no,omitempty"`
	// 商家编码：商家编码（String，选填）
	SpecNo string `json:"spec_no,omitempty"`
	// 状态：10：初始录入15：二次录入20：已入库30：已占用40：已出库（Int，选填）
	Status int `json:"status,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 辅助序列号：辅助序列号（String，选填）
	SecondSn string `json:"second_sn,omitempty"`
}

type GoodsBatchCreateByApiItem struct {
	// 批次号：批次号（String，必填）
	BatchNo string `json:"batch_no"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
}

type GoodsPackUploadParams struct {
	// 仓库编号：仓库编号（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 商家编码：商家编码（String，必填）
	SrcSpecNo string `json:"src_spec_no"`
	// 数量：数量（BigDecimal(19,4)，必填）
	Num float64 `json:"num"`
	// 状态：状态0：未入库2：已入库（byte，必填）
	Status int `json:"status"`
	// 箱码：箱码（不传值则自动生成）（String，选填）
	PackBarcode string `json:"pack_barcode,omitempty"`
	// 批次号：批次号（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 有效期：有效期（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
}

type StockinBaseSearchParams struct {
	// 开始时间：修改时间，时间格式 YYYY-MM-DD HH:MM:SS（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：修改时间，时间格式 YYYY-MM-DD HH:MM:SS（String，必填）
	EndTime string `json:"end_time"`
	// 单据类型：2：调拨4：盘点5：生产原料6：生产成品8：正残转换10：采购单13：jit退货入库20：其它入库23：外仓调整入库33：初始化入库80：借货入库（Byte，选填）
	OrderType int `json:"order_type,omitempty"`
	// 状态：10：已取消20：编辑中30：待审核37：待质检40：质检确认80：已完成（Byte，选填）
	Status int `json:"status,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 源单号：源单号（String，选填）
	SrcOrderNo string `json:"src_order_no,omitempty"`
	// 入库单号：入库单号（String，选填）
	StockinNo string `json:"stockin_no,omitempty"`
}

type StockoutBaseSearchParams struct {
	// 开始时间：修改时间，时间格式 YYYY-MM-DD HH:MM:SS（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：修改时间，时间格式 YYYY-MM-DD HH:MM:SS（String，必填）
	EndTime string `json:"end_time"`
	// 单据类型：2：调拨出库4：盘点出库5：生产出库8：正残转换出库9：jit出库14：采购退货21：其它出库24：外仓调整出库34：初始化出库80：借货出库（Byte，选填）
	OrderType int `json:"order_type,omitempty"`
	// 状态：5：已取消10：待放回48：未确认50：待审核51：缺货53：wms已接单54：获取面单58：档口锁定60：待分配61：排队中63：待补货65：待处理70：待发货73：爆款锁定75：待拣货77：拣货中79：已拣货90：延时发货110：已完成（Byte，选填）
	Status int `json:"status,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 源单号：源单号（String，选填）
	SrcOrderNo string `json:"src_order_no,omitempty"`
	// 出库单号：出库单号，传入单号可不传时间（String，选填）
	StockoutNo string `json:"stockout_no,omitempty"`
}

type StockinBaseSearchSNParams struct {
	// 开始时间：入库SN记录创建的时间yyyy-MM-dd HH:mm:ss格式（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：入库SN记录创建的时间yyyy-MM-dd HH:mm:ss格式（String，必填）
	EndTime string `json:"end_time"`
	// 入库单号：入库单号（String，选填）
	StockinNo string `json:"stockin_no,omitempty"`
}

type StockoutBaseSearchSNParams struct {
	// 开始时间：出库SN记录创建的时间yyyy-MM-dd HH:mm:ss格式（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：出库SN记录创建的时间yyyy-MM-dd HH:mm:ss格式（String，必填）
	EndTime string `json:"end_time"`
	// 出库单号：出库单号（String，选填）
	StockoutNo string `json:"stockout_no,omitempty"`
}

type StockinBaseUploadSNParams struct {
	// 入库单号：入库单号（String，必填）
	StockinNo string `json:"stockin_no"`
	// 单据类型：2：调拨入库6：生产成品入库20：其他入库（byte，必填）
	OrderType int `json:"order_type"`
}

type StockinBaseUploadSNDetail struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 是否残次品：默认false（boolean，选填）
	Defect bool `json:"defect,omitempty"`
	// 批次编号：批次编号（String，选填）
	BatchNo string `json:"batch_no,omitempty"`
	// 生产日期：生产日期（String，选填）
	ProductionDate string `json:"production_date,omitempty"`
	// 有效期：有效期（String，选填）
	ExpireDate string `json:"expire_date,omitempty"`
	// sn列表：sn列表（List<String>，必填）
	SnList []*StockinBaseUploadSNDetailSn `json:"sn_list"`
	// sn新列表：sn新列表sn_list和sn_new_list中有一个必传，同时传sn_list优先级高于sn_new_list（List<Map<String,Object>>，必填）
	SnNewList []any `json:"sn_new_list"`
}

type StockinBaseUploadSNDetailSn struct {
	// 序列号：序列号（String，必填）
	SnNo string `json:"sn_no"`
	// 序列号集合码：序列号集合码（String，必填）
	SnSuiteNo string `json:"sn_suite_no"`
}

type StockoutBaseUploadSNParams struct {
	// 出库单号：出库单号（String，必填）
	StockoutNo string `json:"stockout_no"`
	// 单据类型：2：调拨出库5：生产原料出库14：采购退货出库21：其他出库（byte，必填）
	OrderType int `json:"order_type"`
}

type StockoutBaseUploadSNDetail struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 是否残次品：默认false（boolean，选填）
	Defect bool `json:"defect,omitempty"`
	// sn列表：sn列表（List<String>，必填）
	SnList []string `json:"sn_list"`
}

type ErrorCorrectionQueryWithDetailParams struct {
	// 开始时间：纠错单修改时间格式：yyyy-MM-dd HH:mm:ss（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：纠错单修改时间格式：yyyy-MM-dd HH:mm:ss（String，必填）
	EndTime string `json:"end_time"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 纠错类型：1:采购入库纠错（tinyint，选填）
	Type int `json:"type,omitempty"`
	// 纠错单号：传纠错单号的情况下，时间非必传（String，选填）
	CorrectionNo string `json:"correction_no,omitempty"`
	// 源单号：源单号（String，选填）
	SrcOrderNo string `json:"src_order_no,omitempty"`
}

type StockCostSearchParams struct {
	// 开始时间：起始修改时间，若无仓库编号或商家编码，则为必填。（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束修改时间，上同开始时间（String，必填）
	EndTime string `json:"end_time"`
	// 仓库编码：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 商家编码：多个商家编码使用英文逗号分隔（String，选填）
	SpecNos string `json:"spec_nos,omitempty"`
}

type SettleTransferSearchParams struct {
	// 源仓库编号：源仓库编号（String，选填）
	FromWarehouseNo string `json:"from_warehouse_no,omitempty"`
	// 目标仓库编号：目标仓库编号（String，选填）
	ToWarehouseNo string `json:"to_warehouse_no,omitempty"`
	// 结算单号：结算单号 （按结算单号查询可不传时间参数）（String，选填）
	SettleNo string `json:"settle_no,omitempty"`
	// 调拨单号：调拨单号 （按调拨单号查询可不传时间参数）（String，选填）
	TransferNo string `json:"transfer_no,omitempty"`
	// 结算单状态：10:编辑中,20:待审核,30:已审核,40 已取消.不传默认显示全部.传入多个状态时使用英文逗号分隔（String，选填）
	Status string `json:"status,omitempty"`
	// 开始时间：开始时间，默认创建时间（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间，默认创建时间（String，必填）
	EndTime string `json:"end_time"`
	// 时间类型：时间类型0：创建时间1：修改时间默认0（Int，选填）
	TimeType int `json:"time_type,omitempty"`
}

type SettleLogisticsSearchParams struct {
	// 开始时间：最后修改时间（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：最后修改时间（String，必填）
	EndTime string `json:"end_time"`
	// 状态：0:待分配1:已分配2:已完成4:回收失败5:待回收6:已回收8:手工作废（Short，选填）
	Status int `json:"status,omitempty"`
}

type SettleOtherInUploadOrder struct {
	// 其它入库业务单号：其它入库业务单号（String，必填）
	OtherInNo string `json:"other_in_no"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 物流公司编号：ERP内手动维护的物流公司编号（String，选填）
	LogisticsCompanyNo string `json:"logistics_company_no,omitempty"`
	// 运费：运费（Decimal(19,4)，选填）
	PostFee float64 `json:"post_fee,omitempty"`
	// 供应商编号：填写供应商的情况下会校验供应商权限（String，选填）
	ProviderNo string `json:"provider_no,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 是否审核：默认false,审核失败情况下单据会创建失败（boolean，选填）
	IsCheck bool `json:"is_check,omitempty"`
	// 模糊查询：默认false,业务单号进行模糊查询匹配，匹配数量大于1条时会报错（boolean，选填）
	FuzzyQuery bool `json:"fuzzy_query,omitempty"`
}

type SettleOtherInUploadDetail struct {
	// 商家编码：商家编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 是否残次品：true:残次品false:正品默认false（boolean，选填）
	Defect bool `json:"defect,omitempty"`
	// 入库价：匹配对应入库价的明细，没有则按照商家编码+残次品的维度匹配（Decimal(19,4)，选填）
	StockinPrice float64 `json:"stockin_price,omitempty"`
	// 单价：不传默认为入库单明细的入库价（Decimal(19,4)，选填）
	Price float64 `json:"price,omitempty"`
	// 分摊邮费：分摊邮费（Decimal(19,4)，选填）
	SharePostFee float64 `json:"share_post_fee,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
}

type StockoutCollectQueryCostWithDetailParams struct {
	// 开始时间：起始时间（发货时间），若无出库单号则为必填。（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间（发货时间）（String，必填）
	EndTime string `json:"end_time"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 出库单号：出库单号，多个出库单号之间英文逗号分隔（String，选填）
	StockoutNo string `json:"stockout_no,omitempty"`
}

type StockinCollectQueryCostWithDetailParams struct {
	// 开始时间：起始时间，若无出库单号则为必填。（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间，上同开始时间.（String，必填）
	EndTime string `json:"end_time"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 时间查询类型：1：创建时间2：审核时间默认创建时间（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 入库单号：出库单号，多个入库单号之间英文逗号分隔（String，选填）
	StockinNo string `json:"stockin_no,omitempty"`
}

// Search 库存查询 - 获取ERP单品（sku）的库存量
// 支持增量获取
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限销量统计数据字段说明及计算方式，点击链接查看库存量字段说明，点击链接查看接口已过时, 请使用wms.StockSpec.search2
//
// 对应接口：wms.StockSpec.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockSpec.search
func (s *StockSpecService) Search(ctx context.Context, params *StockSpecSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.StockSpec.search", pager, params)
}

// Search2 库存查询2 - 获取ERP单品（sku）的库存量
// 支持增量获取
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限销量统计数据字段说明及计算方式，点击链接查看库存量字段说明，点击链接查看
//
// 对应接口：wms.StockSpec.search2
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockSpec.search2
func (s *StockSpecService) Search2(ctx context.Context, params *StockSpecSearch2Params, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.StockSpec.search2", pager, params)
}

// QueryAvailableStock 可用库存查询 - 获取ERP内单品的可用库存量
// 支持增量获取
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限
//
// 对应接口：wms.StockSpec.queryAvailableStock
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockSpec.queryAvailableStock
func (s *StockSpecService) QueryAvailableStock(ctx context.Context, params *StockSpecQueryAvailableStockParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.StockSpec.queryAvailableStock", pager, params)
}

// QueryChangeHistory 库存变化查询 - 获取ERP库存变化信息
// 支持增量获取
// start_date和end_date最大跨度为30天
// 【权限校验】：仓库权限如传入商家编码，start_date和end_date最大跨度为30天，如不传入商家编码，start_date和end_date最大跨度为60min。
//
// 对应接口：wms.StockSpec.queryChangeHistory
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockSpec.queryChangeHistory
func (s *StockSpecService) QueryChangeHistory(ctx context.Context, params *StockSpecQueryChangeHistoryParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.StockSpec.queryChangeHistory", pager, params)
}

// StockDetailSearch 库存明细查询 - 获取库存管理页面下明细库存tab
//
// 需要配合库存查询接口，库存查询接口返回的rec_id作为该接口的入参
//
// 对应接口：wms.StockSpec.stockDetailSearch
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockSpec.stockDetailSearch
func (s *StockSpecService) StockDetailSearch(ctx context.Context, params *StockSpecStockDetailSearchParams) (*Response, error) {
	return s.client.Call(ctx, "wms.StockSpec.stockDetailSearch", params)
}

// StockSyncByPd 创建盘点单 - ERP库存需要调整时，推送盘点库存单据给ERP
// 【权限校验】：仓库权限盘点模式只允许单品盘点，该接口会将库存数据直接覆盖。相当于直接在ERP操作新建盘点单，盘点录入，执行盘点三个步骤。
//
// 对应接口：wms.StockPd.stockSyncByPd
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockPd.stockSyncByPd
func (s *StockPdService) StockSyncByPd(ctx context.Context, pdOrder *StockPdStockSyncByPdPdOrder, specList []*StockPdStockSyncByPdSpec) (*Response, error) {
	return s.client.Call(ctx, "wms.StockPd.stockSyncByPd", pdOrder, specList)
}

// QueryStockPd 盘点单查询 - 获取ERP内盘点单信息
//
// 【权限校验】：仓库权限
//
// 对应接口：wms.StockPd.queryStockPd
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockPd.queryStockPd
func (s *StockPdService) QueryStockPd(ctx context.Context, params *StockPdQueryStockPdParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.StockPd.queryStockPd", pager, params)
}

// QueryStockPdDetail 盘点单明细查询 - 获取ERP内盘点单明细信息
//
// 【权限校验】：仓库权限
//
// 对应接口：wms.StockPd.queryStockPdDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockPd.queryStockPdDetail
func (s *StockPdService) QueryStockPdDetail(ctx context.Context, params *StockPdQueryStockPdDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.StockPd.queryStockPdDetail", pager, params)
}

// QueryStockPdInDetail 盘点入库单查询 - 获取ERP盘点入库单信息
// 支持增量获取
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限
//
// 对应接口：wms.StockPd.queryStockPdInDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockPd.queryStockPdInDetail
func (s *StockPdService) QueryStockPdInDetail(ctx context.Context, params *StockPdQueryStockPdInDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.StockPd.queryStockPdInDetail", pager, params)
}

// QueryStockPdOutDetail 盘点出库单查询 - 获取ERP盘点出库单信息
// 支持增量获取
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限
//
// 对应接口：wms.StockPd.queryStockPdOutDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockPd.queryStockPdOutDetail
func (s *StockPdService) QueryStockPdOutDetail(ctx context.Context, params *StockPdQueryStockPdOutDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.StockPd.queryStockPdOutDetail", pager, params)
}

// QueryWithDetail 移位单查询 - 获取ERP的移位单信息
// 支持
// start_time和end_time最大跨度为30天。
// 【权限校验】：仓库权限
//
// 对应接口：wms.MoveOrder.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.MoveOrder.queryWithDetail
func (s *MoveOrderService) QueryWithDetail(ctx context.Context, params *MoveOrderQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.MoveOrder.queryWithDetail", pager, params)
}

// CreateOtherOrder 其它入库单新建 - ERP需要增加库存且入库单据没有对应的业务类型，推送其它入库单给ERP
//
// 【权限校验】：仓库权限不支持批量创建，一次只能推一单
//
// 对应接口：wms.stockin.Other.createOtherOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Other.createOtherOrder
func (s *StockinOtherService) CreateOtherOrder(ctx context.Context, stockinOrder *StockinOtherCreateOtherOrderStockinOrder) (*Response, error) {
	return s.client.Call(ctx, "wms.stockin.Other.createOtherOrder", stockinOrder)
}

// QueryWithDetail 其它入库单查询 - 获取ERP其它入库单单据信息
// 支持增量获取
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockin.Other.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Other.queryWithDetail
func (s *StockinOtherService) QueryWithDetail(ctx context.Context, params *StockinOtherQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockin.Other.queryWithDetail", pager, params)
}

// CancelOtherOrder 其它入库单取消 - 取消待审核或编辑中状态的其它入库单
// 待审核状态单据可能会在驳回的时候返回编辑成功或者是取消失败，此类情况需要重试【权限校验】：仓库权限 无仓库权限单据无法取消成功
//
// 对应接口：wms.stockin.Other.cancelOtherOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Other.cancelOtherOrder
func (s *StockinOtherService) CancelOtherOrder(ctx context.Context, orderNo string, isForce bool) (*Response, error) {
	return s.client.Call(ctx, "wms.stockin.Other.cancelOtherOrder", orderNo, isForce)
}

// CreateOther 其它出库单新建 - ERP需要减少库存且出库单据没有对应的业务类型，推送其它出库单给ERP
//
// 不支持批量创建，一次只能推一单
//
// 对应接口：wms.stockout.Other.createOther
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Other.createOther
func (s *StockoutOtherService) CreateOther(ctx context.Context, stockoutOrder *StockoutOtherCreateOtherStockoutOrder) (*Response, error) {
	return s.client.Call(ctx, "wms.stockout.Other.createOther", stockoutOrder)
}

// QueryWithDetail 其它出库单查询 - 获取ERP其它出库单单据信息
// 支持增量获取
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限。
//
// 对应接口：wms.stockout.OtherQuery.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.OtherQuery.queryWithDetail
func (s *StockoutOtherQueryService) QueryWithDetail(ctx context.Context, params *StockoutOtherQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockout.OtherQuery.queryWithDetail", pager, params)
}

// CancelOtherOrder 其它出库单取消 - 取消待审核或未确认状态的其它出库单
// 待审核状态单据可能会在驳回的时候返回编辑成功或者是取消失败，此类情况需要重试 【权限校验】：仓库权限 无仓库权限单据无法取消成功
//
// 对应接口：wms.stockout.Other.cancelOtherOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Other.cancelOtherOrder
func (s *StockoutOtherService) CancelOtherOrder(ctx context.Context, orderNo string, isForce bool) (*Response, error) {
	return s.client.Call(ctx, "wms.stockout.Other.cancelOtherOrder", orderNo, isForce)
}

// QueryWithDetail 调拨入库单查询 - 获取ERP调拨入库单单据信息
// 支持增量获取
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockin.Transfer.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Transfer.queryWithDetail
func (s *StockinTransferService) QueryWithDetail(ctx context.Context, params *StockinTransferQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockin.Transfer.queryWithDetail", pager, params)
}

// CreateOrder 调拨入库单新建 - 推送调拨入库单据给ERP
//
// 对应接口：wms.stockin.Transfer.createOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Transfer.createOrder
func (s *StockinTransferService) CreateOrder(ctx context.Context, orderInfo *StockinTransferCreateOrderOrderInfo, detailList []*StockinTransferCreateOrderDetail, isCheck bool) (*Response, error) {
	return s.client.Call(ctx, "wms.stockin.Transfer.createOrder", orderInfo, detailList, isCheck)
}

// CancelOrder 调拨单入库取消 - 取消编辑中/待审核状态的调拨入库单
// 不支持
// start_time和end_time最大跨度为30天。
// 【权限校验】：无
//
// 对应接口：wms.stockin.Transfer.cancelOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Transfer.cancelOrder
func (s *StockinTransferService) CancelOrder(ctx context.Context, transferInNo string) (*Response, error) {
	return s.client.Call(ctx, "wms.stockin.Transfer.cancelOrder", transferInNo)
}

// QueryWithDetail 调拨出库单查询 - 获取ERP调拨出库单信息
// 支持增量获取
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockout.Transfer.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Transfer.queryWithDetail
func (s *StockoutTransferService) QueryWithDetail(ctx context.Context, params *StockoutTransferQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockout.Transfer.queryWithDetail", pager, params)
}

// CreateOrder 调拨出库单新建 - 推送调拨出库单据给ERP
//
// 对应接口：wms.stockout.Transfer.createOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Transfer.createOrder
func (s *StockoutTransferService) CreateOrder(ctx context.Context, orderInfo *StockoutTransferCreateOrderOrderInfo, detailList []*StockoutTransferCreateOrderDetail, isCheck bool) (*Response, error) {
	return s.client.Call(ctx, "wms.stockout.Transfer.createOrder", orderInfo, detailList, isCheck)
}

// CancelOrder 调拨单出库取消 - 取消未确认状态的调拨出库单
// 【权限校验】：无
//
// 对应接口：wms.stockout.Transfer.cancelOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Transfer.cancelOrder
func (s *StockoutTransferService) CancelOrder(ctx context.Context, transferOutNo string) (*Response, error) {
	return s.client.Call(ctx, "wms.stockout.Transfer.cancelOrder", transferOutNo)
}

// QueryWithDetail 调拨单查询 - 获取ERP调拨单据信息
// 支持增量获取
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限
//
// 对应接口：wms.stocktransfer.Manage.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stocktransfer.Manage.queryWithDetail
func (s *StockTransferService) QueryWithDetail(ctx context.Context, params *StockTransferQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stocktransfer.Manage.queryWithDetail", pager, params)
}

// CancelOrder 调拨单取消 - 取消编辑中/待审核状态的调拨单
// 【权限校验】：无
//
// 对应接口：wms.stocktransfer.Manage.cancelOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stocktransfer.Manage.cancelOrder
func (s *StockTransferService) CancelOrder(ctx context.Context, transferNo string) (*Response, error) {
	return s.client.Call(ctx, "wms.stocktransfer.Manage.cancelOrder", transferNo)
}

// Pending 调拨单停止等待 - 调拨单停止等待
//
// 对应接口：wms.stocktransfer.Manage.pending
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stocktransfer.Manage.pending
func (s *StockTransferService) Pending(ctx context.Context, transferNos []string, isback bool) (*Response, error) {
	return s.client.Call(ctx, "wms.stocktransfer.Manage.pending", transferNos, isback)
}

// CreateOrder 调拨单新建 - 推送调拨单给ERP
//
// 【权限校验】：仓库权限
//
// 对应接口：wms.stocktransfer.Edit.createOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stocktransfer.Edit.createOrder
func (s *StockTransferEditService) CreateOrder(ctx context.Context, orderInfo *StockTransferEditCreateOrderOrderInfo, detailList []*StockTransferEditCreateOrderDetail, isCheck bool) (*Response, error) {
	return s.client.Call(ctx, "wms.stocktransfer.Edit.createOrder", orderInfo, detailList, isCheck)
}

// QueryWithDetail 补货单查询 - 获取ERP库存变化信息
// 支持增量获取
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限
//
// 对应接口：wms.StockShelve.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.StockShelve.queryWithDetail
func (s *StockShelveService) QueryWithDetail(ctx context.Context, params *StockShelveQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.StockShelve.queryWithDetail", pager, params)
}

// Push 其它入库业务单创建 - 其它入库业务单创建
//
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockother.In.push
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockother.In.push
func (s *StockotherInService) Push(ctx context.Context, order *StockotherInPushOrder, orderDetails []*StockotherInPushOrderDetails) (*Response, error) {
	return s.client.Call(ctx, "wms.stockother.In.push", order, orderDetails)
}

// QueryWithDetail 其它入库业务单查询 - 获取ERP其他入库业务单信息
// 支持增量获取
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockother.InQuery.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockother.InQuery.queryWithDetail
func (s *StockotherInQueryService) QueryWithDetail(ctx context.Context, params *StockotherInQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockother.InQuery.queryWithDetail", pager, params)
}

// CancelOrder 其它入库业务单据取消 - 其它入库业务单取消
// 支持取消已审核、待审核、编辑中状态的单据v1.5.7.0及以上版本 支持按照原业务单号入参取消带-1的单据（待审核/已推送wms状态均支持）
//
// 对应接口：wms.stockother.In.cancelOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockother.In.cancelOrder
func (s *StockotherInService) CancelOrder(ctx context.Context, orderNoList []string) (*Response, error) {
	return s.client.Call(ctx, "wms.stockother.In.cancelOrder", orderNoList)
}

// Push 其它出库业务单创建 - 其它出库业务单创建
//
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockother.Out.push
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockother.Out.push
func (s *StockotherOutService) Push(ctx context.Context, order *StockotherOutPushOrder, orderDetails []*StockotherOutPushOrderDetails) (*Response, error) {
	return s.client.Call(ctx, "wms.stockother.Out.push", order, orderDetails)
}

// QueryWithDetail 其它出库业务单查询 - 获取ERP其他出库业务单信息
// 支持增量获取
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockother.OutQuery.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockother.OutQuery.queryWithDetail
func (s *StockotherOutQueryService) QueryWithDetail(ctx context.Context, params *StockotherOutQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockother.OutQuery.queryWithDetail", pager, params)
}

// CancelOrder 其它出库业务单据取消 - 其他出库业务单取消
// 支持取消已审核、待审核、编辑中状态的单据v1.5.7.0及以上版本 支持按照原业务单号入参取消带-1的单据（待审核/已推送wms状态均支持）
//
// 对应接口：wms.stockother.Out.cancelOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockother.Out.cancelOrder
func (s *StockotherOutService) CancelOrder(ctx context.Context, orderNoList []string) (*Response, error) {
	return s.client.Call(ctx, "wms.stockother.Out.cancelOrder", orderNoList)
}

// QueryWithDetail 生产出库查询 - 获取ERP生产出库信息
//
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockout.Process.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Process.queryWithDetail
func (s *StockoutProcessService) QueryWithDetail(ctx context.Context, params *StockoutProcessQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockout.Process.queryWithDetail", pager, params)
}

// QueryWithDetail 生产入库查询 - 获取ERP生产入库信息
//
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限 传入参数如果没有入库单号或者生产单号，就必须传入时间，和时间类型作为参数
//
// 对应接口：wms.stockin.Process.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Process.queryWithDetail
func (s *StockinProcessService) QueryWithDetail(ctx context.Context, params *StockinProcessQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockin.Process.queryWithDetail", pager, params)
}

// CreateOrder 外仓调整出库单创建 - 外仓调整出库单创建
//
// 【权限校验】：仓库权限
//
// 对应接口：wms.outer.OuterOut.createOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.outer.OuterOut.createOrder
func (s *OuterOutService) CreateOrder(ctx context.Context, order *OuterOutCreateOrderOrder, orderDetails []*OuterOutCreateOrderOrderDetails, isCheck bool) (*Response, error) {
	return s.client.Call(ctx, "wms.outer.OuterOut.createOrder", order, orderDetails, isCheck)
}

// QueryWithDetail 外仓调整出库单查询 - 获取ERP外仓调整出库信息
//
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限传入参数如果没有出库单号，就必须传入时间，和时间类型作为参数
//
// 对应接口：wms.outer.OuterOut.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.outer.OuterOut.queryWithDetail
func (s *OuterOutService) QueryWithDetail(ctx context.Context, params *OuterOutQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.outer.OuterOut.queryWithDetail", pager, params)
}

// CreateOrder 外仓调整入库单创建 - 外仓调整入库单创建
//
// 【权限校验】：仓库权限
//
// 对应接口：wms.outer.OuterIn.createOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.outer.OuterIn.createOrder
func (s *OuterInService) CreateOrder(ctx context.Context, order *OuterInCreateOrderOrder, orderDetails []*OuterInCreateOrderOrderDetails, isCheck bool) (*Response, error) {
	return s.client.Call(ctx, "wms.outer.OuterIn.createOrder", order, orderDetails, isCheck)
}

// QueryWithDetail 外仓调整入库单查询 - 获取ERP外仓调整入库信息
//
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限 传入参数如果没有入库单号，就必须传入时间，和时间类型作为参数
//
// 对应接口：wms.outer.OuterIn.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.outer.OuterIn.queryWithDetail
func (s *OuterInService) QueryWithDetail(ctx context.Context, params *OuterInQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.outer.OuterIn.queryWithDetail", pager, params)
}

// CreateByApi 外仓快速调拨 - 推送调拨单给ERP
//
// 【权限校验】：仓库权限(1)使用外仓明细调拨的情况下，仓库需要开启外仓库存明细配置(2)使用mode=3/4调拨方案的情况下，需要联系旺店通实施开通增值配置
//
// 对应接口：wms.outer.OuterTransfer.createByApi
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.outer.OuterTransfer.createByApi
func (s *OuterTransferService) CreateByApi(ctx context.Context, params *OuterTransferCreateByApiParams, detailList []*OuterTransferCreateByApiDetail) (*Response, error) {
	return s.client.Call(ctx, "wms.outer.OuterTransfer.createByApi", params, detailList)
}

// Search 正残转换单查询 - 获取ERP正残转换单信息
// 支持
// start_time和end_time最大跨度为30天
//
// 对应接口：wms.stockdefect.DefectChange.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockdefect.DefectChange.search
func (s *DefectChangeService) Search(ctx context.Context, params *DefectChangeSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockdefect.DefectChange.search", pager, params)
}

// PickListOverviewForApi 分拣单全览 - 获取ERP内分拣波次信息
//
// 【权限校验】：仓库权限。
//
// 对应接口：wms.stockout.SalesPick.pickListOverviewForApi
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.SalesPick.pickListOverviewForApi
func (s *SalesPickService) PickListOverviewForApi(ctx context.Context, pickNo string) (*Response, error) {
	return s.client.Call(ctx, "wms.stockout.SalesPick.pickListOverviewForApi", pickNo)
}

// Search 默认货位查询 - 获取ERP单品（sku）默认货位
// 支持
// start_time、end_time时间跨度不能大于7天
// 【权限校验】：仓库权限、时间不传的情况下，warehouse_no和spec_no必传
//
// 对应接口：wms.PositionCapacity.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.PositionCapacity.search
func (s *PositionCapacityService) Search(ctx context.Context, params *PositionCapacitySearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.PositionCapacity.search", pager, params)
}

// Search 装箱单查询 - 查询系统内非jit类型的装箱单
// 支持
//
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockout.Pack.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Pack.search
func (s *PackService) Search(ctx context.Context, params *PackSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockout.Pack.search", pager, params)
}

// SearchOrderWithDetail JIT退货入库单查询 - 获取ERP的JIT退货入库单单据信息
// 按照最后修改时间获取
// 请求时间最大跨度为30天。
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockin.JitRefund.searchOrderWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.JitRefund.searchOrderWithDetail
func (s *StockinJitRefundService) SearchOrderWithDetail(ctx context.Context, params *StockinJitRefundSearchOrderWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockin.JitRefund.searchOrderWithDetail", pager, params)
}

// Search JIT出库单查询 - 获取ERP的JIT出库单单据信息
// 按照制单时间进行获取
//
// 对应接口：wms.stockout.JitOrder.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.JitOrder.search
func (s *StockoutJitOrderService) Search(ctx context.Context, params *StockoutJitOrderSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockout.JitOrder.search", pager, params)
}

// QueryWithDetail SN码查询 - 获取ERP序列号管理页面的数据
//
// start_time与end_time起止时间跨度不超过30天
//
// 对应接口：wms.GoodsSN.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.GoodsSN.queryWithDetail
func (s *GoodsSNService) QueryWithDetail(ctx context.Context, params *GoodsSNQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.GoodsSN.queryWithDetail", pager, params)
}

// CreateByApi 批次号创建 - 创建批次号信息
//
// 对应接口：wms.GoodsBatch.createByApi
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.GoodsBatch.createByApi
func (s *GoodsBatchService) CreateByApi(ctx context.Context, items []*GoodsBatchCreateByApiItem) (*Response, error) {
	return s.client.Call(ctx, "wms.GoodsBatch.createByApi", items)
}

// Upload 箱码新建 - 创建箱码信息
//
// 对应接口：wms.GoodsPack.upload
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.GoodsPack.upload
func (s *GoodsPackService) Upload(ctx context.Context, params *GoodsPackUploadParams) (*Response, error) {
	return s.client.Call(ctx, "wms.GoodsPack.upload", params)
}

// Search 入库单查询 - 获取ERP入库单单据信息
// 支持增量获取
// 起止时间跨度不超过1天
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockin.Base.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Base.search
func (s *StockinBaseService) Search(ctx context.Context, params *StockinBaseSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockin.Base.search", pager, params)
}

// Search 出库单查询 - 获取ERP非销售类型出库单单据信息
// 支持增量获取
// 起止时间跨度不超过60分钟
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockout.Base.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Base.search
func (s *StockoutBaseService) Search(ctx context.Context, params *StockoutBaseSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockout.Base.search", pager, params)
}

// SearchSN 入库SN查询 - 查询已入库的SN信息
//
// 对应接口：wms.stockin.Base.searchSN
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Base.searchSN
func (s *StockinBaseService) SearchSN(ctx context.Context, params *StockinBaseSearchSNParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockin.Base.searchSN", pager, params)
}

// SearchSN 出库SN查询 - 查询已出库的SN信息
//
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockout.Base.searchSN
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Base.searchSN
func (s *StockoutBaseService) SearchSN(ctx context.Context, params *StockoutBaseSearchSNParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockout.Base.searchSN", pager, params)
}

// UploadSN 入库SN明细推送 - 针对已经创建好的入库单推送关联的SN信息
//
// 当前仅支持生产入库、调拨入库、其他入库 单据状态需要为 编辑中才能推送SN【权限校验】：仓库权限
//
// 对应接口：wms.stockin.Base.uploadSN
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockin.Base.uploadSN
func (s *StockinBaseService) UploadSN(ctx context.Context, params *StockinBaseUploadSNParams, detailList []*StockinBaseUploadSNDetail) (*Response, error) {
	return s.client.Call(ctx, "wms.stockin.Base.uploadSN", params, detailList)
}

// UploadSN 出库SN明细推送 - 针对已经创建好的出库单推送关联的SN信息
//
// 当前仅支持生产出库、调拨出库、其他出库、采购退货出库 单据状态需要为 编辑中才能推送SN【权限校验】：仓库权限
//
// 对应接口：wms.stockout.Base.uploadSN
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Base.uploadSN
func (s *StockoutBaseService) UploadSN(ctx context.Context, params *StockoutBaseUploadSNParams, detailList []*StockoutBaseUploadSNDetail) (*Response, error) {
	return s.client.Call(ctx, "wms.stockout.Base.uploadSN", params, detailList)
}

// QueryWithDetail 纠错单查询 - 获取ERP纠错管理页面的数据
//
// 对应接口：wms.ErrorCorrection.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.ErrorCorrection.queryWithDetail
func (s *ErrorCorrectionService) QueryWithDetail(ctx context.Context, params *ErrorCorrectionQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.ErrorCorrection.queryWithDetail", pager, params)
}

// Search 存货成本查询 - 获取ERP内存货成本信息
// 支持增量获取
// start_time和end_time最大跨度为30天
// 【权限校验】：仓库权限未开启多仓成本情况下，仓库编号返回空字符串；开启多仓成本后仓库编号返回实际仓库的编号。默认情况下未开启多仓成本。在调用此接口前需咨询客户是否开启多仓成本。
//
// 对应接口：finance.StockCost.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.StockCost.search
func (s *StockCostService) Search(ctx context.Context, params *StockCostSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "finance.StockCost.search", pager, params)
}

// Search 调拨结算查询 - 获取ERP调拨结算单信息
//
// start_time和end_time最大跨度为30天。
// 【权限校验】：仓库权限
//
// 对应接口：finance.settle.Transfer.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.settle.Transfer.search
func (s *SettleTransferService) Search(ctx context.Context, params *SettleTransferSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "finance.settle.Transfer.search", pager, params)
}

// Search 电子面单号查询 - 接口描述: 查询省份信息
// 支持
// start_time和end_time最大跨度为1小时
//
// 对应接口：finance.settle.Logistics.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.settle.Logistics.search
func (s *SettleLogisticsService) Search(ctx context.Context, params *SettleLogisticsSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "finance.settle.Logistics.search", pager, params)
}

// Upload 其它入库业务结算单创建 - 创建其它入库业务结算单给ERP
// 【仓库权限】、【供应商权限】
// 不支持批量创建
//
// 对应接口：finance.settle.OtherIn.upload
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.settle.OtherIn.upload
func (s *SettleOtherInService) Upload(ctx context.Context, orderInfo *SettleOtherInUploadOrder, detailList []*SettleOtherInUploadDetail) (*Response, error) {
	return s.client.Call(ctx, "finance.settle.OtherIn.upload", orderInfo, detailList)
}

// QueryCostWithDetail 出库瞬时成本查询 - 获取ERP出库瞬时成本信息
// start_time与end_time起止时间跨度不超过7天
// 【权限校验】：仓库权限。未开启多仓成本情况下，仓库编号返回空字符串；开启多仓成本后仓库编号返回实际仓库的编号
//
// 对应接口：statistic.StockoutCollect.queryCostWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=statistic.StockoutCollect.queryCostWithDetail
func (s *StockoutCollectService) QueryCostWithDetail(ctx context.Context, params *StockoutCollectQueryCostWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "statistic.StockoutCollect.queryCostWithDetail", pager, params)
}

// QueryCostWithDetail 入库瞬时成本查询 - 获取ERP入库瞬时成本信息
//
// start_time与end_time时间跨度不能超过7天
// 【权限校验】：仓库权限。未开启多仓成本情况下，仓库编号返回空字符串；开启多仓成本后仓库编号返回实际仓库的编号
//
// 对应接口：statistic.StockinCollect.queryCostWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=statistic.StockinCollect.queryCostWithDetail
func (s *StockinCollectService) QueryCostWithDetail(ctx context.Context, params *StockinCollectQueryCostWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "statistic.StockinCollect.queryCostWithDetail", pager, params)
}
