// Code generated by scripts/gen_sdk.py from 旺店通旗舰版 API 文档; DO NOT EDIT.
// 重新生成：python scripts/gen_sdk.py

package wdt

import "context"

// TradeQueryService 提供 sales.TradeQuery.* 接口的封装。
type TradeQueryService struct{ client *Client }

// RawTradeService 提供 sales.RawTrade.* 接口的封装。
type RawTradeService struct{ client *Client }

// LogisticsSyncService 提供 sales.LogisticsSync.* 接口的封装。
type LogisticsSyncService struct{ client *Client }

// StockSyncService 提供 sales.StockSync.* 接口的封装。
type StockSyncService struct{ client *Client }

// TradeEditService 提供 sales.TradeEdit.* 接口的封装。
type TradeEditService struct{ client *Client }

// TradeImportService 提供 sales.TradeImport.* 接口的封装。
type TradeImportService struct{ client *Client }

// SalesPaymentService 提供 sales.Payment.* 接口的封装。
type SalesPaymentService struct{ client *Client }

// SalesJitRefundService 提供 sales.jit.JitRefund.* 接口的封装。
type SalesJitRefundService struct{ client *Client }

// StockoutSalesService 提供 wms.stockout.Sales.* 接口的封装。
type StockoutSalesService struct{ client *Client }

// InvoiceOrderService 提供 finance.invoice.InvoiceOrder.* 接口的封装。
type InvoiceOrderService struct{ client *Client }

// RawPaymentService 提供 finance.RawPayment.* 接口的封装。
type RawPaymentService struct{ client *Client }

// AlipayAccountCheckService 提供 finance.AlipayAccountCheck.* 接口的封装。
type AlipayAccountCheckService struct{ client *Client }

// FinancePaymentService 提供 finance.Payment.* 接口的封装。
type FinancePaymentService struct{ client *Client }

// CustomAttrService 提供 setting.CustomAttr.* 接口的封装。
type CustomAttrService struct{ client *Client }

type TradeQueryWithDetailParams struct {
	// 开始时间：修改起始时间，若无订单编号/原始单号/物流单号，则为必填。示例：“ 2021-11-11 00:00:00”（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：修改结束时间，上同开始时间。示例：“ 2021-11-11 01:00:00”（String，必填）
	EndTime string `json:"end_time"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 订单状态：若多个状态则以“，”隔开。订单状态: 4 线下退款5已取消6 待转预订单(待审核)7 待转已完成10未付款12待尾款15等未付16延时审核19预订单前处理20 审核前处理21自流转待发货23 异常订单24 换货预订单25 待处理预订单27待分配预订单 30待客审35待财审40审核中55已审核95已发货96 成本确认（待录入计划成本，订单结算时有货品无计划成本）101 已过账110已完成（String，选填）
	Status string `json:"status,omitempty"`
	// 订单编号：订单编号（String，选填）
	TradeNo string `json:"trade_no,omitempty"`
	// 店铺编号：店铺编号（暂不支持批量查询）（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
	// 物流单号：物流单号，（V1.4.9.9版本以上支持按照物流单号查询不传入时间范围）（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 原始单号：原始单号, 多个原始单号之间使用英文逗号分隔（String，选填）
	SrcTid string `json:"src_tid,omitempty"`
	// 是否使用从库查询：使用：true 不使用：false（仅对开通从库配置客户生效）（boolean，选填）
	IsSlave bool `json:"is_slave,omitempty"`
	// 是否计算分摊邮费：是否计算分摊邮费默认false计算：true不计算：false（boolean，选填）
	CalSharePostAmount bool `json:"cal_share_post_amount,omitempty"`
	// 订单来源：订单来源1、API抓单2、手工建单3、导入4、复制订单5、接口推送6、补发订单7、PDA选货开单8、分销补发订单（String，选填）
	TradeFrom string `json:"trade_from,omitempty"`
	// 排序类型：0：默认排序1：修改时间降序（Int，选填）
	OrderType int `json:"order_type,omitempty"`
	// 时间类型：1：修改时间2：付款时间3：下单时间默认1（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 是否返回赠品关联关系：0：不返回1：返回默认1（boolean，选填）
	NeedGiftRelation bool `json:"need_gift_relation,omitempty"`
	// 是否强制指定src_tid精准查询：0：否1：是默认0（boolean，选填）
	AccurateQuery bool `json:"accurate_query,omitempty"`
	// 是否截取物流单号：0：不截取1：截取默认0（boolean，选填）
	CutLogisticsNo bool `json:"cut_logistics_no,omitempty"`
	// 是否已拆分：0：不拆分1：拆分默认全部（boolean，选填）
	IsSplit bool `json:"is_split,omitempty"`
	// 分销原始单号：分销原始单号（String，选填）
	FenxiaoTid string `json:"fenxiao_tid,omitempty"`
}

type TradeQueryHistoryWithDetailParams struct {
	// 时间类型：时间类型1：修改时间2：支付时间3：下单时间默认1（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 开始时间：修改起始时间，若无订单号，则为必填。（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：修改结束时间，上同开始时间（String，必填）
	EndTime string `json:"end_time"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 订单状态：若多个状态则以“，”隔开。订单状态: 4 线下退款5已取消6 待转预订单(待审核)7 待转已完成10未付款12待尾款15等未付16延时审核19预订单前处理20 审核前处理21自流转待发货23 异常预订单24 换货预订单25 待处理预订单27待分配预订单 30待客审35待财审55已审核95已发货96 成本确认（待录入计划成本，订单结算时有货品无计划成本）101 已过账110已完成（String，选填）
	Status string `json:"status,omitempty"`
	// 订单编号：订单编号（String，选填）
	TradeNo string `json:"trade_no,omitempty"`
	// 店铺编号：店铺编号（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 原始单号：原始单号, 多个原始单号之间使用英文逗号分隔（String，选填）
	SrcTid string `json:"src_tid,omitempty"`
	// 是否使用从库查询：使用：true 不使用：false(仅对开通从库配置客户生效)（boolean，选填）
	IsSlave bool `json:"is_slave,omitempty"`
	// 是否需要查询分摊邮费：需要：true 不需要：false（boolean，选填）
	CalSharePostAmount bool `json:"cal_share_post_amount,omitempty"`
	// 是否强制指定src_tid精准查询：是否精准查询（客户端V1.5.6.8及以上版本支持）0：否1：是默认0（boolean，选填）
	AccurateQuery bool `json:"accurate_query,omitempty"`
}

type TradeQuerySelfOrderWithDetailParams struct {
	// 开始时间：修改起始时间，若无订单编号/原始单号/物流单号，则为必填。示例：“ 2021-11-11 00:00:00”（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：修改结束时间，上同开始时间。示例：“ 2021-11-11 01:00:00”（String，必填）
	EndTime string `json:"end_time"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 订单状态：若多个状态则以“，”隔开。订单状态: 4 线下退款5已取消6 待转预订单(待审核)7 待转已完成10未付款12待尾款15等未付16延时审核19预订单前处理20 审核前处理21自流转待发货23 异常订单24 换货预订单25 待处理预订单27待分配预订单 30待客审35待财审40审核中55已审核95已发货96 成本确认（待录入计划成本，订单结算时有货品无计划成本）101 已过账110已完成（String，选填）
	Status string `json:"status,omitempty"`
	// 订单编号：订单编号（String，选填）
	TradeNo string `json:"trade_no,omitempty"`
	// 店铺编号：店铺编号（暂不支持批量查询）（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
	// 物流单号：物流单号，（V1.4.9.9版本以上支持按照物流单号查询不传入时间范围）（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 原始单号：原始单号, 多个原始单号之间使用英文逗号分隔（String，选填）
	SrcTid string `json:"src_tid,omitempty"`
	// 是否使用从库查询：使用：true 不使用：false（仅对开通从库配置客户生效）（boolean，选填）
	IsSlave bool `json:"is_slave,omitempty"`
	// 是否计算分摊邮费：是否计算分摊邮费默认false计算：true不计算：false（boolean，选填）
	CalSharePostAmount bool `json:"cal_share_post_amount,omitempty"`
	// 订单来源：订单来源1、API抓单2、手工建单3、导入4、复制订单5、接口推送6、补发订单7、PDA选货开单8、分销补发订单（String，选填）
	TradeFrom string `json:"trade_from,omitempty"`
	// 排序类型：0：默认排序1：修改时间降序（Int，选填）
	OrderType int `json:"order_type,omitempty"`
	// 时间类型：1：修改时间2：付款时间3：下单时间默认1（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 是否返回赠品关联关系：0：不返回1：返回默认1（boolean，选填）
	NeedGiftRelation bool `json:"need_gift_relation,omitempty"`
	// 是否强制指定src_tid精准查询（避免模糊查）：是否精准查询：0：（默认值）否， 1：是；（boolean，选填）
	AccurateQuery bool `json:"accurate_query,omitempty"`
	// 是否截取物流单号：0: (默认值) 不截取1：截取（boolean，选填）
	CutLogisticsNo bool `json:"cut_logistics_no,omitempty"`
	// 是否已拆分：0：不拆分1：拆分默认全部（boolean，选填）
	IsSplit bool `json:"is_split,omitempty"`
}

type TradeQueryHistorySelfOrderWithDetailParams struct {
	// 时间类型：时间类型1：修改时间2：支付时间3：下单时间默认1（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 开始时间：修改起始时间，若无订单号，则为必填。（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：修改结束时间，上同开始时间（String，必填）
	EndTime string `json:"end_time"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 订单状态：若多个状态则以“，”隔开。订单状态: 4 线下退款5已取消6 待转预订单(待审核)7 待转已完成10未付款12待尾款15等未付16延时审核19预订单前处理20 审核前处理21自流转待发货23 异常预订单24 换货预订单25 待处理预订单27待分配预订单 30待客审35待财审55已审核95已发货96 成本确认（待录入计划成本，订单结算时有货品无计划成本）101 已过账110已完成（String，选填）
	Status string `json:"status,omitempty"`
	// 订单编号：订单编号（String，选填）
	TradeNo string `json:"trade_no,omitempty"`
	// 店铺编号：店铺编号（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 原始单号：原始单号, 多个原始单号之间使用英文逗号分隔（String，选填）
	SrcTid string `json:"src_tid,omitempty"`
	// 是否使用从库查询：使用：true 不使用：false(仅对开通从库配置客户生效)（boolean，选填）
	IsSlave bool `json:"is_slave,omitempty"`
	// 是否需要查询分摊邮费：需要：true 不需要：false（boolean，选填）
	CalSharePostAmount bool `json:"cal_share_post_amount,omitempty"`
}

type TradeQueryGetLogParams struct {
	// 订单编号：订单编号（String，必填）
	TradeNo string `json:"trade_no"`
}

type TradeQueryGetLog2Params struct {
	// 订单编号：订单编号，多个订单编号之间用英文逗号隔开（String，必填）
	TradeNo string `json:"trade_no"`
}

type TradeQueryGetTradeMergedLogParams struct {
	// 开始时间：yyyy-MM-dd HH:mm:ss格式（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间，上同开始时间（String，必填）
	EndTime string `json:"end_time"`
}

type RawTradePushSelfRawTrade struct {
	// 原始单号：指商城、官网等平台的订单编号，ERP称之为原始单号，同一个sid下通过本接口新增订单的tid保证唯一。（String，必填）
	Tid string `json:"tid"`
	// 处理状态：是否执行自动递交以系统配置为准10: 待递交,20: 已递交，30: 部分发货，40: 已发货，60: 已完成，70: 已取消（Int，必填）
	ProcessStatus int `json:"process_status"`
	// 平台状态：10未确认 20待尾款 30待发货 40部分发货 50已发货 60已签收 70已完成 80已退款 90已关闭(付款前取消)，单据状态变更点击文档查看（Int，必填）
	TradeStatus int `json:"trade_status"`
	// 退款状态：0无退款 1申请退款 2部分退款 3全部退款，单据状态变更点击文档查看（Int，必填）
	RefundStatus int `json:"refund_status"`
	// 付款状态：0未付款1部分付款2已付款（Int，必填）
	PayStatus int `json:"pay_status"`
	// 子订单个数：原始单包含的子订单数，rawTradeOrderList节点下所有子单数之和（Int，必填）
	OrderCount int `json:"order_count"`
	// 货品总数量：货品总数量，rawTradeOrderList节点下所有“num”数量之和（Decimal(19,4)，必填）
	GoodsCount float64 `json:"goods_count"`
	// 支付方式：1在线转帐 2现金，3银行转账，4邮局汇款 5预付款 6刷卡 7支付宝 8微信支付（Int，必填）
	PayMethod int `json:"pay_method"`
	// 下单时间：下单时间（String，必填）
	TradeTime string `json:"trade_time"`
	// 支付时间：支付时间（String，选填）
	PayTime string `json:"pay_time,omitempty"`
	// 交易结束时间：交易结束时间，若无则传null（String，必填）
	EndTime string `json:"end_time"`
	// 买家昵称/客户网名：若无则传一个固定值（String，必填）
	BuyerNick string `json:"buyer_nick"`
	// 买家备注：若无则传‘’（String，选填）
	BuyerMessage string `json:"buyer_message,omitempty"`
	// 买家邮箱：‘’（String，选填）
	BuyerEmail string `json:"buyer_email,omitempty"`
	// 买家地区：‘’（String，选填）
	BuyerArea string `json:"buyer_area,omitempty"`
	// 收件人姓名：收件人姓名（String，必填）
	ReceiverName string `json:"receiver_name"`
	// 省市区：省市区空格分隔，示例【北京 北京市 朝阳区】，省市区推送旺店通地址库，点击查看（String，必填）
	ReceiverArea string `json:"receiver_area"`
	// 地址：收件人详细地址，不包含省市区，示例【xx街道xx小区xx号楼101】（String，必填）
	ReceiverAddress string `json:"receiver_address"`
	// 收件人邮编：收件人邮编，若无则传‘’（String，选填）
	ReceiverZip string `json:"receiver_zip,omitempty"`
	// 收件人手机：该字段必传，收件人手机号，为11位手机号码，示例【13888888888】（String，必填）
	ReceiverMobile string `json:"receiver_mobile"`
	// 收件人电话：收件人固话号，为11位固话号码，示例【02288888888】（String，选填）
	ReceiverTelno string `json:"receiver_telno,omitempty"`
	// 邮费：邮费（Decimal(19,4)，必填）
	PostAmount float64 `json:"post_amount"`
	// 其他费用：其他费用（Decimal(19,4)，选填）
	OtherAmount float64 `json:"other_amount,omitempty"`
	// 优惠金额：优惠金额（Decimal(19,4)，必填）
	Discount float64 `json:"discount"`
	// 应收金额：应收金额，售前退款会变化，“详细金额逻辑点击查看”（Decimal(19,4)，必填）
	Receivable float64 `json:"receivable"`
	// 平台费用：0.0000（Decimal(19,4)，选填）
	PlatformCost float64 `json:"platform_cost,omitempty"`
	// 发票类别：0：不需要1：普通发票2：增值税普通发票3：增值税专用发票（Int，选填）
	InvoiceType int `json:"invoice_type,omitempty"`
	// 发票抬头：发票抬头，若无则传‘’（String，选填）
	InvoiceTitle string `json:"invoice_title,omitempty"`
	// 发票内容：发票内容，格式：纳税人识别号:*******;地址:*******;开户银行:*******;银行账号:******;联系电话:*****,电子邮箱***** 若无则传‘""（String，选填）
	InvoiceContent string `json:"invoice_content,omitempty"`
	// 物流类别：-1（Int，选填）
	LogisticsType int `json:"logistics_type,omitempty"`
	// 物流编号：系统物流编号（设置--基本设置--物流）（String，选填）
	CustData string `json:"cust_data,omitempty"`
	// 发货条件：1款到发货 2货到付款(包含部分货到付款)（Int，必填）
	DeliveryTerm int `json:"delivery_term"`
	// 平台支付订单ID：‘’（String，选填）
	PayId string `json:"pay_id,omitempty"`
	// 客服备注：客服备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 客服备注标记：标旗（1 红、2 黄、3 绿、4 蓝、5 紫、6 橙、7 浅蓝、8 浅粉、9 深绿、10 桃红 无则填0）（Int，选填）
	RemarkFlag int `json:"remark_flag,omitempty"`
	// 货到付款金额：若delivery_term=2，则为应付金额，否则则为0（Decimal(19,4)，选填）
	CodAmount float64 `json:"cod_amount,omitempty"`
	// 是否是自流转：true自流转，false 非自流转 自动流转模式处理办法详解 单击这里（Boolean，必填）
	IsAutoWms bool `json:"is_auto_wms"`
	// 仓库编号：仅自流转订单填写该仓库编号, 非自流转订单传入空字符串即可（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 买家支付宝帐号：‘’（String，选填）
	PayAccount string `json:"pay_account,omitempty"`
	// 买家要求的送货日期：买家要求的送货日期（String，选填）
	ToDeliverTime string `json:"to_deliver_time,omitempty"`
	// 已收：已从平台收款的金额（Decimal(19,4)，选填）
	Received float64 `json:"received,omitempty"`
	// 淘宝新增,物流到货时效，单位小时：淘宝新增,物流到货时效，单位小时（Int，选填）
	ConsignInterval int `json:"consign_interval,omitempty"`
	// 已支付金额：已支付金额（Decimal(19,4)，选填）
	Paid float64 `json:"paid,omitempty"`
	// 是否能合并订单：0：默认3：不允许合并（byte，选填）
	IsSealed int `json:"is_sealed,omitempty"`
	// 分销商名称：分销商名称（String，选填）
	FenxiaoNick string `json:"fenxiao_nick,omitempty"`
	// 证件类型：0：无1：身份证2：军官证3：护照（Int，选填）
	IdCardType int `json:"id_card_type,omitempty"`
	// 证件号：证件号（String，选填）
	IdCard string `json:"id_card,omitempty"`
	// 省份id：省份id，点击查看省市区代码表（传省份id、市id、区id的情况下可以不传receiver_area字段）（Int，选填）
	ReceiverProvinceNo int `json:"receiver_province_no,omitempty"`
	// 市id：市id，点击查看省市区代码表 （传省份id、市id、区id的情况下可以不传receiver_area字段）（Int，选填）
	ReceiverCityNo int `json:"receiver_city_no,omitempty"`
	// 区id：区id，点击查看省市区代码表 （传省份id、市id、区id的情况下可以不传receiver_area字段）（Int，选填）
	ReceiverDistrictNo int `json:"receiver_district_no,omitempty"`
	// 物流单号：物流单号 is_auto_wms=1自流转模式 支持传入外部发货物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
}

type RawTradePushSelfRawTradeOrder struct {
	// 原始订单号：原始订单号（String，必填）
	Tid string `json:"tid"`
	// 原始子单号：平台订单货品表主键,子订单唯一标识,同一个sid下通过本接口新增订单的oid（子订单编号）要保证唯一；如果oid重复,ERP生成系统单（递交）时会提示“订单货品数量不一致xxxxxx”（String，必填）
	Oid string `json:"oid"`
	// 平台的状态：10未确认 20待尾款 30待发货 40部分发货 50已发货 60已签收 70已完成 80已退款 90已关闭，单据状态变更点击文档查看（Int，必填）
	Status int `json:"status"`
	// 退款标记：0无退款1取消退款,2已申请退款,3等待退货,4等待收货,5退款成功,6未付款关闭，单据状态变更点击文档查看（Int，必填）
	RefundStatus int `json:"refund_status"`
	// 平台货品ID：平台系统货品（SPU）的唯一标识。SPU和SKU概念介绍，单击这里（String，必填）
	GoodsId string `json:"goods_id"`
	// 平台规格ID：平台系统单品（SKU）的的唯一标识。SPU和SKU概念介绍，单击这里（String，必填）
	SpecId string `json:"spec_id"`
	// 货品编号：货品编号（String，必填）
	GoodsNo string `json:"goods_no"`
	// 规格编码：规格编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 货品名称：货品名称（String，必填）
	GoodsName string `json:"goods_name"`
	// 规格名称：规格名称（String，选填）
	SpecName string `json:"spec_name,omitempty"`
	// 子单类型：0正常货品 1虚拟货品 2服务（不传默认为0）（Int，选填）
	OrderType int `json:"order_type,omitempty"`
	// 平台类目：平台类目（String，选填）
	Cid string `json:"cid,omitempty"`
	// 数量：数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 单价：单价（Decimal(19,4)，必填）
	Price float64 `json:"price"`
	// 优惠：优惠，平台折扣, 不包含手工调整和分摊优惠（Decimal(19,4)，必填）
	Discount float64 `json:"discount"`
	// 分摊优惠：分摊优惠,退款不变（Decimal(19,4)，必填）
	ShareDiscount float64 `json:"share_discount"`
	// 总价格：总价格，“详细金额逻辑点击查看”（Decimal(19,4)，必填）
	TotalAmount float64 `json:"total_amount"`
	// 手工调整的优惠金额：手工调整的优惠金额，“详细金额逻辑点击查看”（Decimal(19,4)，必填）
	AdjustAmount float64 `json:"adjust_amount"`
	// 退款金额：退款金额（Decimal(19,4)，必填）
	RefundAmount float64 `json:"refund_amount"`
	// 备注：备注（String，必填）
	Remark string `json:"remark"`
	// json串：json串，若无可传“”（String，必填）
	Json string `json:"json"`
	// 赠品方式：赠品方式0非赠品1自动赠送2手工赠送4周期购赠送8平台赠送32阶梯满赠 64CRM追加赠送 65 主品（Int，选填）
	GiftType int `json:"gift_type,omitempty"`
}

type RawTradePushSelfDiscount struct {
	// 原始订单号：原始订单号（String，必填）
	Tid string `json:"tid"`
	// 原始子单号：原始子单号（String，必填）
	Oid string `json:"oid"`
	// 唯一编码：平台上优惠的唯一标识（String，选填）
	Sn string `json:"sn,omitempty"`
	// 优惠名称：优惠名称（String，选填）
	Name string `json:"name,omitempty"`
	// 优惠详情：优惠详情（String，选填）
	Detail string `json:"detail,omitempty"`
	// 优惠金额：优惠金额（Decimal(19,4)，选填）
	Amount float64 `json:"amount,omitempty"`
}

type RawTradePushSelf2RawTrade struct {
	// 原始单号：指商城、官网等平台的订单编号，ERP称之为原始单号，同一个sid下通过本接口新增订单的tid保证唯一。（String，必填）
	Tid string `json:"tid"`
	// 处理状态：是否执行自动递交以系统配置为准10: 待递交,20: 已递交，30: 部分发货，40: 已发货，60: 已完成，70: 已取消（Int，必填）
	ProcessStatus int `json:"process_status"`
	// 平台状态：10未确认 20待尾款 30待发货 40部分发货 50已发货 60已签收 70已完成 80已退款 90已关闭(付款前取消)，单据状态变更点击文档查看（Int，必填）
	TradeStatus int `json:"trade_status"`
	// 退款状态：0无退款 1申请退款 2部分退款 3全部退款，单据状态变更点击文档查看（Int，必填）
	RefundStatus int `json:"refund_status"`
	// 付款状态：0未付款1部分付款2已付款（Int，必填）
	PayStatus int `json:"pay_status"`
	// 子订单个数：原始单包含的子订单数，rawTradeOrderList节点下所有子单数之和（Int，必填）
	OrderCount int `json:"order_count"`
	// 货品总数量：货品总数量，rawTradeOrderList节点下所有“num”数量之和（Decimal(19,4)，必填）
	GoodsCount float64 `json:"goods_count"`
	// 支付方式：1在线转帐 2现金，3银行转账，4邮局汇款 5预付款 6刷卡 7支付宝 8微信支付（Int，必填）
	PayMethod int `json:"pay_method"`
	// 下单时间：下单时间（String，必填）
	TradeTime string `json:"trade_time"`
	// 支付时间：支付时间（String，选填）
	PayTime string `json:"pay_time,omitempty"`
	// 交易结束时间：交易结束时间，若无则传null（String，必填）
	EndTime string `json:"end_time"`
	// 买家昵称/客户网名：若无则传一个固定值（String，必填）
	BuyerNick string `json:"buyer_nick"`
	// 买家备注：若无则传‘’（String，选填）
	BuyerMessage string `json:"buyer_message,omitempty"`
	// 买家邮箱：‘’（String，选填）
	BuyerEmail string `json:"buyer_email,omitempty"`
	// 买家地区：‘’（String，选填）
	BuyerArea string `json:"buyer_area,omitempty"`
	// 收件人姓名：收件人姓名（String，必填）
	ReceiverName string `json:"receiver_name"`
	// 省市区：省市区空格分隔，示例【北京 北京市 朝阳区】，省市区推送旺店通地址库，点击查看（String，必填）
	ReceiverArea string `json:"receiver_area"`
	// 地址：收件人详细地址，不包含省市区，示例【xx街道xx小区xx号楼101】（String，必填）
	ReceiverAddress string `json:"receiver_address"`
	// 收件人邮编：收件人邮编，若无则传‘’（String，选填）
	ReceiverZip string `json:"receiver_zip,omitempty"`
	// 收件人手机：该字段必传，收件人手机号，为11位手机号码，示例【13888888888】（String，必填）
	ReceiverMobile string `json:"receiver_mobile"`
	// 收件人电话：收件人固话号，为11位固话号码，示例【02288888888】（String，选填）
	ReceiverTelno string `json:"receiver_telno,omitempty"`
	// 邮费：邮费（Decimal(19,4)，必填）
	PostAmount float64 `json:"post_amount"`
	// 其他费用：其他费用（Decimal(19,4)，选填）
	OtherAmount float64 `json:"other_amount,omitempty"`
	// 优惠金额：优惠金额（Decimal(19,4)，必填）
	Discount float64 `json:"discount"`
	// 应收金额：应收金额，售前退款会变化，“详细金额逻辑点击查看”（Decimal(19,4)，必填）
	Receivable float64 `json:"receivable"`
	// 平台费用：0.0000（Decimal(19,4)，选填）
	PlatformCost float64 `json:"platform_cost,omitempty"`
	// 发票类别：0：不需要1：普通发票2：增值税普通发票3：增值税专用发票（Int，选填）
	InvoiceType int `json:"invoice_type,omitempty"`
	// 发票抬头：发票抬头，若无则传‘’（String，选填）
	InvoiceTitle string `json:"invoice_title,omitempty"`
	// 发票内容：发票内容，格式：纳税人识别号:*******;地址:*******;开户银行:*******;银行账号:******;联系电话:*****,电子邮箱***** 若无则传‘""（String，选填）
	InvoiceContent string `json:"invoice_content,omitempty"`
	// 物流类别：-1（Int，选填）
	LogisticsType int `json:"logistics_type,omitempty"`
	// 物流编号：系统物流编号（设置--基本设置--物流）（String，选填）
	CustData string `json:"cust_data,omitempty"`
	// 发货条件：1款到发货 2货到付款(包含部分货到付款) 3分期付款（Int，必填）
	DeliveryTerm int `json:"delivery_term"`
	// 平台支付订单ID：‘’（String，选填）
	PayId string `json:"pay_id,omitempty"`
	// 客服备注：客服备注（String，选填）
	Remark string `json:"remark,omitempty"`
	// 客服备注标记：标旗（1 红、2 黄、3 绿、4 蓝、5 紫、6 橙、7 浅蓝、8 浅粉、9 深绿、10 桃红 无则填0）（Int，选填）
	RemarkFlag int `json:"remark_flag,omitempty"`
	// 货到付款金额：若delivery_term=2，则为应付金额，否则为0（Decimal(19,4)，选填）
	CodAmount float64 `json:"cod_amount,omitempty"`
	// 是否是自流转：true自流转，false 非自流转 自动流转模式处理办法详解 单击这里（Boolean，必填）
	IsAutoWms bool `json:"is_auto_wms"`
	// 仓库编号：仅自流转订单填写该仓库编号, 非自流转订单传入空字符串即可（String，必填）
	WarehouseNo string `json:"warehouse_no"`
	// 买家支付宝帐号：‘’（String，选填）
	PayAccount string `json:"pay_account,omitempty"`
	// 买家要求的送货日期：买家要求的送货日期（String，选填）
	ToDeliverTime string `json:"to_deliver_time,omitempty"`
	// 已收：已从平台收款的金额（Decimal(19,4)，选填）
	Received float64 `json:"received,omitempty"`
	// 淘宝新增,物流到货时效，单位小时：淘宝新增,物流到货时效，单位小时（Int，选填）
	ConsignInterval int `json:"consign_interval,omitempty"`
	// 已付：已支付金额（Decimal(19,4)，选填）
	Paid float64 `json:"paid,omitempty"`
	// 是否能合并订单：0：默认3：不允许合并（byte，选填）
	IsSealed int `json:"is_sealed,omitempty"`
	// 分销商名称：分销商名称（String，选填）
	FenxiaoNick string `json:"fenxiao_nick,omitempty"`
	// 证件类型：0：无1：身份证2：军官证3：护照（Int，选填）
	IdCardType int `json:"id_card_type,omitempty"`
	// 证件号：证件号（String，选填）
	IdCard string `json:"id_card,omitempty"`
	// 省份id：省份id，点击查看省市区代码表（传省份id、市id、区id的情况下可以不传receiver_area字段）（Int，选填）
	ReceiverProvinceNo int `json:"receiver_province_no,omitempty"`
	// 市id：市id，点击查看省市区代码表 （传省份id、市id、区id的情况下可以不传receiver_area字段）（Int，选填）
	ReceiverCityNo int `json:"receiver_city_no,omitempty"`
	// 区id：区id，点击查看省市区代码表 （传省份id、市id、区id的情况下可以不传receiver_area字段）（Int，选填）
	ReceiverDistrictNo int `json:"receiver_district_no,omitempty"`
	// 物流单号：物流单号 is_auto_wms=1时 自流转模式支持传入外部发货物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
}

type RawTradePushSelf2RawTradeOrder struct {
	// 原始订单号：原始订单号（String，必填）
	Tid string `json:"tid"`
	// 原始子单号：平台订单货品表主键,子订单唯一标识,同一个sid下通过本接口新增订单的oid（子订单编号）要保证唯一；如果oid重复,ERP生成系统单（递交）时会提示“订单货品数量不一致xxxxxx”（String，必填）
	Oid string `json:"oid"`
	// 平台的状态：10未确认 20待尾款 30待发货 40部分发货 50已发货 60已签收 70已完成 80已退款 90已关闭，单据状态变更点击文档查看（Int，必填）
	Status int `json:"status"`
	// 退款标记：0无退款1取消退款,2已申请退款,3等待退货,4等待收货,5退款成功,6未付款关闭，单据状态变更点击文档查看（Int，必填）
	RefundStatus int `json:"refund_status"`
	// 平台货品ID：平台系统货品（SPU）的唯一标识。SPU和SKU概念介绍，单击这里（String，必填）
	GoodsId string `json:"goods_id"`
	// 平台规格ID：平台系统单品（SKU）的的唯一标识。SPU和SKU概念介绍，单击这里（String，必填）
	SpecId string `json:"spec_id"`
	// 货品编号：货品编号（String，必填）
	GoodsNo string `json:"goods_no"`
	// 规格编码：规格编码（String，必填）
	SpecNo string `json:"spec_no"`
	// 货品名称：货品名称（String，必填）
	GoodsName string `json:"goods_name"`
	// 规格名称：规格名称（String，选填）
	SpecName string `json:"spec_name,omitempty"`
	// 子单类型：0正常货品 1虚拟货品 2服务（不传默认为0）（Int，选填）
	OrderType int `json:"order_type,omitempty"`
	// 平台类目：平台类目（String，选填）
	Cid string `json:"cid,omitempty"`
	// 数量：数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 单价：单价（Decimal(19,4)，必填）
	Price float64 `json:"price"`
	// 优惠：优惠，平台折扣, 不包含手工调整和分摊优惠（Decimal(19,4)，必填）
	Discount float64 `json:"discount"`
	// 分摊优惠：分摊优惠,退款不变（Decimal(19,4)，必填）
	ShareDiscount float64 `json:"share_discount"`
	// 总价格：总价格，“详细金额逻辑点击查看”（Decimal(19,4)，必填）
	TotalAmount float64 `json:"total_amount"`
	// 手工调整的优惠金额：手工调整的优惠金额，“详细金额逻辑点击查看”（Decimal(19,4)，必填）
	AdjustAmount float64 `json:"adjust_amount"`
	// 退款金额：退款金额（Decimal(19,4)，必填）
	RefundAmount float64 `json:"refund_amount"`
	// 备注：备注（String，必填）
	Remark string `json:"remark"`
	// json串：json串，若无可传“”（String，必填）
	Json string `json:"json"`
	// 赠品方式：赠品方式0非赠品1自动赠送2手工赠送4周期购赠送8平台赠送32阶梯满赠 64CRM追加赠送 65 主品（Int，选填）
	GiftType int `json:"gift_type,omitempty"`
}

type RawTradePushSelf2Discount struct {
	// 原始订单号：原始订单号（String，必填）
	Tid string `json:"tid"`
	// 原始子单号：原始子单号（String，必填）
	Oid string `json:"oid"`
	// 唯一编码：平台上优惠的唯一标识（String，选填）
	Sn string `json:"sn,omitempty"`
	// 优惠名称：优惠名称（String，选填）
	Name string `json:"name,omitempty"`
	// 优惠详情：优惠详情（String，选填）
	Detail string `json:"detail,omitempty"`
	// 优惠金额：优惠金额（Decimal(19,4)，选填）
	Amount float64 `json:"amount,omitempty"`
}

type RawTradeSearchParams struct {
	// 原始单号：原始单号（String，选填）
	Tid string `json:"tid,omitempty"`
	// 开始时间：修改起始时间（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：修改结束时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 店铺编号：店铺编号（暂不支持批量查询）（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
	// 是否使用从库查询：使用:true 不使用:false(仅对开通从库配置客户生效)（boolean，选填）
	IsSlave bool `json:"is_slave,omitempty"`
	// 优惠明细掩码：默认为0，1：返回优惠明细0：不返回优惠明细（Int，选填）
	DetailMask int `json:"detail_mask,omitempty"`
	// 递交异常：不传为全部 传递该参数的时候会把递交状态强制置为待递交 1 有异常 0 无异常（int，选填）
	BadReason int `json:"bad_reason,omitempty"`
}

type RawTradeSearchHistoryParams struct {
	// 原始单号：原始单号（String，选填）
	Tid string `json:"tid,omitempty"`
	// 开始时间：修改起始时间（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：修改结束时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 店铺编号：店铺编号（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
	// 是否使用从库查询：使用:true 不使用:false(仅对开通从库配置客户生效)（boolean，选填）
	IsSlave bool `json:"is_slave,omitempty"`
	// 优惠明细掩码：默认为0，1：返回优惠明细0：不返回优惠明细（Int，选填）
	DetailMask int `json:"detail_mask,omitempty"`
}

type RawTradeSearchSelfOrderParams struct {
	// 原始单号：原始单号（String，选填）
	Tid string `json:"tid,omitempty"`
	// 开始时间：修改起始时间（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：修改结束时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 店铺编号：店铺编号（暂不支持批量查询）（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
	// 是否使用从库查询：使用:true 不使用:false(仅对开通从库配置客户生效)（boolean，选填）
	IsSlave bool `json:"is_slave,omitempty"`
	// 优惠明细掩码：默认为0，1：返回优惠明细0：不返回优惠明细（Int，选填）
	DetailMask int `json:"detail_mask,omitempty"`
}

type RawTradeSearchHistorySelfOrderParams struct {
	// 原始单号：原始单号（String，选填）
	Tid string `json:"tid,omitempty"`
	// 开始时间：修改起始时间（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：修改结束时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 店铺编号：店铺编号（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
	// 是否使用从库查询：使用:true 不使用:false(仅对开通从库配置客户生效)（boolean，选填）
	IsSlave bool `json:"is_slave,omitempty"`
	// 优惠明细掩码：默认为0，1：返回优惠明细0：不返回优惠明细（Int，选填）
	DetailMask int `json:"detail_mask,omitempty"`
}

type LogisticsSyncGetSyncListExtParams struct {
	// 店铺编号：店铺编号，不支持传入多个店铺编号（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
	// 是否自有平台：是否自有平台（自有平台调用传true）是：true 否：false不填默认为false（bool，选填）
	IsOwnPlatform bool `json:"is_own_platform,omitempty"`
	// 原始单号：原始单号（String，选填）
	Tid string `json:"tid,omitempty"`
	// 物流单号：物流单号（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 是否拆单发货：1拆单发货，0非拆单发货 不传则不使用该条件（Int，选填）
	IsPartSync int `json:"is_part_sync,omitempty"`
	// 同步状态：3:淘宝发货等待判断-2:淘宝发货不可达-1:淘宝发货可达0:等待同步2:同步失败3:同步成功4:手动设置同步成功5:手动取消同步6:自动取消同步（String，选填）
	SyncStatus string `json:"sync_status,omitempty"`
}

type LogisticsSyncUpdateSync struct {
	// 物流同步：在物流同步接口获取到的物流同步id（Int，必填）
	SyncId int `json:"sync_id"`
	// 同步结果：0: 同步成功、-100: 还需同步，2:同步失败（Int，必填）
	Status int `json:"status"`
	// 错误信息：失败的错误信息，若成功传“”（String，选填）
	ErrorMsg string `json:"error_msg,omitempty"`
}

type StockSyncFailInfo struct {
	// 最后同步库存量：最后同步库存量（Decimal(19,4)，必填）
	SynStock float64 `json:"syn_stock"`
	// 库存变化量：库存变化量（Decimal(19,4)，必填）
	StockChangeCount float64 `json:"stock_change_count"`
	// 同步规则策略id：同步规则策略id（Int，必填）
	StockSynRuleId int `json:"stock_syn_rule_id"`
	// 同步规则策略编号：同步规则策略编号（String，必填）
	StockSynRuleNo string `json:"stock_syn_rule_no"`
	// 同步策略的其他信息：同步策略的其他信息（String，必填）
	StockSynOther string `json:"stock_syn_other"`
	// 库存同步的仓库id：库存同步的仓库id，多个仓库则用,分隔（String，必填）
	StockSynWarehouses string `json:"stock_syn_warehouses"`
	// 库存计算方法的掩码：库存计算方法的掩码（Int，必填）
	StockSynMask int `json:"stock_syn_mask"`
	// 同步百分比：同步百分比（Int，必填）
	StockSynPercent int `json:"stock_syn_percent"`
	// 增加值：增加值（Decimal(19,4)，必填）
	StockSynPlus float64 `json:"stock_syn_plus"`
	// 最小同步库存量：最小同步库存量（Decimal(19,4)，必填）
	StockSynMin float64 `json:"stock_syn_min"`
	// 最大同步：最大同步（Decimal(19,4)，必填）
	StockSynMax float64 `json:"stock_syn_max"`
	// 是否自动上架：是否自动上架（Boolean，必填）
	IsAutoListing bool `json:"is_auto_listing"`
	// 是否自动下架：是否自动下架（Boolean，必填）
	IsAutoDelisting bool `json:"is_auto_delisting"`
	// 是否同步成功：是否同步成功（Boolean，必填）
	IsSynSuccess bool `json:"is_syn_success"`
	// 是否手动同步：是否手动同步（Boolean，必填）
	IsManual bool `json:"is_manual"`
	// 同步结果：同步结果（String，必填）
	SynResult string `json:"syn_result"`
}

type StockSyncSuccessInfo struct {
	// 同步库存量：同步库存量（Decimal(19,4)，必填）
	SynStock float64 `json:"syn_stock"`
	// 库存变化量：库存变化量（Decimal(19,4)，必填）
	StockChangeCount float64 `json:"stock_change_count"`
	// 同步规则策略id：同步规则策略id（Int，必填）
	StockSynRuleId int `json:"stock_syn_rule_id"`
	// 同步规则策略编号：同步规则策略编号（String，必填）
	StockSynRuleNo string `json:"stock_syn_rule_no"`
	// 同步策略的其他信息：同步策略的其他信息（String，必填）
	StockSynOther string `json:"stock_syn_other"`
	// 库存同步的仓库id：库存同步的仓库id，多个仓库则用,分隔（String，必填）
	StockSynWarehouses string `json:"stock_syn_warehouses"`
	// 库存计算方法的掩码：库存计算方法的掩码（Int，必填）
	StockSynMask int `json:"stock_syn_mask"`
	// 同步百分比：同步百分比（Int，必填）
	StockSynPercent int `json:"stock_syn_percent"`
	// 增加值：增加值（Decimal(19,4)，必填）
	StockSynPlus float64 `json:"stock_syn_plus"`
	// 最小同步库存量：最小同步库存量（Decimal(19,4)，必填）
	StockSynMin float64 `json:"stock_syn_min"`
	// 最大同步：最大同步（Decimal(19,4)，必填）
	StockSynMax float64 `json:"stock_syn_max"`
	// 是否自动上架：是否自动上架（Boolean，必填）
	IsAutoListing bool `json:"is_auto_listing"`
	// 是否自动下架：是否自动下架（Boolean，必填）
	IsAutoDelisting bool `json:"is_auto_delisting"`
	// 是否同步成功：是否同步成功（Boolean，必填）
	IsSynSuccess bool `json:"is_syn_success"`
	// 是否手动同步：是否手动同步（Boolean，必填）
	IsManual bool `json:"is_manual"`
	// 同步结果：同步结果（String，必填）
	SynResult string `json:"syn_result"`
}

type StockSyncBatchCalcStockParams struct {
	// 平台货品的rec_id：平台货品的rec_id（long，必填）
	ApiGoodsId int64 `json:"api_goods_id"`
	// 货品是否开启检测：true开启；false未开启，（主要用于被停用平台货品或临时停止库存同步时强制同步库存，无该逻辑传false即可）（Boolean，必填）
	ForceSync bool `json:"force_sync"`
}

type TradeEditModifyRemarkParams struct {
	// 订单备注列表（List<Map<String, Object>>，必填）
	Data []*TradeEditModifyRemarkParamsData `json:"data"`
}

type TradeEditModifyRemarkParamsData struct {
	// 订单编号：系统订单编号（String，必填）
	TradeNo string `json:"trade_no"`
	// 客服备注：客服备注（String，必填）
	CsRemark string `json:"cs_remark"`
	// 是否按追加方式添加：是否按追加方式添加，默认否（bool，选填）
	IsSuperAdd bool `json:"is_super_add,omitempty"`
}

type TradeEditUploadChangeGoodsByApiParams struct {
	// 换入货品：换入货品（String，必填）
	SpecNoIn string `json:"spec_no_in"`
	// 换出货品：换出货品（String，必填）
	SpecNoOut string `json:"spec_no_out"`
	// 优先级：默认1（tinyint，选填）
	Priority int `json:"priority,omitempty"`
	// 是否停用：0：否（默认）1：是（tinyint，选填）
	IsDisabled int `json:"is_disabled,omitempty"`
	// 是否可互换：0：否1：是（默认）会建两条数据，两个分单品分别做换出传入（tinyint，选填）
	IsMutually int `json:"is_mutually,omitempty"`
}

type TradeImportUploadTrade struct {
	// 订单编号：订单编号（String，必填）
	TradeNo string `json:"trade_no"`
	// 原始单号：原始单号（String，选填）
	SrcTids string `json:"src_tids,omitempty"`
	// 原始子单号：原始子单号（String，选填）
	SrcOid string `json:"src_oid,omitempty"`
	// 订单类别：订单类别1：网店销售2：线下订单3：售后换货4：批发业务7：现款销售（Byte，选填）
	TradeType int `json:"trade_type,omitempty"`
	// 订单来源：订单来源1：API抓单2：手工建单3：导入5：接口推送6：补发订单7：PDA选货开单（Byte，选填）
	TradeFrom int `json:"trade_from,omitempty"`
	// 应收金额：应收金额（Decimal(19,4)，必填）
	Receivable float64 `json:"receivable"`
	// 店铺名称：店铺名称（String，必填）
	ShopName string `json:"shop_name"`
	// 仓库名称：仓库名称（String，必填）
	WarehouseName string `json:"warehouse_name"`
	// 物流公司名称：系统内自定义的物流公司名称（String，必填）
	LogisticsName string `json:"logistics_name"`
	// 邮费：邮费（Decimal(19,4)，选填）
	PostAmount float64 `json:"post_amount,omitempty"`
	// 物流单号：物流单号（String，必填）
	LogisticsNo string `json:"logistics_no"`
	// 商家编码：商家编码（String，必填）
	MerchantNo string `json:"merchant_no"`
	// 货品数量：货品数量（Decimal(19,4)，必填）
	Num float64 `json:"num"`
	// 货品价格：货品价格（Decimal(19,4)，必填）
	OrderPrice float64 `json:"order_price"`
	// 业务员：业务员（String，选填）
	Salesman string `json:"salesman,omitempty"`
	// 审单员：审单员（String，选填）
	Checker string `json:"checker,omitempty"`
	// 发票类型：发票类型0：不需要发票1：普通发票2：增值税发票（Byte，选填）
	InvoiceType int `json:"invoice_type,omitempty"`
	// 发票抬头：发票抬头（String，选填）
	InvoiceTitle string `json:"invoice_title,omitempty"`
	// 发票内容：发票内容（String，选填）
	InvoiceContect string `json:"invoice_contect,omitempty"`
	// 客户网名：客户网名（String，选填）
	BuyerNick string `json:"buyer_nick,omitempty"`
	// 收件人：收件人（String，必填）
	ReceiverName string `json:"receiver_name"`
	// 省份：省份（String，选填）
	Province string `json:"province,omitempty"`
	// 城市：城市（String，选填）
	City string `json:"city,omitempty"`
	// 区县：区县（String，选填）
	District string `json:"district,omitempty"`
	// 大头笔：大头笔（String，选填）
	ReceiverDtb string `json:"receiver_dtb,omitempty"`
	// 地址：地址（String，必填）
	ReceiverAddress string `json:"receiver_address"`
	// 邮编：邮编（String，选填）
	ReceiverZip string `json:"receiver_zip,omitempty"`
	// 电话：电话（String，必填）
	ReceiverMobile string `json:"receiver_mobile"`
	// 买家留言：买家留言（String，选填）
	BuyerMessage string `json:"buyer_message,omitempty"`
	// 客服备注：客服备注（String，选填）
	CsRemark string `json:"cs_remark,omitempty"`
	// 下单时间：下单时间yyyy-MM-dd HH:mm:ss格式（String，选填）
	TradeTime string `json:"trade_time,omitempty"`
	// 付款时间：付款时间yyyy-MM-dd HH:mm:ss格式（String，选填）
	PayTime string `json:"pay_time,omitempty"`
	// 审单时间：审单时间yyyy-MM-dd HH:mm:ss格式（String，选填）
	CheckTime string `json:"check_time,omitempty"`
	// 打单时间：打单时间yyyy-MM-dd HH:mm:ss格式（String，选填）
	PrintTime string `json:"print_time,omitempty"`
	// 扫描时间：扫描时间yyyy-MM-dd HH:mm:ss格式（String，选填）
	ScanTime string `json:"scan_time,omitempty"`
	// 发货时间：发货时间yyyy-MM-dd HH:mm:ss格式（String，选填）
	ConsignTime string `json:"consign_time,omitempty"`
	// 赠品方式：赠品方式0：非赠品1：自动赠送2：手动赠送3：回购自动赠送（Byte，选填）
	GiftType int `json:"gift_type,omitempty"`
	// 货品优惠：货品优惠（Decimal(19,4)，选填）
	GoodsDiscount float64 `json:"goods_discount,omitempty"`
}

type SalesPaymentQueryWithDetailParams struct {
	// 开始时间：开始时间，yyyy-MM-dd HH:mm:ss格式（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间，上同开始时间（String，必填）
	EndTime string `json:"end_time"`
	// 时间类型：0：创建时间1：收付时间默认0（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 状态：10：已取消20：待审核30：待结算40：已完成（Int，选填）
	Status int `json:"status,omitempty"`
	// 方向：0：收款1：退款（Int，选填）
	IsRefund int `json:"is_refund,omitempty"`
	// 收付单号：收付单号（String，选填）
	PaymentNo string `json:"payment_no,omitempty"`
	// 业务单号：业务单号（String，选填）
	SalesOrderNo string `json:"sales_order_no,omitempty"`
	// 店铺编号：店铺编号，多个使用英文逗号分隔（String，选填）
	ShopNos string `json:"shop_nos,omitempty"`
}

type SalesJitRefundSearchParams struct {
	// 开始时间：起始时间, yyyy-MM-dd HH:mm:ss格式（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束时间, yyyy-MM-dd HH:mm:ss格式（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 平台退货单号：平台退货单号（String，选填）
	JitRefundNo string `json:"jit_refund_no,omitempty"`
}

type StockoutSalesQueryWithDetailParams struct {
	// 开始时间：起始时间, status_type =1,2,3 按照出库单修改时间查询, status_type=0 按照发货时间查询（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间（String，必填）
	EndTime string `json:"end_time"`
	// 出库单状态：出库单状态: 默认值为01.已取消2.在企业版状态中对应status=55(已确认),这里为 待分配~延时发货（此条件会返回延时发货状态的订单）3.按照指定的status状态字段查询0.延时发货&已完成（Int，选填）
	StatusType int `json:"status_type,omitempty"`
	// 出库单状态详细：传status_type=3情况下，按照修改时间和status查询（status_type=3的情况下，若不传status字段，按照发货时间查询）出库单状态（若多个状态则以“，”隔开）: 5已取消10待放回(拣货待放回), 小于该值的都是已取消的单子50待审核51缺货52缺货待入库53 WMS已接单54 获取电子面单58 档口锁定60 待分配61 排队中63 待补货65 待处理 70 待发货73 爆款锁定74 预打包75 待拣货77 拣货中,PDA拣货后79 已拣货90 延时发货110已完成（String，选填）
	Status string `json:"status,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 出库单号：出库单号,V1.6.1.9支持批量查询多个单号之间用 ”,“间隔上限200（传入出库单号可以不传时间条件）（String，选填）
	StockoutNo string `json:"stockout_no,omitempty"`
	// 店铺编号：多个店铺编号使用英文逗号分隔（String，选填）
	ShopNos string `json:"shop_nos,omitempty"`
	// 销售订单号：系统订单号（传入ERP订单号可以不传时间条件）（String，选填）
	SrcOrderNo string `json:"src_order_no,omitempty"`
	// 物流单号：物流单号（存在匹配的出库单时，可以不传时间条件）（String，选填）
	LogisticsNo string `json:"logistics_no,omitempty"`
	// 是否返回sn信息：true:返回false:不返回（bool，选填）
	NeedSn bool `json:"need_sn,omitempty"`
	// 是否按照货位排序：等于0为否，不等于0为是，不填为否（Int，选填）
	Position int `json:"position,omitempty"`
	// 是否使用从库查询：使用：true 不使用：false(仅对开通从库配置客户生效)（boolean，选填）
	IsSlave bool `json:"is_slave,omitempty"`
	// 是否获取主播信息：true:返回 false:不返回（boolean，选填）
	GetAnchor bool `json:"get_anchor,omitempty"`
	// 排序类型：0：默认1：修改时间降序2：发货时间降序（Int，选填）
	OrderType int `json:"order_type,omitempty"`
	// 是否需要拣货位明细：0：不需要（默认）1：需要（Int，选填）
	NeedPickPosition int `json:"need_pick_position,omitempty"`
	// 是否需要国补信息：0：不需要（默认）1：需要（boolean，选填）
	NeedGovSubsidyInfo bool `json:"need_gov_subsidy_info,omitempty"`
	// 原始单号：原始单号（String，选填）
	SrcTid string `json:"src_tid,omitempty"`
	// 是否仅获取库存记录：0：否1：是默认0（Int，选填）
	FetchStockOnly int `json:"fetch_stock_only,omitempty"`
	// 是否需要保留销售出库单驳回合并后的原单据：是否需要保留销售出库单驳回合并后的原单据，如果需要保留原单据，需要同时传以下参数status_type: "3"status: "5,10,50,51,52,53,54,58,60,61,63,65,70,73,74,75,77,79,90,110"（boolean，选填）
	GetRejectedOriginalOrder bool `json:"get_rejected_original_order,omitempty"`
}

type StockoutSalesQueryHistoryWithDetailParams struct {
	// 开始时间：起始时间, status_type =1,2 按照出库单修改时间查询, status_type=0 按照发货时间查询（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间（String，必填）
	EndTime string `json:"end_time"`
	// 出库单状态：出库单状态: 默认值为01.已取消2.在企业版状态中对应status=55(已确认),这里为 待分配~延时发货0.已发货（Int，必填）
	StatusType int `json:"status_type"`
	// 仓库编码：仓库编码（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 出库单编号：出库单编号（String，选填）
	StockoutNo string `json:"stockout_no,omitempty"`
	// 店铺编号：多个店铺编号使用英文逗号分隔（String，选填）
	ShopNos string `json:"shop_nos,omitempty"`
	// 销售订单号：系统订单号（String，选填）
	SrcOrderNo string `json:"src_order_no,omitempty"`
}

type StockoutSalesWeighingParams struct {
	// 单据编号：物流单号或者出库单号（String，必填）
	OrderNo string `json:"order_no"`
	// 重量：重量（BigDecimal(19,4)，必填）
	Weight float64 `json:"weight"`
	// 包装条码：包装条码（String，选填）
	PackageBarcode string `json:"package_barcode,omitempty"`
	// 打包员编号：打包员编号，优先级高于打包员id（String，选填）
	PackagerNo string `json:"packager_no,omitempty"`
	// 打包员id：打包员id,如果传入打包员编号会覆盖id（int，选填）
	PackagerId int `json:"packager_id,omitempty"`
	// 打包台名称：打包台名称（String，选填）
	OperatorTableName string `json:"operator_table_name,omitempty"`
	// 是否强制称重：默认传false，常用于超重或与预估重量差距较大时强制称重（boolean，选填）
	Force bool `json:"force,omitempty"`
	// 长：单位CM，回传至物流单管理界面展示（BigDecimal(19,4)，选填）
	Length float64 `json:"length,omitempty"`
	// 宽：单位CM，回传至物流单管理界面展示（BigDecimal(19,4)，选填）
	Width float64 `json:"width,omitempty"`
	// 高：单位CM，回传至物流单管理界面展示（BigDecimal(19,4)，选填）
	Height float64 `json:"height,omitempty"`
}

type StockoutSalesSearchLogisticsParams struct {
	// 开始时间：最后变更时间, 开始时间,样例: 2022-01-25 16:40:06（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间（String，必填）
	EndTime string `json:"end_time"`
	// 状态：10:待发货;15:延时发货;20:待结算;30:已结算（Int，必填）
	Status int `json:"status"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
	// 单据类型：1:销售订单;2:调拨单;5:生产原料;21:其它出库;24:调整出库（目前仅支持查询销售订单类型的物流单数据）（String，选填）
	OrderType string `json:"order_type,omitempty"`
	// 订单编号：订单编号（String，选填）
	TradeNo string `json:"trade_no,omitempty"`
	// 原始单号：多个原始单号使用英文逗号分隔（String，选填）
	SrcTids string `json:"src_tids,omitempty"`
	// 店铺编号：店铺编号（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
}

type StockoutSalesSearchPositionDetailParams struct {
	// 开始时间：出库单最后修改时间，格式: yyyy-MM-dd HH:mm:ss（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：最后修改时间格式: yyyy-MM-dd HH:mm:ss（String，必填）
	EndTime string `json:"end_time"`
	// 出库单号：出库单号（String，选填）
	StockoutNo string `json:"stockout_no,omitempty"`
	// 销售订单号：系统订单号（ERP订单号）（String，选填）
	TradeNo string `json:"trade_no,omitempty"`
	// 仓库编号：仓库编号（String，选填）
	WarehouseNo string `json:"warehouse_no,omitempty"`
}

type StockoutSalesSearchCancelParams struct {
	// 开始时间：修改时间yyyy-MM-dd HH:mm:ss格式（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：修改时间yyyy-MM-dd HH:mm:ss格式（String，必填）
	EndTime string `json:"end_time"`
}

type InvoiceOrderSearchParams struct {
	// 开始时间：开始时间（最后更新时间）（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：结束时间（最后更新时间）（String，选填）
	EndTime string `json:"end_time,omitempty"`
	// 发票编号：发票编号（String，选填）
	InvoiceOrderNo string `json:"invoice_order_no,omitempty"`
	// 查询类型：1:按照传入的条件查询,不限制服务商类型和发票状态.默认仅返回线下待开票的数据（Int，选填）
	Mode int `json:"mode,omitempty"`
	// 发票状态：仅mode=1 时生效，5:取消;10:编辑中;20:待审核;35:导入待确认;40:待开票;45:线下待开票;50:开票中;60:开票成功;70开票申请失败;80:开票失败;85:线下开票失败;90:待上传PDF;100:上传失败;110:上传成功（Int，选填）
	Status int `json:"status,omitempty"`
	// 服务商类型：201 金壬（Int，选填）
	PlatformType int `json:"platform_type,omitempty"`
}

type InvoiceOrderUpdateInvoiceItem struct {
	// 发票编号：系统内部自动生成（String，必填）
	InvoiceOrderNo string `json:"invoice_order_no"`
	// 发票号码：发票号码（String，必填）
	InvoiceNo string `json:"invoice_no"`
	// 发票代码：发票代码（String，必填）
	InvoiceCode string `json:"invoice_code"`
	// 状态：60：开票成功85：线下开票失败（Int，必填）
	Status int `json:"status"`
	// 发票下载地址pdf：发票下载地址pdf（旺店通V1.5.8.0及以上版本file_url为必传项）（旺店通V1.5.8.4及以上版本 当status传85时，file_url可以不传）（String，必填）
	FileUrl string `json:"file_url"`
	// 发票下载地址ofd：发票下载地址ofd（String，选填）
	OfdUrl string `json:"ofd_url,omitempty"`
	// 发票下载地址xml：发票下载地址xml（String，选填）
	XmlUrl string `json:"xml_url,omitempty"`
	// 开票时间：yyyy-MM-dd HH:mm:ss格式（String，选填）
	InvoiceTime string `json:"invoice_time,omitempty"`
	// 错误信息：错误信息（String，选填）
	ErrorInfo string `json:"error_info,omitempty"`
	// 开票金额：开票金额（实际金额）（Decimal(19,4))，选填）
	InvoiceOuterAmount float64 `json:"invoice_outer_amount,omitempty"`
}

type RawPaymentSearchParams struct {
	// 店铺编号：店铺编号（String，选填）
	ShopNo string `json:"shop_no,omitempty"`
	// 关联单号：关联单号（String，选填）
	OrderNo string `json:"order_no,omitempty"`
	// 时间类型：1：收付时间2：下载时间默认按照收付时间进行获取（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 类型：0：其他1：收款2：退款（Int，选填）
	Type int `json:"type,omitempty"`
	// 时间起始：时间起始（String，必填）
	StartTime string `json:"start_time"`
	// 时间结束：时间结束（String，必填）
	EndTime string `json:"end_time"`
}

type RawPaymentPushDetail struct {
	// 店铺编号：店铺编号,，仅支持自有平台店铺（String，必填）
	ShopNo string `json:"shop_no"`
	// 关联单号：关联单号（原始单号）（String，必填）
	OrderNo string `json:"order_no"`
	// 支付单号：支付单号（String，选填）
	PayOrderNo string `json:"pay_order_no,omitempty"`
	// 收付时间：收付时间，不传默认当前时间（String，选填）
	CreateTime string `json:"create_time,omitempty"`
	// 是否担保：是否担保（Int，选填）
	IsGuarantee int `json:"is_guarantee,omitempty"`
	// 商户订单号：商户订单号（String，选填）
	RawOrderNo string `json:"raw_order_no,omitempty"`
	// 类型：类型0：其他1：收款2：退款默认0（Int，选填）
	Type int `json:"type,omitempty"`
	// 收入金额：收入金额（Decimal(19,4)，选填）
	InAmount float64 `json:"in_amount,omitempty"`
	// 支出金额：支出金额（Decimal(19,4)，选填）
	OutAmount float64 `json:"out_amount,omitempty"`
	// 数量：数量（正数发货，负数退货）（Decimal(19,4)，选填）
	Num float64 `json:"num,omitempty"`
	// 余额：余额（Decimal(19,4)，选填）
	Balance float64 `json:"balance,omitempty"`
	// 对方支付账号：对方支付账号（String，选填）
	OptPayAccount string `json:"opt_pay_account,omitempty"`
	// 备注：备注（String，选填）
	Remark string `json:"remark,omitempty"`
}

type AlipayAccountCheckSearchParams struct {
	// 开始时间：开始时间（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间（String，必填）
	EndTime string `json:"end_time"`
	// 时间条件类型：1：最后修改时间2：发货时间3：对账时间4：确认收货时间默认1（Byte，选填）
	TimeType int `json:"time_type,omitempty"`
	// 平台id：平台id，映射表点击详情查看（Short，必填）
	PlatformId int `json:"platform_id"`
	// 对账单状态：0：未确认1：部分对账2：对账失败3：对账成功4：设置对账成功（Byte，选填）
	Status int `json:"status,omitempty"`
}

type FinancePaymentSearchParams struct {
	// 开始时间：开始时间，yyyy-MM-dd HH:mm:ss格式（String，必填）
	StartTime string `json:"start_time"`
	// 结束时间：结束时间，上同开始时间（String，必填）
	EndTime string `json:"end_time"`
	// 时间类型：1: 创建时间 2: 最后修改时间 默认1（Int，选填）
	TimeType int `json:"time_type,omitempty"`
	// 收付单类型：1: 收款 2: 付款 3: 其它收款 4: 其他付款（byte，选填）
	Type int `json:"type,omitempty"`
	// 收付单状态：10: 编辑中 20: 待审核 30: 已审核 40: 已取消（byte，选填）
	Status int `json:"status,omitempty"`
}

type CustomAttrGetTradeLabelParams struct {
	// 开始时间：最后修改时间（String，选填）
	StartTime string `json:"start_time,omitempty"`
	// 结束时间：最后修改时间（String，选填）
	EndTime string `json:"end_time,omitempty"`
}

// QueryWithDetail 订单查询 - 获取ERP系统内订单信息
// 支持
// start_time和end_time最大跨度为60分钟。
//
// 对应接口：sales.TradeQuery.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeQuery.queryWithDetail
func (s *TradeQueryService) QueryWithDetail(ctx context.Context, params *TradeQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "sales.TradeQuery.queryWithDetail", pager, params)
}

// QueryHistoryWithDetail 历史订单查询 - 获取ERP的历史销售订单信息
// 支持
// start_time和end_time最大跨度为60分钟。
// 权限校验：【店铺权限】为了达到保护用户隐私数据安全的目的，本接口不返回淘系、拼多多及系统供销平台订单数据，相关平台规则点击这里，淘系及系统供销平台数据获取办法点击这里，拼多多请自行对接平台获取。本接口中涉及到用户隐私的字段数据仅自有平台及线下平台订单返回，具体字段详见下述“隐私字段列表”
//
// 对应接口：sales.TradeQuery.queryHistoryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeQuery.queryHistoryWithDetail
func (s *TradeQueryService) QueryHistoryWithDetail(ctx context.Context, params *TradeQueryHistoryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "sales.TradeQuery.queryHistoryWithDetail", pager, params)
}

// QuerySelfOrderWithDetail 订单查询（仅自有平台、线下平台） - 获取ERP系统内自有平台及线下平台订单信息
// 支持
// start_time和end_time最大跨度为60分钟。
// 权限校验：【店铺权限】仅返回自有平台、线下平台订单信息通过从后往前翻页的方式可以避免漏单问题。
//
// 对应接口：sales.TradeQuery.querySelfOrderWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeQuery.querySelfOrderWithDetail
func (s *TradeQueryService) QuerySelfOrderWithDetail(ctx context.Context, params *TradeQuerySelfOrderWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "sales.TradeQuery.querySelfOrderWithDetail", pager, params)
}

// QueryHistorySelfOrderWithDetail 历史订单查询（仅自有平台、线下平台） - 获取ERP自有平台及线下的历史销售订单信息
// 支持
// start_time和end_time最大跨度为60分钟。
// 权限校验：【店铺权限】仅返回自有平台、线下平台订单信息
//
// 对应接口：sales.TradeQuery.queryHistorySelfOrderWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeQuery.queryHistorySelfOrderWithDetail
func (s *TradeQueryService) QueryHistorySelfOrderWithDetail(ctx context.Context, params *TradeQueryHistorySelfOrderWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "sales.TradeQuery.queryHistorySelfOrderWithDetail", pager, params)
}

// GetLog 订单日志查询 - 按照订单编号查询订单日志
//
// 不支持批量查询
//
// 对应接口：sales.TradeQuery.getLog
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeQuery.getLog
func (s *TradeQueryService) GetLog(ctx context.Context, params *TradeQueryGetLogParams) (*Response, error) {
	return s.client.Call(ctx, "sales.TradeQuery.getLog", params)
}

// GetLog2 订单日志批量查询 - 按照订单编号查询订单日志
//
// 支持批量查询，建议单次查询不超过100
//
// 对应接口：sales.TradeQuery.getLog2
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeQuery.getLog2
func (s *TradeQueryService) GetLog2(ctx context.Context, params *TradeQueryGetLog2Params) (*Response, error) {
	return s.client.Call(ctx, "sales.TradeQuery.getLog2", params)
}

// GetTradeMergedLog 被合并订单查询 - 查询被合并订单信息
//
// 此数据仅保留七天, 每周一凌晨1点删除七天前数据; 查询时间间隔不可以超过七天
//
// 对应接口：sales.TradeQuery.getTradeMergedLog
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeQuery.getTradeMergedLog
func (s *TradeQueryService) GetTradeMergedLog(ctx context.Context, params *TradeQueryGetTradeMergedLogParams) (*Response, error) {
	return s.client.Call(ctx, "sales.TradeQuery.getTradeMergedLog", params)
}

// PushSelf 原始单推送 - ①推送销售订单给ERP ②更新已推送成功的销售订单
// 【权限校验】：店铺权限（仅支持自有平台推送）；上线之前必须在测试环境测试订单推送之后的相关流程!!!接口已过时, 请使用 sales.RawTrade.pushSelf2
//
// 对应接口：sales.RawTrade.pushSelf
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.RawTrade.pushSelf
func (s *RawTradeService) PushSelf(ctx context.Context, shopNo string, rawTradeList []*RawTradePushSelfRawTrade, rawTradeOrderList []*RawTradePushSelfRawTradeOrder, discountList []*RawTradePushSelfDiscount) (*Response, error) {
	return s.client.Call(ctx, "sales.RawTrade.pushSelf", shopNo, rawTradeList, rawTradeOrderList, discountList)
}

// PushSelf2 原始单推送2 - ①推送销售订单给ERP ②更新已推送成功的销售订单
// 【权限校验】：店铺权限（仅支持自有平台推送）；上线之前必须在测试环境测试订单推送之后的相关流程!!!单次推送建议单量不超过100单
//
// 对应接口：sales.RawTrade.pushSelf2
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.RawTrade.pushSelf2
func (s *RawTradeService) PushSelf2(ctx context.Context, shopNo string, rawTradeList []*RawTradePushSelf2RawTrade, rawTradeOrderList []*RawTradePushSelf2RawTradeOrder, discountList []*RawTradePushSelf2Discount) (*Response, error) {
	return s.client.Call(ctx, "sales.RawTrade.pushSelf2", shopNo, rawTradeList, rawTradeOrderList, discountList)
}

// Search 原始单查询 - 获取ERP原始订单信息
// 支持
// start_time和end_time最大跨度为30天。
//
// 对应接口：sales.RawTrade.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.RawTrade.search
func (s *RawTradeService) Search(ctx context.Context, params *RawTradeSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "sales.RawTrade.search", pager, params)
}

// SearchHistory 历史原始单查询 - 获取ERP已归档的原始订单信息
// 支持
// start_time和end_time最大跨度为30天。
//
// 对应接口：sales.RawTrade.searchHistory
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.RawTrade.searchHistory
func (s *RawTradeService) SearchHistory(ctx context.Context, params *RawTradeSearchHistoryParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "sales.RawTrade.searchHistory", pager, params)
}

// SearchSelfOrder 原始单查询（仅自有平台、线下平台） - 获取ERP自有平台及线下平台的原始订单信息
// 支持
// start_time和end_time最大跨度为30天。
// 【权限校验】：店铺权限仅返回自有平台、线下平台订单信息通过从后往前翻页的方式可以避免漏单问题。
//
// 对应接口：sales.RawTrade.searchSelfOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.RawTrade.searchSelfOrder
func (s *RawTradeService) SearchSelfOrder(ctx context.Context, params *RawTradeSearchSelfOrderParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "sales.RawTrade.searchSelfOrder", pager, params)
}

// SearchHistorySelfOrder 历史原始单查询（仅自有平台、线下平台） - 获取ERP已归档的自有平台及线下平台原始订单信息
// 支持
// start_time和end_time最大跨度为30天。
// 【权限校验】：店铺权限仅返回自有平台、线下平台订单通过从后往前翻页的方式可以避免漏单问题。
//
// 对应接口：sales.RawTrade.searchHistorySelfOrder
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.RawTrade.searchHistorySelfOrder
func (s *RawTradeService) SearchHistorySelfOrder(ctx context.Context, params *RawTradeSearchHistorySelfOrderParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "sales.RawTrade.searchHistorySelfOrder", pager, params)
}

// GetSyncListExt 待同步列表查询 - 查询待同步物流列表
// 不支持
// 【权限校验】：店铺权限（仅支持自有平台）
//
// 对应接口：sales.LogisticsSync.getSyncListExt
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.LogisticsSync.getSyncListExt
func (s *LogisticsSyncService) GetSyncListExt(ctx context.Context, params *LogisticsSyncGetSyncListExtParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "sales.LogisticsSync.getSyncListExt", pager, params)
}

// Update 物流同步状态回传 - 物流同步是否成功的状态回传给ERP
//
// 仅支持自有平台推送
//
// 对应接口：sales.LogisticsSync.update
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.LogisticsSync.update
func (s *LogisticsSyncService) Update(ctx context.Context, syncList []*LogisticsSyncUpdateSync) (*Response, error) {
	return s.client.Call(ctx, "sales.LogisticsSync.update", syncList)
}

// CancelSync 取消当前同步 - 取消库存同步
//
// 仅支持自有平台推送
//
// 对应接口：sales.StockSync.cancelSync
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.StockSync.cancelSync
func (s *StockSyncService) CancelSync(ctx context.Context, apiGoodsId int, stockChangeCount int) (*Response, error) {
	return s.client.Call(ctx, "sales.StockSync.cancelSync", apiGoodsId, stockChangeCount)
}

// SyncFail 库存同步失败 - 库存同步失败时调用
//
// 仅支持自有平台推送
//
// 对应接口：sales.StockSync.syncFail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.StockSync.syncFail
func (s *StockSyncService) SyncFail(ctx context.Context, apiGoodsId int, info *StockSyncFailInfo) (*Response, error) {
	return s.client.Call(ctx, "sales.StockSync.syncFail", apiGoodsId, info)
}

// SyncSuccess 库存同步成功 - 库存同步成功时调用
//
// 仅支持自有平台推送
//
// 对应接口：sales.StockSync.syncSuccess
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.StockSync.syncSuccess
func (s *StockSyncService) SyncSuccess(ctx context.Context, apiGoodsId int, info *StockSyncSuccessInfo) (*Response, error) {
	return s.client.Call(ctx, "sales.StockSync.syncSuccess", apiGoodsId, info)
}

// GetSelfWaitSyncIdListOpen 获取自有平台货品需要同步信息 - 获取自有平台货品需要同步信息
//
// 【权限校验】：店铺权限
//
// 对应接口：sales.StockSync.getSelfWaitSyncIdListOpen
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.StockSync.getSelfWaitSyncIdListOpen
func (s *StockSyncService) GetSelfWaitSyncIdListOpen(ctx context.Context, count int, position int) (*Response, error) {
	return s.client.Call(ctx, "sales.StockSync.getSelfWaitSyncIdListOpen", count, position)
}

// CalcStock 库存同步计算查询 - 计算自有平台货品应该同步的库存
//
// 原sales.StockSync.calcStockWithAuth替代接口（仅支持自有平台推送）如需批量查询请用下面接口：库存同步计算查询(支持批量查询)
//
// 对应接口：sales.StockSync.calcStock
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.StockSync.calcStock
func (s *StockSyncService) CalcStock(ctx context.Context, apiGoodsId int, forceSync bool) (*Response, error) {
	return s.client.Call(ctx, "sales.StockSync.calcStock", apiGoodsId, forceSync)
}

// BatchCalcStock 库存同步计算查询（批量） - 批量库存同步计算查询
//
// 对应接口：sales.StockSync.batchCalcStock
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.StockSync.batchCalcStock
func (s *StockSyncService) BatchCalcStock(ctx context.Context, params []*StockSyncBatchCalcStockParams) (*Response, error) {
	return s.client.Call(ctx, "sales.StockSync.batchCalcStock", params)
}

// ModifyRemark 订单客服备注修改 - 一次最多100条 (1.6.2.0版本及以上不再限制订单状态，低于1.6.2.0版本仅支持修改待审核状态订单备注)
//
// 【权限校验】：店铺权限
//
// 对应接口：sales.TradeEdit.modifyRemark
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeEdit.modifyRemark
func (s *TradeEditService) ModifyRemark(ctx context.Context, params *TradeEditModifyRemarkParams) (*Response, error) {
	return s.client.Call(ctx, "sales.TradeEdit.modifyRemark", params)
}

// ToException 订单转异常 - 将订单转入异常订单
// 仅支持待审核、待处理预订单、待分配预订单、换货预订单状态的订单
//
// 对应接口：sales.TradeEdit.toException
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeEdit.toException
func (s *TradeEditService) ToException(ctx context.Context, tradeNo string) (*Response, error) {
	return s.client.Call(ctx, "sales.TradeEdit.toException", tradeNo)
}

// UploadChangeGoodsByApi 优先级换货策略写入和更新 - 对流程图策略中得换货策略进行写入和更新
//
// 对应接口：sales.TradeEdit.uploadChangeGoodsByApi
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeEdit.uploadChangeGoodsByApi
func (s *TradeEditService) UploadChangeGoodsByApi(ctx context.Context, params []*TradeEditUploadChangeGoodsByApiParams) (*Response, error) {
	return s.client.Call(ctx, "sales.TradeEdit.uploadChangeGoodsByApi", params)
}

// Upload 已完成订单推送 - 推送已完成订单给ERP
// 【权限校验】：店铺权限、仓库权限一次最多传入200条数据数据不支持更新，需要保证请求参数正确推送的单据状态在客户端-销售-订单导入界面为待转已完成状态
//
// 对应接口：sales.TradeImport.upload
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.TradeImport.upload
func (s *TradeImportService) Upload(ctx context.Context, tradeList []*TradeImportUploadTrade) (*Response, error) {
	return s.client.Call(ctx, "sales.TradeImport.upload", tradeList)
}

// QueryWithDetail 销售收付单查询 - 获取ERP内销售收付款单信息
//
// 最大跨度不能超过30天
// 为了达到保护用户隐私数据安全的目的，本接口不返回淘系、拼多多及系统供销平台订单数据，相关平台规则点击这里，淘系及系统供销平台数据获取办法点击这里，拼多多请自行对接平台获取。本接口中涉及到用户隐私的字段数据仅有自有平台及线下平台订单返回。具体字段详情见下面表格；
//
// 对应接口：sales.Payment.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.Payment.queryWithDetail
func (s *SalesPaymentService) QueryWithDetail(ctx context.Context, params *SalesPaymentQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "sales.Payment.queryWithDetail", pager, params)
}

// Search JIT退货单查询 - 获取ERP的JIT退货单据信息
// 按照最后修改时间返回
// 起止时间跨度不超过30天
//
// 对应接口：sales.jit.JitRefund.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=sales.jit.JitRefund.search
func (s *SalesJitRefundService) Search(ctx context.Context, params *SalesJitRefundSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "sales.jit.JitRefund.search", pager, params)
}

// QueryWithDetail 销售出库单查询 - 获取ERP销售出库单信息
// 支持
// start_time和end_time最大跨度为60分钟。
//
// 对应接口：wms.stockout.Sales.queryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.queryWithDetail
func (s *StockoutSalesService) QueryWithDetail(ctx context.Context, params *StockoutSalesQueryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockout.Sales.queryWithDetail", pager, params)
}

// QueryHistoryWithDetail 历史销售出库单查询 - 获取ERP历史销售出库单信息
// 支持
// start_time和end_time最大跨度为60分钟。
// 权限校验：【店铺、仓库权限】为了达到保护用户隐私数据安全的目的，本接口不返回淘系、拼多多及系统供销平台订单数据，淘系相关平台规则点击这里，淘系数据获取办法点击这里，拼多多请自行对接平台获取。本接口中涉及到用户隐私的字段数据仅有自有平台及线下平台订单返回。具体字段详情见下面表格；
//
// 对应接口：wms.stockout.Sales.queryHistoryWithDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.queryHistoryWithDetail
func (s *StockoutSalesService) QueryHistoryWithDetail(ctx context.Context, params *StockoutSalesQueryHistoryWithDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockout.Sales.queryHistoryWithDetail", pager, params)
}

// WeighingExt 重量回传 - 将重量回传写入ERP销售订单出库单
//
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockout.Sales.weighingExt
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.weighingExt
func (s *StockoutSalesService) WeighingExt(ctx context.Context, logisticsOrTradeNo string, packageBarcode string, weight float64, packagerId int, force bool) (*Response, error) {
	return s.client.Call(ctx, "wms.stockout.Sales.weighingExt", logisticsOrTradeNo, packageBarcode, weight, packagerId, force)
}

// OnceWeighing 重量回传2 - 将重量回传写入ERP销售订单出库单
//
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockout.Sales.onceWeighing
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.onceWeighing
func (s *StockoutSalesService) OnceWeighing(ctx context.Context, logisticsOrTradeNo string, packageBarcode string, weight float64, packagerId int, operateTableName string, force bool) (*Response, error) {
	return s.client.Call(ctx, "wms.stockout.Sales.onceWeighing", logisticsOrTradeNo, packageBarcode, weight, packagerId, operateTableName, force)
}

// OnceWeighingByNo 重量回传3 - 将重量回传写入ERP销售订单出库单
// 不支持
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockout.Sales.onceWeighingByNo
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.onceWeighingByNo
func (s *StockoutSalesService) OnceWeighingByNo(ctx context.Context, logisticsOrTradeNo string, packageBarcode string, weight float64, packagerNo string, operateTableName string, force bool) (*Response, error) {
	return s.client.Call(ctx, "wms.stockout.Sales.onceWeighingByNo", logisticsOrTradeNo, packageBarcode, weight, packagerNo, operateTableName, force)
}

// SalesWeighing 重量回传4 - 将重量回传写入ERP销售订单出库单
//
// 【权限校验】：仓库权限 接口回传的长宽高在客户端-账款-单据结算-邮资结算-物流单管理界面查看
//
// 对应接口：wms.stockout.Sales.salesWeighing
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.salesWeighing
func (s *StockoutSalesService) SalesWeighing(ctx context.Context, params *StockoutSalesWeighingParams) (*Response, error) {
	return s.client.Call(ctx, "wms.stockout.Sales.salesWeighing", params)
}

// SearchLogistics 物流单查询 - 获取包含多物流的出库物流单信息
// 支持
// start_time与end_time时间跨度不超过1天
// 【权限校验】：仓库权限
//
// 对应接口：wms.stockout.Sales.searchLogistics
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.searchLogistics
func (s *StockoutSalesService) SearchLogistics(ctx context.Context, params *StockoutSalesSearchLogisticsParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockout.Sales.searchLogistics", pager, params)
}

// SearchPositionDetail 销售出库实际出库明细查询 - 获取销售出库实际出库明细
// 支持
// 起止时间跨度不超过60分钟
// 权限校验：【仓库权限】
//
// 对应接口：wms.stockout.Sales.searchPositionDetail
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.searchPositionDetail
func (s *StockoutSalesService) SearchPositionDetail(ctx context.Context, params *StockoutSalesSearchPositionDetailParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockout.Sales.searchPositionDetail", pager, params)
}

// SearchCancel 已取消出库单查询 - 获取已取消的销售出库单
//
// 起止时间差最大1小时
//
// 对应接口：wms.stockout.Sales.searchCancel
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=wms.stockout.Sales.searchCancel
func (s *StockoutSalesService) SearchCancel(ctx context.Context, params *StockoutSalesSearchCancelParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "wms.stockout.Sales.searchCancel", pager, params)
}

// Search 发票信息查询 - 获取发票信息
// 支持增量获取
// start_time和end_time最大跨度为30天
// 发票编号不填写的情况下必须填写开始时间和结束时间 【权限校验】：店铺权限为了达到保护用户隐私数据安全的目的，本接口不返回淘系、拼多多及系统供销平台订单数据，相关平台规则点击这里，淘系及系统供销平台数据获取办法点击这里，拼多多请自行对接平台获取。
//
// 对应接口：finance.invoice.InvoiceOrder.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.invoice.InvoiceOrder.search
func (s *InvoiceOrderService) Search(ctx context.Context, params *InvoiceOrderSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "finance.invoice.InvoiceOrder.search", pager, params)
}

// UpdateInvoice 发票信息更新 - 发票信息更新
//
// 状态为线下待开票或线下开票失败的发票单据支持回传
//
// 对应接口：finance.invoice.InvoiceOrder.updateInvoice
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.invoice.InvoiceOrder.updateInvoice
func (s *InvoiceOrderService) UpdateInvoice(ctx context.Context, items []*InvoiceOrderUpdateInvoiceItem) (*Response, error) {
	return s.client.Call(ctx, "finance.invoice.InvoiceOrder.updateInvoice", items)
}

// Search 平台账单查询 - 获取ERP内平台账单信息
//
// start_time和end_time最大跨度为30天
// 【权限校验】：店铺权限为了达到保护用户隐私数据安全的目的，本接口不返回淘系、拼多多及系统供销平台订单数据，淘系相关平台规则点击这里，淘系及系统供销平台数据获取办法点击这里，拼多多请自行对接平台获取。
//
// 对应接口：finance.RawPayment.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.RawPayment.search
func (s *RawPaymentService) Search(ctx context.Context, params *RawPaymentSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "finance.RawPayment.search", pager, params)
}

// Push 平台账单推送 - 推送平台账单信息
//
// 【权限校验】：店铺权限（仅支持自有平台推送）
//
// 对应接口：finance.RawPayment.push
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.RawPayment.push
func (s *RawPaymentService) Push(ctx context.Context, detailList []*RawPaymentPushDetail) (*Response, error) {
	return s.client.Call(ctx, "finance.RawPayment.push", detailList)
}

// Search 平台对账单查询 - 获取ERP内平台对账单信息
//
// start_time和end_time最大跨度为30天。
// 【权限校验】：店铺权限为了达到保护用户隐私数据安全的目的，本接口不返回淘系、拼多多及系统供销平台数据，相关平台规则点击这里，淘系数据获取办法点击这里，拼多多请自行对接平台获取。
//
// 对应接口：finance.AlipayAccountCheck.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.AlipayAccountCheck.search
func (s *AlipayAccountCheckService) Search(ctx context.Context, params *AlipayAccountCheckSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "finance.AlipayAccountCheck.search", pager, params)
}

// Search 收付款单查询 - 获取ERP内收付款单信息
//
// 起止时间跨度不超过30天
// 权限校验：【店铺权限】为了达到保护用户隐私数据安全的目的，本接口不返回淘系、拼多多及系统供销平台订单数据，相关平台规则点击这里，淘系及系统供销平台数据获取办法点击这里，拼多多请自行对接平台获取。
//
// 对应接口：finance.Payment.search
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=finance.Payment.search
func (s *FinancePaymentService) Search(ctx context.Context, params *FinancePaymentSearchParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "finance.Payment.search", pager, params)
}

// GetTradeLabel 订单标签查询 - 获取订单标签数据
// 支持
// start_time和end_time最大跨度为30天。
//
// 对应接口：setting.CustomAttr.getTradeLabel
// 文档：https://open.wangdian.cn/qjb/open/apidoc/doc?path=setting.CustomAttr.getTradeLabel
func (s *CustomAttrService) GetTradeLabel(ctx context.Context, params *CustomAttrGetTradeLabelParams, pager *Pager) (*Response, error) {
	return s.client.PageCall(ctx, "setting.CustomAttr.getTradeLabel", pager, params)
}
