# -*- coding: utf-8 -*-
"""根据 scripts/data/apis.json 生成 Go SDK 的服务层代码。

生成文件：services.go、trade.go、basic.go、goods.go、purchase.go、stock.go、refund.go、system.go
运行：python scripts/gen_sdk.py
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, ".."))
DATA = os.path.join(HERE, "data")

GENERATED_HEADER = (
    "// Code generated by scripts/gen_sdk.py from 旺店通旗舰版 API 文档; DO NOT EDIT.\n"
    "// 重新生成：python scripts/gen_sdk.py\n\n"
)

# 接口主题前缀 → Go 服务名
SERVICES = {
    "sales.TradeQuery": "TradeQuery",
    "sales.RawTrade": "RawTrade",
    "sales.LogisticsSync": "LogisticsSync",
    "sales.StockSync": "StockSync",
    "sales.TradeEdit": "TradeEdit",
    "sales.TradeImport": "TradeImport",
    "sales.Payment": "SalesPayment",
    "sales.jit.JitRefund": "SalesJitRefund",
    "wms.stockout.Sales": "StockoutSales",
    "finance.invoice.InvoiceOrder": "InvoiceOrder",
    "finance.RawPayment": "RawPayment",
    "finance.AlipayAccountCheck": "AlipayAccountCheck",
    "finance.Payment": "FinancePayment",
    "finance.StockCost": "StockCost",
    "finance.settle.Purchase": "SettlePurchase",
    "finance.settle.PurchaseReturn": "SettlePurchaseReturn",
    "finance.settle.Transfer": "SettleTransfer",
    "finance.settle.Logistics": "SettleLogistics",
    "finance.settle.OtherIn": "SettleOtherIn",
    "finance.settle.process": "SettleProcess",
    "setting.Shop": "Shop",
    "setting.Warehouse": "Warehouse",
    "setting.Logistics": "Logistics",
    "setting.PurchaseProvider": "PurchaseProvider",
    "setting.Employee": "Employee",
    "setting.CustomAttr": "CustomAttr",
    "setting.OperationReason": "OperationReason",
    "setting.Address": "Address",
    "setting.strategy.VirtualWarehouse": "VirtualWarehouse",
    "composite.Composite": "Composite",
    "goods.Goods": "Goods",
    "goods.Suite": "Suite",
    "goods.ApiGoods": "ApiGoods",
    "goods.GoodsClass": "GoodsClass",
    "goods.GoodsBrand": "GoodsBrand",
    "goods.Category": "Category",
    "goods.Barcode": "Barcode",
    "process.Bom": "Bom",
    "process.Process": "Process",
    "purchase.PurchaseOrder": "PurchaseOrder",
    "purchase.PurchaseReturn": "PurchaseReturn",
    "purchase.PurchaseApply": "PurchaseApply",
    "purchase.ProviderGoods": "ProviderGoods",
    "purchase.StockInPreOrder": "StockInPreOrder",
    "wms.stockin.Purchase": "StockinPurchase",
    "wms.stockout.PurchaseReturn": "StockoutPurchaseReturn",
    "wms.StockSpec": "StockSpec",
    "wms.StockPd": "StockPd",
    "wms.MoveOrder": "MoveOrder",
    "wms.stockin.Other": "StockinOther",
    "wms.stockout.Other": "StockoutOther",
    "wms.stockout.OtherQuery": "StockoutOtherQuery",
    "wms.stockin.Transfer": "StockinTransfer",
    "wms.stockout.Transfer": "StockoutTransfer",
    "wms.stocktransfer.Manage": "StockTransfer",
    "wms.stocktransfer.Edit": "StockTransferEdit",
    "wms.StockShelve": "StockShelve",
    "wms.stockother.In": "StockotherIn",
    "wms.stockother.InQuery": "StockotherInQuery",
    "wms.stockother.Out": "StockotherOut",
    "wms.stockother.OutQuery": "StockotherOutQuery",
    "wms.stockout.Process": "StockoutProcess",
    "wms.stockin.Process": "StockinProcess",
    "wms.outer.OuterIn": "OuterIn",
    "wms.outer.OuterOut": "OuterOut",
    "wms.outer.OuterTransfer": "OuterTransfer",
    "wms.stockdefect.DefectChange": "DefectChange",
    "wms.stockout.SalesPick": "SalesPick",
    "wms.PositionCapacity": "PositionCapacity",
    "wms.stockout.Pack": "Pack",
    "wms.stockin.JitRefund": "StockinJitRefund",
    "wms.stockout.JitOrder": "StockoutJitOrder",
    "wms.GoodsSN": "GoodsSN",
    "wms.GoodsBatch": "GoodsBatch",
    "wms.GoodsPack": "GoodsPack",
    "wms.stockin.Base": "StockinBase",
    "wms.stockout.Base": "StockoutBase",
    "wms.ErrorCorrection": "ErrorCorrection",
    "statistic.StockoutCollect": "StockoutCollect",
    "statistic.StockinCollect": "StockinCollect",
    "wms.stockin.Refund": "StockinRefund",
    "wms.stockin.PreStockin": "PreStockin",
    "wms.stockin.SmartRefund": "SmartRefund",
    "aftersales.refund.RawRefund": "RawRefund",
    "aftersales.refund.Refund": "Refund",
    "system.Core": "System",
}

CATEGORY_FILE = {
    "订单": "trade.go",
    "基础": "basic.go",
    "货品": "goods.go",
    "采购": "purchase.go",
    "库存": "stock.go",
    "售后": "refund.go",
}

PAGER_FIELDS = {"page_size", "page_no", "calc_total"}

GO_KEYWORDS = {
    "break", "case", "chan", "const", "continue", "default", "defer", "else",
    "fallthrough", "for", "func", "go", "goto", "if", "import", "interface",
    "map", "package", "range", "return", "select", "struct", "switch", "type", "var",
}

STRING_TYPES = {"string", "sring", "sting", "varchar", "char", "text", "date", "datetime", "timestamp"}
INT_TYPES = {"int", "integer", "short", "tinyint", "byte", "mediumint"}
INT64_TYPES = {"long", "bigint"}
FLOAT_TYPES = {"decimal", "bigdecimal", "double", "float", "number", "numeric"}
BOOL_TYPES = {"boolean", "bool"}


def norm_type(t):
    """规范化文档类型字符串。"""
    t = (t or "").strip()
    t = t.replace("＜", "<").replace("＞", ">").replace("（", "(").replace("）", ")")
    t = re.sub(r"\s+", " ", t)
    return t


def is_composite(t):
    t = norm_type(t)
    return "<" in t or t in ("Object", "object", "Map", "List")


def go_pascal(name):
    """snake_case / camelCase → PascalCase。"""
    parts = re.split(r"[_\-\s]+", (name or "").strip())
    out = []
    for p in parts:
        if not p:
            continue
        out.append(p[0].upper() + p[1:])
    s = "".join(out)
    s = re.sub(r"[^0-9A-Za-z_.]", "", s)
    return s


def go_lower(name):
    """snake_case → lowerCamel，用于 Go 参数名。"""
    s = go_pascal(name)
    if not s:
        return "arg"
    return s[0].lower() + s[1:]


def safe_param(name):
    """Go 形参名避开关键字与内置标识。"""
    if name in GO_KEYWORDS or name in ("string", "int", "int64", "float64", "bool", "byte", "len", "cap", "new", "make", "nil", "true", "false"):
        return name + "Val"
    return name


def merge_prefix(service, method):
    """合并服务名与方法名的重叠部分：TradeQuery+QueryWithDetail → TradeQueryWithDetail。"""
    for k in range(min(len(service), len(method)) - 1, 2, -1):
        if service.endswith(method[:k]):
            return service + method[k:]
    return service + method


def clean_desc(s):
    s = re.sub(r"\s+", " ", (s or "").strip())
    return s


def strip_list_suffix(field):
    """rawTradeList → rawTrade；用于推导集合元素的类型名。"""
    f = field
    for suf in ("_list", "_lists", "_infos", "_info", "List", "Lists", "Infos"):
        if f.endswith(suf) and len(f) > len(suf) + 1:
            f = f[: -len(suf)]
            break
    return f


class Struct:
    def __init__(self, name):
        self.name = name
        self.fields = []  # list of Field

    def go_name(self, taken):
        n = self.name
        i = 2
        while n in taken:
            n = self.name + str(i)
            i += 1
        taken.add(n)
        return n


class Field:
    def __init__(self, cn, name, typ, required, desc):
        self.cn = cn
        self.name = name  # JSON 字段名
        self.typ = typ    # 文档类型
        self.required = required
        self.desc = desc
        self.struct = None       # 复合类型的嵌套 Struct
        self.is_list = False
        self.go_name = go_pascal(name)
        # 同一结构体内重名字段处理在 emit 时进行


def is_pager_section(sec):
    fields = sec["fields"]
    return fields and all(f["field"] in PAGER_FIELDS for f in fields) and len(fields) >= 2


def parse_required(v):
    v = (v or "").strip().lower()
    return v in ("是", "y", "yes", "true", "必填", "1")


class SecIter:
    """章节迭代器：按文档顺序消费字段表，记录剩余未消费的章节。"""

    def __init__(self, secs):
        self.secs = list(secs)
        self.i = 0

    def next(self):
        if self.i < len(self.secs):
            s = self.secs[self.i]
            self.i += 1
            return s
        return None

    def leftover(self):
        return self.secs[self.i:]


def make_struct(gen, name_base, fields, sec_iter):
    st = Struct(name_base)
    for f in fields:
        fld = Field(f.get("cn", ""), f["field"], f.get("type", ""), parse_required(f.get("required")), f.get("desc", ""))
        if is_composite(fld.typ):
            sub = sec_iter.next()
            if sub is not None:
                sub_base = name_base + go_pascal(strip_list_suffix(fld.name))
                fld.struct = make_struct(gen, sub_base, sub["fields"], sec_iter)
                fld.is_list = "list" in norm_type(fld.typ).lower() or norm_type(fld.typ).startswith("<")
        st.fields.append(fld)
    return st


def go_type_of(fld):
    """返回 (Go类型, 是否需要 omitempty)。"""
    t = norm_type(fld.typ)
    tl = t.lower().replace(" ", "")
    opt = not fld.required
    if fld.struct is not None:
        name = fld.struct.go_name_final
        if fld.is_list:
            return "[]*" + name, opt
        return "*" + name, opt
    if "list<string>" in tl or tl == "string[]":
        return "[]string", opt
    if "list<" in tl or tl.startswith("<"):
        return "[]any", opt
    if "map<string,string>" in tl:
        return "map[string]string", opt
    if tl.startswith("map<") or tl in ("object", "map", "list"):
        return "any", opt
    if tl in STRING_TYPES:
        return "string", opt
    if tl in INT64_TYPES:
        return "int64", opt
    if tl in INT_TYPES:
        return "int", opt
    if tl in FLOAT_TYPES or tl.startswith("decimal(") or tl.startswith("bigdecimal("):
        return "float64", opt
    if tl in BOOL_TYPES:
        return "bool", opt
    return "any", opt


def emit_struct(gen, st, out):
    lines = []
    lines.append("type %s struct {" % st.go_name_final)
    seen = set()
    for f in st.fields:
        gn = f.go_name
        i = 2
        while gn in seen:
            gn = f.go_name + str(i)
            i += 1
        seen.add(gn)
        typ, omitempty = go_type_of(f)
        tag = '`json:"%s%s"`' % (f.name, ",omitempty" if omitempty else "")
        comment = f.cn or f.name
        extra = []
        if f.typ:
            extra.append(f.typ)
        extra.append("必填" if f.required else "选填")
        if f.desc:
            comment += "：" + clean_desc(f.desc)
        lines.append("\t// %s（%s）" % (comment, "，".join(extra)))
        lines.append("\t%s %s %s" % (gn, typ, tag))
    lines.append("}")
    out.extend(lines)


def arg_from_row(gen, prefix, row, sec_iter):
    """sig 行 → 顶层参数。"""
    name = row["name"]
    fld = Field(row.get("cn", ""), name, row.get("type", ""), parse_required(row.get("required", "是")), "")
    t = norm_type(fld.typ)
    tl = t.lower().replace(" ", "")
    if tl == "pager":
        return {"kind": "pager"}
    # List<String> / 裸 List：元素为标量，不消费嵌套章节
    if tl in ("list<string>", "string[]"):
        return {"kind": "strings", "field": fld, "go": safe_param(go_lower(name))}
    if tl in ("list", "list<object>", "object[]"):
        return {"kind": "anylist", "field": fld, "go": safe_param(go_lower(name))}
    if is_composite(t):
        sub = sec_iter.next()
        if sub is not None:
            base = prefix + go_pascal(strip_list_suffix(name))
            fld.struct = make_struct(gen, base, sub["fields"], sec_iter)
            fld.is_list = "list" in tl or tl.startswith("<")
        else:
            # 没有可消费的章节：退化为通用容器
            return {"kind": "anylist" if ("list" in tl or tl.startswith("<")) else "anymap",
                    "field": fld, "go": safe_param(go_lower(name))}
    if fld.struct is not None:
        kind = "list" if fld.is_list else "map"
    elif tl in STRING_TYPES:
        kind = "string"
    elif tl in INT_TYPES or tl in INT64_TYPES:
        kind = "int"
    elif tl in FLOAT_TYPES or tl.startswith("decimal(") or tl.startswith("bigdecimal("):
        kind = "float"
    elif tl in BOOL_TYPES:
        kind = "bool"
    else:
        kind = "scalar"
    return {"kind": kind, "field": fld, "go": safe_param(go_lower(name))}


def analyze_api(gen, api):
    """推断一个接口的调用形态。"""
    prefix = merge_prefix(api["service_go"], api["method_go"])
    sig = api.get("sdk_sig") or []
    req_secs = [s for s in api["req_sections"] if not is_pager_section(s)]
    has_pager = any(norm_type(r["type"]).lower() == "pager" for r in sig) or any(is_pager_section(s) for s in api["req_sections"])

    ov = OVERRIDES.get(api["method"])
    sec_iter = SecIter(req_secs)
    if ov:
        shape = ov["shape"]
        if shape == "list_of_struct":
            # 单个位置参数：结构体列表（示例为 [[{...}]]）
            sec0 = sec_iter.next()
            st = make_struct(gen, prefix + "Item", sec0["fields"], sec_iter)
            fld = Field(ov.get("cn", "参数列表"), ov.get("field", "list"), "List<Map<String, Object>>", True, "")
            fld.struct = st
            fld.is_list = True
            args = [{"kind": "list", "field": fld, "go": ov.get("go", "items")}]
        elif shape == "params_wrapped_list":
            # 包裹对象：{ "<field>": [ {...} ] }
            sec0 = sec_iter.next()
            wrapper = Struct(prefix + "Params")
            fname = ov["field"]
            f = Field(ov.get("cn", "数据列表"), fname, "List<Map<String, Object>>", True, "")
            f.struct = make_struct(gen, wrapper.name + go_pascal(strip_list_suffix(fname)), sec0["fields"], sec_iter)
            f.is_list = True
            wrapper.fields.append(f)
            args = [{"kind": "params", "struct": wrapper, "go": "params"}]
        else:
            args = []
        return {"prefix": prefix, "args": args, "has_pager": ov.get("has_pager", False), "leftover": sec_iter.leftover()}

    args = []

    if sig and any(norm_type(r["type"]).lower() != "pager" for r in sig):
        # 签名表描述了业务参数（位置参数或单个 params 对象）
        for row in sig:
            if norm_type(row["type"]).lower() == "pager" or row.get("name", "").lower() == "pager":
                # 名为 pager 的签名行视为分页参数（部分文档将其类型标为 Map）
                continue
            args.append(arg_from_row(gen, prefix, row, sec_iter))
    else:
        sec0 = sec_iter.next()
        if sec0 is not None:
            comps = [f for f in sec0["fields"] if is_composite(f["type"])]
            if not comps and example_is_positional_scalars(api, sec0):
                # 请求示例显示为位置标量参数（如 apiGoodsId, stockChangeCount）
                for f in sec0["fields"]:
                    row = {"name": f["field"], "cn": f.get("cn", ""), "type": f["type"], "required": f.get("required", "是")}
                    args.append(arg_from_row(gen, prefix, row, sec_iter))
            elif comps:
                # 位置参数：主表每个字段即一个参数
                for f in sec0["fields"]:
                    row = {"name": f["field"], "cn": f.get("cn", ""), "type": f["type"], "required": f.get("required", "是")}
                    args.append(arg_from_row(gen, prefix, row, sec_iter))
            else:
                # 单个 params 对象
                params_struct = make_struct(gen, prefix + "Params", sec0["fields"], sec_iter)
                args.append({"kind": "params", "struct": params_struct, "go": "params"})

    return {"prefix": prefix, "args": args, "has_pager": has_pager, "leftover": sec_iter.leftover()}


def example_is_positional_scalars(api, sec0):
    """请求示例为全标量且数量与字段数一致 → 位置标量参数。"""
    kinds = example_kinds(api.get("req_example", ""))
    return bool(kinds) and all(k == "scalar" for k in kinds) and len(kinds) == len(sec0["fields"])


# ---------------- 代码输出 ----------------

def emit_field_line(f):
    gn = f.go_name
    typ, omitempty = go_type_of(f)
    tag = '`json:"%s%s"`' % (f.name, ",omitempty" if omitempty else "")
    comment = f.cn or f.name
    extra = []
    if f.typ:
        extra.append(f.typ)
    extra.append("必填" if f.required else "选填")
    if f.desc:
        comment += "：" + clean_desc(f.desc)
    return ["\t// %s（%s）" % (comment, "，".join(extra)), "\t%s %s %s" % (gn, typ, tag)]


def emit_struct_full(st, out):
    out.append("type %s struct {" % st.go_name_final)
    seen = set()
    for f in st.fields:
        gn = f.go_name
        i = 2
        while gn in seen:
            gn = f.go_name + str(i)
            i += 1
        seen.add(gn)
        out.extend(emit_field_line(f))
    out.append("}")
    out.append("")


def emit_args_signature(args):
    """生成方法签名的参数列表与调用时的 args 表达式。"""
    kind_type = {
        "string": "string", "int": "int", "float": "float64", "bool": "bool", "scalar": "any",
        "strings": "[]string", "anylist": "[]any", "anymap": "map[string]any",
    }
    params, call_args = [], []
    for a in args:
        if a["kind"] == "params":
            params.append("%s *%s" % (a["go"], a["struct"].go_name_final))
            call_args.append(a["go"])
        elif a["kind"] in ("map", "list"):
            fld = a["field"]
            typ, _ = go_type_of(fld)
            params.append("%s %s" % (a["go"], typ))
            call_args.append(a["go"])
        elif a["kind"] == "pager":
            continue
        else:
            params.append("%s %s" % (a["go"], kind_type.get(a["kind"], "any")))
            call_args.append(a["go"])
    return params, call_args


def comment_block(lines):
    return "\n".join(("// " + l) if l else "//" for l in lines)


def emit_method(api, out):
    service = api["service"]
    method = api["method"]
    mg = api["method_go"]
    sg = api["service_go"]
    doc_url = "https://open.wangdian.cn/qjb/open/apidoc/doc?path=%s" % method
    desc = clean_desc(api.get("desc", ""))
    head = ["%s %s - %s" % (mg, api.get("name", ""), desc)]
    for meta in api.get("meta", []):
        m = meta.strip()
        if re.match(r"^1\.[3-9]", m) and len(m) < 160:
            head.append(re.sub(r"^1\.\d+[^：:]*[：:]\s*", "", m))
    head.append("")
    head.append("对应接口：%s" % method)
    head.append("文档：%s" % doc_url)

    info = api["analysis"]
    params, call_args = emit_args_signature(info["args"])
    if info["has_pager"]:
        params.append("pager *Pager")
    out.append(comment_block(head))
    call = "PageCall" if info["has_pager"] else "Call"
    if info["has_pager"]:
        # PageCall 的第三个参数是 *Pager
        call_args = ["pager"] + call_args
    call_args_src = ", ".join(call_args) if call_args else ""
    out.append("func (s *%sService) %s(ctx context.Context, %s) (*Response, error) {" % (sg, mg, ", ".join(params)))
    out.append('\treturn s.client.%s(ctx, "%s"%s%s)' % (call, method, ", " if call_args_src else "", call_args_src))
    out.append("}")
    out.append("")


# ---------------- 主流程 ----------------

OVERRIDES = {
    # system.Core.now 无业务参数
    "system.Core.now": {"shape": "none"},
    # 文档签名表标注为 List，但示例报文是 [{"data":[...]}] 包裹对象
    "sales.TradeEdit.modifyRemark": {"shape": "params_wrapped_list", "field": "data", "cn": "订单备注列表"},
    # 示例为 [[{...}]]：单个参数为对象列表
    "finance.invoice.InvoiceOrder.updateInvoice": {"shape": "list_of_struct", "field": "invoice_list", "cn": "发票更新列表"},
    "wms.GoodsBatch.createByApi": {"shape": "list_of_struct", "field": "batch_list", "cn": "批次列表"},
}


def service_for(method):
    """按最长前缀匹配服务名，返回 (主题前缀, Go服务名)。"""
    best = None
    for k in SERVICES:
        if method == k or method.startswith(k + "."):
            if best is None or len(k) > len(best):
                best = k
    if best is None:
        raise RuntimeError("未映射的服务前缀: %s" % method)
    return best, SERVICES[best]


def method_go_name(action):
    return go_pascal(action)


def walk_structs(args):
    """收集参数树中的全部 Struct（深度优先，保持文档顺序）。"""
    out = []

    def visit(st):
        out.append(st)
        for f in st.fields:
            if f.struct is not None:
                visit(f.struct)

    for a in args:
        if a.get("struct") is not None:
            visit(a["struct"])
        elif a.get("field") is not None and a["field"].struct is not None:
            visit(a["field"].struct)
    return out


def assign_names(structs, taken):
    for st in structs:
        n = st.name
        i = 2
        while n in taken:
            n = st.name + str(i)
            i += 1
        taken.add(n)
        st.go_name_final = n


def example_kinds(ex):
    """解析请求示例 JSON，返回元素类型列表：'dict'/'list'/'scalar'。"""
    try:
        arr = json.loads(ex)
    except ValueError:
        return None
    if not isinstance(arr, list):
        return None
    kinds = []
    for el in arr:
        if isinstance(el, dict):
            kinds.append("dict")
        elif isinstance(el, list):
            kinds.append("list")
        else:
            kinds.append("scalar")
    return kinds


def inferred_kinds(args):
    kinds = []
    for a in args:
        k = a["kind"]
        if k in ("params", "map", "anymap"):
            kinds.append("dict")
        elif k in ("list", "strings", "anylist"):
            kinds.append("list")
        else:
            kinds.append("scalar")
    return kinds


def validate_example(api):
    """用请求示例校验推断的参数形态，返回警告列表。"""
    ex = api.get("req_example")
    if not ex:
        return []
    kinds = example_kinds(ex)
    if kinds is None:
        return ["%s: 请求示例 JSON 解析失败" % api["method"]]
    inf = inferred_kinds(api["analysis"]["args"])
    if kinds == inf:
        return []
    # 允许示例省略尾部可选参数
    if len(kinds) <= len(inf) and kinds == inf[: len(kinds)]:
        return []
    return ["%s: 示例参数形态 %s 与推断 %s 不一致" % (api["method"], kinds, inf)]


def main():
    with open(os.path.join(DATA, "apis.json"), encoding="utf-8") as f:
        apis = json.load(f)["apis"]

    taken = set()
    files = {}  # filename -> {"structs": [], "methods": []}
    services = []  # (service_go, category_file)

    for api in apis:
        method = api["method"]
        api["service"], api["service_go"] = service_for(method)
        action = method.split(".")[-1]
        api["method_go"] = method_go_name(action)
        if api["category"] in CATEGORY_FILE:
            fname = CATEGORY_FILE[api["category"]]
        else:
            fname = "system.go"
        api["file"] = fname

        api["analysis"] = analyze_api(api, api)  # gen 参数未使用，传自身
        structs = walk_structs(api["analysis"]["args"])
        assign_names(structs, taken)
        api["structs"] = structs

        for w in validate_example(api):
            print("WARN:", w, file=sys.stderr)
        for s in api["analysis"]["leftover"]:
            print("WARN: %s: 未消费的字段表(%d 字段, 标题=%s)" % (method, len(s["fields"]), s["heading"][:30]), file=sys.stderr)

        if fname not in files:
            files[fname] = {"structs": [], "methods": []}
        files[fname]["structs"].extend(structs)
        files[fname]["methods"].append(api)
        services.append((api["service_go"], fname))

    # services.go：服务类型 + Services 结构体 + 装配
    seen_services = []
    for sg, _ in services:
        if sg not in seen_services:
            seen_services.append(sg)
    subject_of = {}
    for api in apis:
        subject_of.setdefault(api["service_go"], api["service"])
    out = [GENERATED_HEADER, "package wdt", ""]
    out.append("// Services 按业务主题分组暴露全部开放平台接口。")
    out.append("type Services struct {")
    for sg in seen_services:
        out.append("\t%s *%sService" % (sg, sg))
    out.append("}")
    out.append("")
    out.append("// newServices 初始化各业务服务。")
    out.append("func newServices(c *Client) {")
    for sg in seen_services:
        out.append("\tc.%s = &%sService{client: c}" % (sg, sg))
    out.append("}")
    write_file("services.go", "\n".join(out) + "\n")

    for fname, data in files.items():
        out = [GENERATED_HEADER, "package wdt", "", 'import "context"', ""]
        # 服务类型定义（每个服务的全部接口位于同一文件）
        file_services = []
        for api in data["methods"]:
            if api["service_go"] not in file_services:
                file_services.append(api["service_go"])
        for sg in file_services:
            out.append("// %sService 提供 %s.* 接口的封装。" % (sg, subject_of.get(sg, sg)))
            out.append("type %sService struct{ client *Client }" % sg)
            out.append("")
        # 去重结构体（同 API 结构体可能已在别处注册过；按对象标识去重）
        emitted = set()
        for st in data["structs"]:
            if id(st) in emitted:
                continue
            emitted.add(id(st))
            emit_struct_full(st, out)
        for api in data["methods"]:
            emit_method(api, out)
        write_file(fname, "\n".join(out) + "\n")

    print("generated: services.go +", ", ".join(sorted(files.keys())))


def write_file(name, content):
    path = os.path.join(ROOT, name)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print("wrote", name)


if __name__ == "__main__":
    main()
